<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $data = [
        //     // ["PersonnelNo" => "12345", "Name" => "ADMIN"],
        //     // ["PersonnelNo" => "123456", "Name" => "KARYAWAN"],
        //     ["PersonnelNo" => "421", "Name" => "DYAH AJENG PUSPA YUNITA"],
        //     // Tambahkan data lainnya...
        // ];

        $data = [
            // ["PersonnelNo" => "39", "Name" => "MARYUTI"],
            // ["PersonnelNo" => "36", "Name" => "MUHAMMAD AINUR ROSYIDDIN"],
            // ["PersonnelNo" => "61", "Name" => "SUCI ANINGSIH"],
            // ["PersonnelNo" => "48", "Name" => "NURMA MERDIANA"],
            // ["PersonnelNo" => "8100", "Name" => "ERIANDI SURBAKTI"],
            // ["PersonnelNo" => "8", "Name" => "ANDHAN LUPI WIRENI"],
            // ["PersonnelNo" => "41", "Name" => "MEILY HANDAYANI"],
            // ["PersonnelNo" => "45", "Name" => "NOVITA DWI WAHYUNI"],
            // ["PersonnelNo" => "23", "Name" => "FLORENSIA RETHA BUDIANTY"],
            // ["PersonnelNo" => "22", "Name" => "FAUZI ALVIANTO"],
            // ["PersonnelNo" => "74", "Name" => "YASHINTA MAHARANI HARIYADI"],
            // ["PersonnelNo" => "52", "Name" => "RATNA TUSI WULANDARI"],
            // ["PersonnelNo" => "59", "Name" => "SEPTIYAN YOGI BAHTIAR"],
            // ["PersonnelNo" => "16", "Name" => "DINDA SUKMAWATI"],
            // ["PersonnelNo" => "55", "Name" => "RISTIANTO"],
            // ["PersonnelNo" => "12", "Name" => "CAHYA RISKITA"],
            // ["PersonnelNo" => "7", "Name" => "ALVYANTI VIDIA FEBRIANI"],
            // ["PersonnelNo" => "67", "Name" => "SUSIO MUDJIONO"],
            // ["PersonnelNo" => "71", "Name" => "WAHYUDI"],
            // ["PersonnelNo" => "69", "Name" => "UMAR NURBANA"],
            // ["PersonnelNo" => "166", "Name" => "SINTA MAHARANI"],
            // ["PersonnelNo" => "58", "Name" => "SALSABILA AISYAH BUNDARTI"],
            // ["PersonnelNo" => "1", "Name" => "MUCHTAR LUTHFI MALIK AL AZHAR"],
            // ["PersonnelNo" => "169", "Name" => "ABIM SURYA MAHENDRA"],
            // ["PersonnelNo" => "9151", "Name" => "ADE FIKI JULIANDA"],
            // ["PersonnelNo" => "9007", "Name" => "Ali Imron Rosyidi"],
            // ["PersonnelNo" => "106", "Name" => "ROCHMANI"],
            // ["PersonnelNo" => "171", "Name" => "ANDRE AGASI NOR RIHI"],
            // ["PersonnelNo" => "9010", "Name" => "ANIS PUJI SARINI"],
            // ["PersonnelNo" => "9011", "Name" => "ANITA NUR FADILA"],
            // ["PersonnelNo" => "182", "Name" => "ARIEL SEPTIAN RIVELLINO"],
            // ["PersonnelNo" => "9113", "Name" => "AYU NUR RASTIN"],
            // ["PersonnelNo" => "175", "Name" => "CHEVA ANIN INDRIYANI"],
            // ["PersonnelNo" => "9116", "Name" => "DELLA DAMAYANTI"],
            // ["PersonnelNo" => "78", "Name" => "DEDI IRAWAN"],
            // ["PersonnelNo" => "9117", "Name" => "Dodik Kurniawan"],
            // ["PersonnelNo" => "9123", "Name" => "ERLI KUSTANTI"],
            // ["PersonnelNo" => "170", "Name" => "FERI WIBOWO TRI PRASTIYO"],
            // ["PersonnelNo" => "113", "Name" => "WIJAYA KUSUMA"],
            // ["PersonnelNo" => "172", "Name" => "HERI TEGUH ARIFIANTO"],
            // ["PersonnelNo" => "9153", "Name" => "Iana Hanifah"],
            // ["PersonnelNo" => "9129", "Name" => "IMROATUN LADHIFAH"],
            // ["PersonnelNo" => "115", "Name" => "NANDA GITA SHAFIRA"],
            // ["PersonnelNo" => "161", "Name" => "INDRA KURNIAWAN PRASETYO"],
            // ["PersonnelNo" => "9132", "Name" => "JOKO MARTOPO"],
            // ["PersonnelNo" => "150", "Name" => "MAGDALENA DAMAI PRAMUDIA"],
            // ["PersonnelNo" => "9137", "Name" => "MAIMANAH"],
            // ["PersonnelNo" => "9138", "Name" => "MEGA PUTRI LIA ANJANI"],
            // ["PersonnelNo" => "213", "Name" => "MOHAMMAD IQBAL SYAIFUDIN"],
            // ["PersonnelNo" => "92", "Name" => "SITI SOEDARMI"],
            // ["PersonnelNo" => "9052", "Name" => "NADYA ANISAFITRI"],
            // ["PersonnelNo" => "9146", "Name" => "NASRIYA"],
            // ["PersonnelNo" => "127", "Name" => "HERNOWO YUDHA PRABOWO"],
            // ["PersonnelNo" => "9148", "Name" => "PALUPI HANDITASARI"],
            // ["PersonnelNo" => "95", "Name" => "SLAMET PRIYANTO"],
            // ["PersonnelNo" => "98", "Name" => "MUHAMMAD AFIFAN"],
            // ["PersonnelNo" => "9149", "Name" => "RATNA PUJIATI"],
            // ["PersonnelNo" => "9062", "Name" => "RITA BINA WATI"],
            // ["PersonnelNo" => "9063", "Name" => "RIZKI DWI WITANTO"],
            // ["PersonnelNo" => "159", "Name" => "RUSWANTO"],
            // ["PersonnelNo" => "155", "Name" => "SIGIT BUDIANTO"],
            // ["PersonnelNo" => "9068", "Name" => "SITI ALFIYAH"],
            // ["PersonnelNo" => "9150", "Name" => "STEFANI SELVIA SARI"],
            // ["PersonnelNo" => "163", "Name" => "SULIANTO"],
            // ["PersonnelNo" => "129", "Name" => "BENY RATNO"],
            // ["PersonnelNo" => "9074", "Name" => "SUTIASE"],
            // ["PersonnelNo" => "130", "Name" => "SUBEKI PURNOMO"],
            // ["PersonnelNo" => "5007", "Name" => "HAYUN RATNA PUSPITASARI"],
            // ["PersonnelNo" => "5005", "Name" => "DITA NAUMI AYU ERLIANA"],
            // ["PersonnelNo" => "5009", "Name" => "NOVI ENDAH PUSPITASARI"],
            // ["PersonnelNo" => "9081", "Name" => "URIFAH"],
            // ["PersonnelNo" => "9155", "Name" => "VIVI NOVITASARI TRI WAHYUNINGTYAS"],
            // ["PersonnelNo" => "8068", "Name" => "PIPIN FITRIYANTO"],
            // ["PersonnelNo" => "8045", "Name" => "HENDRA SETIAWAN"],
            // ["PersonnelNo" => "8069", "Name" => "PUTU MAHENDRA"],
            // ["PersonnelNo" => "8052", "Name" => "IRVAN"],
            // ["PersonnelNo" => "8013", "Name" => "Anisa Moha"],
            // ["PersonnelNo" => "8078", "Name" => "SISKA"],
            // ["PersonnelNo" => "8016", "Name" => "Ayu Wandari"],
            // ["PersonnelNo" => "8044", "Name" => "HENDRA PALEMBANGAN"],
            // ["PersonnelNo" => "8060", "Name" => "MUCHAMMAD FAISOL"],
            // ["PersonnelNo" => "8074", "Name" => "ROSSI BASTIYAR"],
            // ["PersonnelNo" => "8019", "Name" => "CHRISTI SUSIE MURNIATY"],
            // ["PersonnelNo" => "8062", "Name" => "MUHAMMAD AZHARI ABDI"],
            // ["PersonnelNo" => "8063", "Name" => "NELSON KIAMANI"],
            // ["PersonnelNo" => "9084", "Name" => "YENI DWI PURBA"],
            // ["PersonnelNo" => "8057", "Name" => "MEI"],
            // ["PersonnelNo" => "8080", "Name" => "SITI ROHANI"],
            // ["PersonnelNo" => "8022", "Name" => "DEDI KAIMUDDIN"],
            // ["PersonnelNo" => "102", "Name" => "WINDU HANDAYANI"],
            // ["PersonnelNo" => "8072", "Name" => "RISKA LANDRIANI"],
            // ["PersonnelNo" => "8041", "Name" => "FRIDA ANDINA"],
            // ["PersonnelNo" => "8038", "Name" => "FAHRUL SEPTIAN AMIN"],
            // ["PersonnelNo" => "8065", "Name" => "NIRMALA"],
            // ["PersonnelNo" => "5016", "Name" => "NURHAEPA"],
            // ["PersonnelNo" => "8051", "Name" => "INDRI RESPATI HAYUNINGTYAS"],
            // ["PersonnelNo" => "8061", "Name" => "MUHAMMAD AGUNG HIDAYAT"],
            // ["PersonnelNo" => "8073", "Name" => "ROFIUDIN ANDRIANTO"],
            // ["PersonnelNo" => "8017", "Name" => "BAYU WIJAYA"],
            // ["PersonnelNo" => "8071", "Name" => "Rika Meilinda Dwi L"],
            // ["PersonnelNo" => "70013", "Name" => "WAHYU ARIF SAPUTRA"],
            // ["PersonnelNo" => "8055", "Name" => "KOMANG DEDDY MEGA SUDARMAWAN"],
            // ["PersonnelNo" => "8028", "Name" => "DIAN TRISNA PUTRI"],
            // ["PersonnelNo" => "8033", "Name" => "EKI ERVANDI"],
            // ["PersonnelNo" => "70003", "Name" => "AFANDI"],
            // ["PersonnelNo" => "8002", "Name" => "ADE DWI JAYANTI"],
            // ["PersonnelNo" => "8050", "Name" => "Ika Siwi Suprapti"],
            // ["PersonnelNo" => "70005", "Name" => "DWI FEBRIANSYAH"],
            // ["PersonnelNo" => "5001", "Name" => "FATIMATUS ZAHROH"],
            // ["PersonnelNo" => "8042", "Name" => "HABSI ARDIANSYAH"],
            // ["PersonnelNo" => "8025", "Name" => "DERIANTO RAHMAN"],
            // ["PersonnelNo" => "8046", "Name" => "HENDRI ISMANTO"],
            // ["PersonnelNo" => "8015", "Name" => "ARI WIBOWO"],
            // ["PersonnelNo" => "8031", "Name" => "DWI KHOIRIYAH"],
            // ["PersonnelNo" => "8035", "Name" => "Elly Sumarni Wawi"],
            // ["PersonnelNo" => "8011", "Name" => "ANGGA PRAYOGA"],
            // ["PersonnelNo" => "70007", "Name" => "SUGENG"],
            // ["PersonnelNo" => "8037", "Name" => "FADILA LAGAUTU"],
            // ["PersonnelNo" => "8053", "Name" => "JEPRI KARTAGUNA"],
            // ["PersonnelNo" => "8054", "Name" => "Jon Fereddy Hutabarat"],
            // ["PersonnelNo" => "5013", "Name" => "WIWIN"],
            // ["PersonnelNo" => "148", "Name" => "DINIA RAMADHAN NINGRUM HAS"],
            // ["PersonnelNo" => "165", "Name" => "ALDO PRAVISTA GABRIEL"],
            // ["PersonnelNo" => "139", "Name" => "DEBORA INGGRID KARUNIA"],
            // ["PersonnelNo" => "185", "Name" => "MARSHELIA TANNUS"],
            // ["PersonnelNo" => "146", "Name" => "YOHANA ALICIA"],
            // ["PersonnelNo" => "138", "Name" => "MOCH DEFRI RIZA ISTIANTO"],
            // ["PersonnelNo" => "181", "Name" => "ENDANG YULVIANTI"],
            // ["PersonnelNo" => "173", "Name" => "SUPRIYANTO"],
            // ["PersonnelNo" => "176", "Name" => "RIZKI ALDILLA"],
            // ["PersonnelNo" => "174", "Name" => "WARAS SETIAWAN"],
            // ["PersonnelNo" => "180", "Name" => "SITI JULAIKHAH"],
            // ["PersonnelNo" => "160", "Name" => "LEMUEL OKTAVIANUS DARMAWAN"],
            // ["PersonnelNo" => "157", "Name" => "M. NUR AROSI"],
            // ["PersonnelNo" => "136", "Name" => "MOKH RIZAL"],
            // ["PersonnelNo" => "8083", "Name" => "SUHARYATIK"],
            // ["PersonnelNo" => "8026", "Name" => "DEVISA ISKANDAR"],
            // ["PersonnelNo" => "8890", "Name" => "IFAN FAHMI"],
            // ["PersonnelNo" => "8891", "Name" => "IRMA ERVIANA"],
            // ["PersonnelNo" => "8892", "Name" => "MESI ARSITA"],
            // ["PersonnelNo" => "8893", "Name" => "ANNISA REGITA"],
            // ["PersonnelNo" => "8895", "Name" => "PUTRI LISDA PERMATA SARI"],
            // ["PersonnelNo" => "8896", "Name" => "HARRIS AGUNG WICAKSONO"],
            // ["PersonnelNo" => "8087", "Name" => "WIDIANTO"],
            // ["PersonnelNo" => "8027", "Name" => "DHANI IKHSAN DERMAWAN"],
            // ["PersonnelNo" => "8897", "Name" => "ASRI AGUNG"],
            // ["PersonnelNo" => "8007", "Name" => "AMELIA TANTO"],
            // ["PersonnelNo" => "8090", "Name" => "YOHANES BILLY THERYUZ FAREZA BARENS"],
            // ["PersonnelNo" => "8112", "Name" => "PARLUHUTAN RAMBE"],
            // ["PersonnelNo" => "8012", "Name" => "ANGGIANA NOVITASARI"],
            // ["PersonnelNo" => "8034", "Name" => "ELEANOR FERDINAND VALENTINO"],
            // ["PersonnelNo" => "192", "Name" => "EUNIKE RIAHTA TARIGAN"],
            // ["PersonnelNo" => "190", "Name" => "DWI JULIA BISMAWATI"],
            // ["PersonnelNo" => "9006", "Name" => "MUHAMMAD ALDI ZAKARIA"],
            // ["PersonnelNo" => "9045", "Name" => "MOHAMMAD FERRY ARDIANSYAH"],
            // ["PersonnelNo" => "9053", "Name" => "NASIFUDIN AKBAR"],
            // ["PersonnelNo" => "9064", "Name" => "SAFI ANI RAHAYU"],
            // ["PersonnelNo" => "9066", "Name" => "SANDI ANTI NINGTYAS"],
            // ["PersonnelNo" => "9067", "Name" => "SINTA AYU K"],
            // ["PersonnelNo" => "9073", "Name" => "SULAMI"],
            // ["PersonnelNo" => "193", "Name" => "TIVANA DEWI FEBRIANY"],
            // ["PersonnelNo" => "9112", "Name" => "TONI HIMAWAN"],
            // ["PersonnelNo" => "8004", "Name" => "AGUS NILAWATI"],
            // ["PersonnelNo" => "8009", "Name" => "ANDRI YANA"],
            // ["PersonnelNo" => "8010", "Name" => "ANGGA KURNIAWAN"],
            // ["PersonnelNo" => "8020", "Name" => "DANI IRAWAN"],
            // ["PersonnelNo" => "70010", "Name" => "DENI HARIADI"],
            // ["PersonnelNo" => "5008", "Name" => "HETTY FITRIANA"],
            // ["PersonnelNo" => "8084", "Name" => "TAUFIK AMRI"],
            // ["PersonnelNo" => "9108", "Name" => "TIFLATUS SHULKHA"],
            // ["PersonnelNo" => "9106", "Name" => "SOFA YUNIAR KURNIASARI"],
            // ["PersonnelNo" => "9154", "Name" => "SITI NUR ASIA"],
            // ["PersonnelNo" => "9105", "Name" => "SHOFIYAH NUGRAHA SALSABILA"],
            // ["PersonnelNo" => "9104", "Name" => "RETNO KRISDIANTO"],
            // ["PersonnelNo" => "9103", "Name" => "NUR HIDAYATI"],
            // ["PersonnelNo" => "9102", "Name" => "NOVIA DWI SULISTIYOWATI"],
            // ["PersonnelNo" => "9101", "Name" => "NENNY NUR A"],
            // ["PersonnelNo" => "5006", "Name" => "FITRI RAHMAWATI"],
            // ["PersonnelNo" => "9094", "Name" => "FINA PRINDIANI"],
            // ["PersonnelNo" => "9092", "Name" => "EKA NUR FAUZIAH"],
            // ["PersonnelNo" => "9089", "Name" => "BAIDAH"],
            // ["PersonnelNo" => "9087", "Name" => "ANISYA NURUL CINTYA ZAHRA"],
            // ["PersonnelNo" => "9085", "Name" => "ANIFFA ROSSIANA"],
            // ["PersonnelNo" => "9156", "Name" => "ULVIA"],
            // ["PersonnelNo" => "194", "Name" => "FAJAR NUGRAHA"],
            // ["PersonnelNo" => "8113", "Name" => "AKBAR"],
            // ["PersonnelNo" => "8115", "Name" => "MAYA SARI"],
            // ["PersonnelNo" => "8116", "Name" => "RYAN HIDAYAT"],
            // ["PersonnelNo" => "8117", "Name" => "KRISTIANDI"],
            // ["PersonnelNo" => "8108", "Name" => "TRI HARIONO"],
            // ["PersonnelNo" => "8118", "Name" => "RUDI FIRDAUS"],
            // ["PersonnelNo" => "8109", "Name" => "MUH.NASYIR"],
            // ["PersonnelNo" => "198", "Name" => "VERO INDRA MARDANY"],
            // ["PersonnelNo" => "5026", "Name" => "MAWAR WULANDARI"],
            // ["PersonnelNo" => "5003", "Name" => "KISI ANJALI"],
            // ["PersonnelNo" => "135", "Name" => "MUHAMAD SARIONO"],
            // ["PersonnelNo" => "199", "Name" => "FEBIANANTO RIZKY ASTIA PUTRA"],
            // ["PersonnelNo" => "200", "Name" => "M. IQFAN NURINDRA"],
            // ["PersonnelNo" => "70011", "Name" => "SUDIRO"],
            // ["PersonnelNo" => "8122", "Name" => "HARDIAN SYAHPUTRA"],
            // ["PersonnelNo" => "8123", "Name" => "RUDI SUHENDRA"],
            // ["PersonnelNo" => "9158", "Name" => "MUHAMMAD AFIFAN REMBUK"],
            // ["PersonnelNo" => "202", "Name" => "NOFANDI PRASETYO"],
            // ["PersonnelNo" => "9160", "Name" => "AGUS HARIONO"],
            // ["PersonnelNo" => "9161", "Name" => "MOCH. DANNY AMANNULLAH"],
            // ["PersonnelNo" => "204", "Name" => "HENDRA ADI SURYANTO"],
            // ["PersonnelNo" => "203", "Name" => "MOHAMMAD TRI BAHANA LAZAURDI"],
            // ["PersonnelNo" => "207", "Name" => "NATALIA PUSPITA SARI"],
            // ["PersonnelNo" => "9163", "Name" => "RE DYANSYAH PUTRA"],
            // ["PersonnelNo" => "8134", "Name" => "DEWI ZULAIKHAH"],
            // ["PersonnelNo" => "8129", "Name" => "LOLA JOHN FEBYSCA"],
            // ["PersonnelNo" => "8137", "Name" => "MARSELINA"],
            // ["PersonnelNo" => "8125", "Name" => "MUH. NASYIR"],
            // ["PersonnelNo" => "8131", "Name" => "NELWINDA MASHANAFI"],
            // ["PersonnelNo" => "8135", "Name" => "KRISTIANDI"],
            // ["PersonnelNo" => "8133", "Name" => "MANSYUR SULAIMAN"],
            // ["PersonnelNo" => "8128", "Name" => "M. BUHARI IRVAN"],
            // ["PersonnelNo" => "8136", "Name" => "PIPIT FITRIWANI KOTO"],
            // ["PersonnelNo" => "8124", "Name" => "ASTRIANDANY IDEA KARSA"],
            // ["PersonnelNo" => "8130", "Name" => "LIA FATHURAHMAH"],
            // ["PersonnelNo" => "8138", "Name" => "IDAYANTI"],
            // ["PersonnelNo" => "8126", "Name" => "PRISKILA CLAUDIA YUNI RAMBA"],
            // ["PersonnelNo" => "70014", "Name" => "AWALUDIN  MULYONO"],
            // ["PersonnelNo" => "70015", "Name" => "HUSEN MAULANA"],
            // ["PersonnelNo" => "8139", "Name" => "RATNI L HALINDIS"],
            // ["PersonnelNo" => "5014", "Name" => "EKA NUR SAFITRIH"],
            // ["PersonnelNo" => "8146", "Name" => "ISNAWATI"],
            // ["PersonnelNo" => "8145", "Name" => "ELPINA PIDIAWATI"],
            // ["PersonnelNo" => "8144", "Name" => "SERLI SEPTAYUDA"],
            // ["PersonnelNo" => "8143", "Name" => "HELTON SUEJARWO"],
            // ["PersonnelNo" => "8142", "Name" => "IKA WIDIYANINGSIH"],
            // ["PersonnelNo" => "5019", "Name" => "ULFA AMALIA NURJANAH"],
            // ["PersonnelNo" => "209", "Name" => "AGIL DANANG PRABOWO"],
            // ["PersonnelNo" => "9996", "Name" => "YENI IIS SHOLIKHAH"],
            // ["PersonnelNo" => "70016", "Name" => "II HIDAYAT"],
            // ["PersonnelNo" => "212", "Name" => "FAHMI ULA"],
            // ["PersonnelNo" => "9162", "Name" => "ALFIAN FATKHUR ROKHIM"],
            // ["PersonnelNo" => "9164", "Name" => "TRIO RAMADHANI"],
            // ["PersonnelNo" => "214", "Name" => "ACHMAD REZAL ELI EFENDY"],
            // ["PersonnelNo" => "8148", "Name" => "APRILIA DARASMANTI"],
            // ["PersonnelNo" => "215", "Name" => "EKO YUDI PURWANTO"],
            // ["PersonnelNo" => "218", "Name" => "KUDORI"],
            // ["PersonnelNo" => "219", "Name" => "LUQMAN HAKIM"],
            // ["PersonnelNo" => "70019", "Name" => "FERA MARDIANA"],
            // ["PersonnelNo" => "70017", "Name" => "SITI AMINAH(JKT)"],
            // ["PersonnelNo" => "220", "Name" => "DEDI SETYAWAN"],
            // ["PersonnelNo" => "9166", "Name" => "ANGGI ARDIANSYAH"],
            // ["PersonnelNo" => "8150", "Name" => "ARISWANTO"],
            // ["PersonnelNo" => "5020", "Name" => "SEPTA OKTARIA"],
            // ["PersonnelNo" => "8152", "Name" => "FAIREL DAME"],
            // ["PersonnelNo" => "9167", "Name" => "BELA RIZALATUL CHANIFAH"],
            // ["PersonnelNo" => "9168", "Name" => "MUHAMMAD BASHORI ILHAM"],
            // ["PersonnelNo" => "9169", "Name" => "HERIBERTUS RICKY NOVANDA"],
            // ["PersonnelNo" => "9170", "Name" => "RANGGA IRGIWAHYU FAHREZI"],
            // ["PersonnelNo" => "9171", "Name" => "WIDIA NANDA FAJAR"],
            // ["PersonnelNo" => "9172", "Name" => "AYU RAHMAWATI"],
            // ["PersonnelNo" => "9173", "Name" => "KARINA ROEMI KHAFIFAH"],
            // ["PersonnelNo" => "9174", "Name" => "CHUSNUL WULANDARI"],
            // ["PersonnelNo" => "9175", "Name" => "INNE YULIA NUR FITRIASYARI"],
            // ["PersonnelNo" => "9176", "Name" => "DINDA RIKA UMI FATONA"],
            // ["PersonnelNo" => "70018", "Name" => "MAHDI"],
            // ["PersonnelNo" => "5025", "Name" => "YUAN APRILLIA"],
            // ["PersonnelNo" => "5017", "Name" => "SUTMA VAN GOBEL"],
            // ["PersonnelNo" => "222", "Name" => "IMAM MUSLIM"],
            // ["PersonnelNo" => "8158", "Name" => "MAYASARI"],
            // ["PersonnelNo" => "5018", "Name" => "RIANTY DALENO"],
            // ["PersonnelNo" => "70020", "Name" => "TRIWULAN AGUSTIN"],
            // ["PersonnelNo" => "202108", "Name" => "MUHAMMAD ANDI WIJAYA"],
            // ["PersonnelNo" => "202107", "Name" => "ILHAM BAGUS PRADANA"],
            // ["PersonnelNo" => "70021", "Name" => "EKO FRIBUNA"],
            // ["PersonnelNo" => "5021", "Name" => "FIKI OCTAVIA DEWI"],
            // ["PersonnelNo" => "5022", "Name" => "REMBULAN NUR SUKARMI"],
            // ["PersonnelNo" => "202106", "Name" => "AYUB EKO HARI SETYAWAN"],
            // ["PersonnelNo" => "5023", "Name" => "YUNIA RISTA MANDAK"],
            // ["PersonnelNo" => "202105", "Name" => "EVA AMALIYA"],
            // ["PersonnelNo" => "224", "Name" => "TITIS SARI DWI SEPTEVY"],
            // ["PersonnelNo" => "5024", "Name" => "ELLYSDA SAGITA DOSIOFA"],
            // ["PersonnelNo" => "9177", "Name" => "SULUNG BACHTIAR"],
            // ["PersonnelNo" => "9178", "Name" => "APRILIA DWI KURNIAWATI"],
            // ["PersonnelNo" => "9180", "Name" => "GABRIELLE LORENZA"],
            // ["PersonnelNo" => "9181", "Name" => "VELLY ANGGRAENI"],
            // ["PersonnelNo" => "9182", "Name" => "MAHMUDAH"],
            // ["PersonnelNo" => "9183", "Name" => "SITI MUSA ADAH"],
            // ["PersonnelNo" => "9184", "Name" => "YENNY SRI WAHYUNI"],
            // ["PersonnelNo" => "9185", "Name" => "NISMAQUL UMMA"],
            // ["PersonnelNo" => "9186", "Name" => "TITIN HERMAYANTI"],
            // ["PersonnelNo" => "9187", "Name" => "AYU KURNIA FEBRI OLOWATI"],
            // ["PersonnelNo" => "9188", "Name" => "NOVIA NUR ROHMA"],
            // ["PersonnelNo" => "9189", "Name" => "DINDA SAFIRA AZZAHRO"],
            // ["PersonnelNo" => "9191", "Name" => "FENI RAHMAWATI AGUSTIN"],
            // ["PersonnelNo" => "9193", "Name" => "DWI HARYANTO"],
            // ["PersonnelNo" => "9194", "Name" => "AULIA FERUCA KUMALA"],
            // ["PersonnelNo" => "225", "Name" => "INDRA RIZKY HALIM PRATAMA"],
            // ["PersonnelNo" => "5027", "Name" => "MAULIDAH"],
            // ["PersonnelNo" => "8898", "Name" => "AMELLIA NURFAIDA"],
            // ["PersonnelNo" => "9990", "Name" => "WULAN MAHARDIKA"],
            // ["PersonnelNo" => "9991", "Name" => "SURIANI DJAFAR"],
            // ["PersonnelNo" => "9995", "Name" => "MUHAMMAD VIJAY"],
            // ["PersonnelNo" => "9993", "Name" => "DORA PEBRI LIANTY"],
            // ["PersonnelNo" => "9994", "Name" => "FENO TRIADI"],
            // ["PersonnelNo" => "227", "Name" => "ACHMAD DENDY KURNIAWAN"],
            // ["PersonnelNo" => "5028", "Name" => "MITA BONITA"],
            // ["PersonnelNo" => "9197", "Name" => "TRIZKA NURMALA SARI"],
            // ["PersonnelNo" => "9198", "Name" => "YOSI SUTINAR WULANDARI"],
            // ["PersonnelNo" => "9200", "Name" => "SITTA MAULIYA PUTRI"],
            // ["PersonnelNo" => "9201", "Name" => "DINA NOVITA SARI"],
            // ["PersonnelNo" => "9202", "Name" => "YANTI"],
            // ["PersonnelNo" => "9203", "Name" => "SAMSUL ISWAHYUDI"],
            // ["PersonnelNo" => "9204", "Name" => "HANIFAH ELYUCI RAMADANI"],
            // ["PersonnelNo" => "9205", "Name" => "RISA SALSA BELLA FIRDA"],
            // ["PersonnelNo" => "229", "Name" => "VINA ABRIAMNIE"],
            // ["PersonnelNo" => "9207", "Name" => "YUSRIL ISYAMA HENDRA"],
            // ["PersonnelNo" => "5029", "Name" => "INDAR SUCIANTI"],
            // ["PersonnelNo" => "5030", "Name" => "OLIVIA LAIHAD"],
            // ["PersonnelNo" => "233", "Name" => "YUDI PRASETYO"],
            // ["PersonnelNo" => "9208", "Name" => "ARNANDO HADI WIRANATA"],
            // ["PersonnelNo" => "9209", "Name" => "ILYAS MARDIYANTO"],
            // ["PersonnelNo" => "8181", "Name" => "DAVID NUGROHO TRI"],
            // ["PersonnelNo" => "9998", "Name" => "MOHAMAD FAIZAL"],
            // ["PersonnelNo" => "9210", "Name" => "SRI MARTININGSIH"],
            // ["PersonnelNo" => "234", "Name" => "PUTRI SEPTIANITA RACHMAWATI"],
            // ["PersonnelNo" => "9215", "Name" => "ERVINA AGUSTIN"],
            // ["PersonnelNo" => "9213", "Name" => "YUNIA ROSIDAH"],
            // ["PersonnelNo" => "9214", "Name" => "SINTYA DWI AGUSTIN"],
            // ["PersonnelNo" => "70022", "Name" => "LUTHFI ADITYA  NUGRAHA"],
            // ["PersonnelNo" => "70023", "Name" => "EKA CIPTAWIJAYA"],
            // ["PersonnelNo" => "7024", "Name" => "BAYU PURNOMO"],
            // ["PersonnelNo" => "92120", "Name" => "INDAH NAWANGSARI"],
            // ["PersonnelNo" => "92121", "Name" => "MUHAMAD FADLI"],
            // ["PersonnelNo" => "92122", "Name" => "LODIAH TANUWIJAYA"],
            // ["PersonnelNo" => "236", "Name" => "ANDRIK IRAWAN"],
            // ["PersonnelNo" => "237", "Name" => "NATASYA BERNIKA OLIVIA IVADA"],
            // ["PersonnelNo" => "238", "Name" => "PUTRI RATNA SARI"],
            // ["PersonnelNo" => "240", "Name" => "MOH BAGUS LUQMAN HAQIQI"],
            // ["PersonnelNo" => "241", "Name" => "RIO EFFANDA. AMD"],
            // ["PersonnelNo" => "5032", "Name" => "ROSDIANA PAMUNGKAS HS"],
            // ["PersonnelNo" => "70024", "Name" => "EMHA"],
            // ["PersonnelNo" => "258", "Name" => "YOPI ANTARIKSA"],
            // ["PersonnelNo" => "5034", "Name" => "RANI AYU WARDANI"],
            // ["PersonnelNo" => "5035", "Name" => "KIKI INDAHSARI"],
            // ["PersonnelNo" => "8163", "Name" => "DHIANIKA ENY ARYATI"],
            // ["PersonnelNo" => "8168", "Name" => "CAHYO HADI SUSANDI"],
            // ["PersonnelNo" => "8167", "Name" => "RAHIMA SHARA DIPA"],
            // ["PersonnelNo" => "8166", "Name" => "TOMI LESMANA GELIAN"],
            // ["PersonnelNo" => "8165", "Name" => "MALAYANTI SITUMORANG"],
            // ["PersonnelNo" => "8164", "Name" => "SWASTIKA ADI SURANTA"],
            // ["PersonnelNo" => "8174", "Name" => "FUAD BIDOL"],
            // ["PersonnelNo" => "8173", "Name" => "IRWAN"],
            // ["PersonnelNo" => "8172", "Name" => "RAHMAT MANSYUR"],
            // ["PersonnelNo" => "8171", "Name" => "ERMA DAMAYANTI"],
            // ["PersonnelNo" => "8170", "Name" => "DESI NURMALA HAMNI"],
            // ["PersonnelNo" => "5036", "Name" => "PUTRI IMELIA AJENG PRIANTI"],
            // ["PersonnelNo" => "5037", "Name" => "YULIANINGSIH"],
            // ["PersonnelNo" => "5039", "Name" => "MUTIARA ANNISA"],
            // ["PersonnelNo" => "261", "Name" => "SUSELO BARA PERSADA"],
            // ["PersonnelNo" => "262", "Name" => "JUMINTAR"],
            // ["PersonnelNo" => "9217", "Name" => "FAUZIYAH"],
            // ["PersonnelNo" => "5038", "Name" => "RIKA AGUSTIN"],
            // ["PersonnelNo" => "70025", "Name" => "ADE MULYANI"],
            // ["PersonnelNo" => "8178", "Name" => "SABRINA LEOVITA"],
            // ["PersonnelNo" => "8177", "Name" => "NUR ALAMSYAH"],
            // ["PersonnelNo" => "8176", "Name" => "YOUNGKY NUR HIDAYAT"],
            // ["PersonnelNo" => "8175", "Name" => "NOVIARA ANGELIA"],
            // ["PersonnelNo" => "267", "Name" => "RENDRA PRATAMA PUTRA"],
            // ["PersonnelNo" => "8180", "Name" => "PURWANTI"],
            // ["PersonnelNo" => "5041", "Name" => "WINDA NURFADILAH"],
            // ["PersonnelNo" => "271", "Name" => "ABDI MULYAWAN"],
            // ["PersonnelNo" => "8183", "Name" => "SELVIA ROHANIATI"],
            // ["PersonnelNo" => "270", "Name" => "NURUL FITRIA"],
            // ["PersonnelNo" => "8185", "Name" => "SYAFARI RAMADHAN"],
            // ["PersonnelNo" => "8186", "Name" => "VINKA SELLA"],
            // ["PersonnelNo" => "8187", "Name" => "MUHAMMAD FAIZ RIZKI"],
            // ["PersonnelNo" => "8188", "Name" => "PRIMAYONA"],
            // ["PersonnelNo" => "8189", "Name" => "SRI MURYATI"],
            // ["PersonnelNo" => "5043", "Name" => "DINDA RIYANI"],
            // ["PersonnelNo" => "5046", "Name" => "DIAN ANDRIANI"],
            // ["PersonnelNo" => "70027", "Name" => "WAHYU NINGSIH"],
            // ["PersonnelNo" => "5048", "Name" => "AYU WAHYUNINGRUM"],
            // ["PersonnelNo" => "8903", "Name" => "FARADILLA"],
            // ["PersonnelNo" => "8899", "Name" => "INDAH TRISNA"],
            // ["PersonnelNo" => "5049", "Name" => "TARI FEBRIYANTI"],
            // ["PersonnelNo" => "274", "Name" => "INDARTI"],
            // ["PersonnelNo" => "275", "Name" => "AGGUNG ARIF HADI SISWOYO"],
            // ["PersonnelNo" => "5052", "Name" => "NELA WULANDARI"],
            // ["PersonnelNo" => "5053", "Name" => "WIWITAMI MOKOGINTA"],
            // ["PersonnelNo" => "9218", "Name" => "RICO HENDRIK SANJAYA"],
            // ["PersonnelNo" => "9219", "Name" => "MUHAMMAD SYAIFULLAH"],
            // ["PersonnelNo" => "5054", "Name" => "ALNI NURINTAN MULYADI"],
            // ["PersonnelNo" => "5055", "Name" => "YUANITA SUDIARTI"],
            // ["PersonnelNo" => "5056", "Name" => "RIZKA AMELIA WIDIYANTI"],
            // ["PersonnelNo" => "5057", "Name" => "SRI DHEA KARIM"],
            // ["PersonnelNo" => "5058", "Name" => "SABRINA TIKKA NUR PRATAMI"],
            // ["PersonnelNo" => "5059", "Name" => "RISKA NUR CAHYANTI"],
            // ["PersonnelNo" => "5061", "Name" => "NUR SELYANAWATI"],
            // ["PersonnelNo" => "5062", "Name" => "PUTRI INDAH WULAN SARI"],
            // ["PersonnelNo" => "5063", "Name" => "ADHISTA FRICA ANANDA"],
            // ["PersonnelNo" => "70030", "Name" => "NOVI MAYASARI"],
            // ["PersonnelNo" => "9999", "Name" => "KISWARANTI ANGGRAENI"],
            // ["PersonnelNo" => "8906", "Name" => "SIDIK"],
            // ["PersonnelNo" => "8907", "Name" => "VITA SUNARTI"],
            // ["PersonnelNo" => "8912", "Name" => "NIDIA PURWATI TINAMBUNAN"],
            // ["PersonnelNo" => "5064", "Name" => "RAHMANIA AZZAHRA"],
            // ["PersonnelNo" => "5066", "Name" => "DIAS DAMAYANTI"],
            // ["PersonnelNo" => "8086", "Name" => "FAEDHIL ANGRYAWAN"],
            // ["PersonnelNo" => "8095", "Name" => "NURUL CHOLIFAH"],
            // ["PersonnelNo" => "5067", "Name" => "DESSI NURHASANAH"],
            // ["PersonnelNo" => "5069", "Name" => "FITRI WULANDARI"],
            // ["PersonnelNo" => "5070", "Name" => "SITI NURUL AISHAH"],
            // ["PersonnelNo" => "9220", "Name" => "BAGAS BAHARUDIN ANHARI"],
            // ["PersonnelNo" => "5071", "Name" => "FITRA ANITA"],
            // ["PersonnelNo" => "5073", "Name" => "ISTIYANA"],
            // ["PersonnelNo" => "9221", "Name" => "MUCHAMAD ARIFIN APRIYANTO"],
            // ["PersonnelNo" => "70032", "Name" => "LANNY NURJANAH"],
            // ["PersonnelNo" => "70033", "Name" => "ADITIA PRABOWO"],
            // ["PersonnelNo" => "278", "Name" => "DYAH TRI PALUPI"],
            // ["PersonnelNo" => "5074", "Name" => "FATHINA KHALISHAH KANSA"],
            // ["PersonnelNo" => "8088", "Name" => "REMITA IDRIS"],
            // ["PersonnelNo" => "8089", "Name" => "ELLA ANGRAINI"],
            // ["PersonnelNo" => "8092", "Name" => "ADELIA"],
            // ["PersonnelNo" => "5075", "Name" => "NURSUSILAWATI"],
            // ["PersonnelNo" => "5076", "Name" => "SITI KHOTIJAH"],
            // ["PersonnelNo" => "279", "Name" => "NUR ASRI HANDAYANI SEHOL"],
            // ["PersonnelNo" => "8190", "Name" => "ANATYAS SARI KUSUMANINGRUM"],
            // ["PersonnelNo" => "5077", "Name" => "NOVITA DWI LESTARI"],
            // ["PersonnelNo" => "5079", "Name" => "RIVIANA KURNIASARI"],
            // ["PersonnelNo" => "5080", "Name" => "LILI MUKHOLIFAH"],
            // ["PersonnelNo" => "5081", "Name" => "PUTRI DIAH OKTAVIA"],
            // ["PersonnelNo" => "5082", "Name" => "LAELA SETIANI"],
            // ["PersonnelNo" => "5083", "Name" => "HARININGSIH"],
            // ["PersonnelNo" => "5084", "Name" => "SITI RANIA ERNAWATI"],
            // ["PersonnelNo" => "5085", "Name" => "NURIYATI"],
            // ["PersonnelNo" => "8191", "Name" => "JAKA SYARIEF HIDAYAT"],
            // ["PersonnelNo" => "5089", "Name" => "FENSCA TERSEMAN"],
            // ["PersonnelNo" => "8192", "Name" => "MUHAMMAD NASRUDIN"],
            // ["PersonnelNo" => "5088", "Name" => "I WAYAN BUDIARSANA"],
            // ["PersonnelNo" => "5087", "Name" => "DZULFIQAR"],
            // ["PersonnelNo" => "70035", "Name" => "AYU UTARI KUSUMA"],
            // ["PersonnelNo" => "8120", "Name" => "SIMON PETER SAGITA YANUAR"],
            // ["PersonnelNo" => "8029", "Name" => "ANDAR WASITO"],
            // ["PersonnelNo" => "8121", "Name" => "AIDUL SAPUTRA"],
            // ["PersonnelNo" => "8132", "Name" => "SRI UTAMI"],
            // ["PersonnelNo" => "8141", "Name" => "ADITYA MANGGALA YUDHA"],
            // ["PersonnelNo" => "6092", "Name" => "RIA PUTRI ABRIANTI"],
            // ["PersonnelNo" => "8201", "Name" => "HENDRIK BARITA SIMATUPANG"],
            // ["PersonnelNo" => "8205", "Name" => "YUDHIE ANDRIYANTO"],
            // ["PersonnelNo" => "322", "Name" => "SUCI NADHILAH ASMY"],
            // ["PersonnelNo" => "8030", "Name" => "DEWI WAHYU SUSANTI"],
            // ["PersonnelNo" => "5091", "Name" => "KARTIKA TATIK YULIANTI"],
            // ["PersonnelNo" => "5092", "Name" => "CHOIRUNNISA"],
            // ["PersonnelNo" => "281", "Name" => "FATKHUR ROHMAN"],
            // ["PersonnelNo" => "8024", "Name" => "MEGA SARI"],
            // ["PersonnelNo" => "5290", "Name" => "FITRY SABTUTI"],
            // ["PersonnelNo" => "5098", "Name" => "EKO SUGIANTO"],
            // ["PersonnelNo" => "5097", "Name" => "HAIRUNNISA"],
            // ["PersonnelNo" => "5093", "Name" => "SITI MIFTAHUL JANAH"],
            // ["PersonnelNo" => "5094", "Name" => "INNAYAH KURNIAWATI"],
            // ["PersonnelNo" => "8199", "Name" => "YUSUP MURDIANSYAH"],
            // ["PersonnelNo" => "9223", "Name" => "M NUR WAHYUDIN"],
            // ["PersonnelNo" => "5192", "Name" => "TATAH ISMAWATI"],
            // ["PersonnelNo" => "5099", "Name" => "ADINDA PRADIPTA FIERYANTO"],
            // ["PersonnelNo" => "5100", "Name" => "SARAH RAHAYU"],
            // ["PersonnelNo" => "8305", "Name" => "MUHAMMAD AKBAR TONE"],
            // ["PersonnelNo" => "9224", "Name" => "ARIA TOFAN WAHYUDI"],
            // ["PersonnelNo" => "5101", "Name" => "MEYLIYA FAUZIAH"],
            // ["PersonnelNo" => "286", "Name" => "JAINUL TRIONO"],
            // ["PersonnelNo" => "8767", "Name" => "MARTINDA PAULA SOFA"],
            // ["PersonnelNo" => "8766", "Name" => "IWAN SETIADI"],
            // ["PersonnelNo" => "8157", "Name" => "DADI SUPRIATNA"],
            // ["PersonnelNo" => "8156", "Name" => "CARIN PUSPA SARI"],
            // ["PersonnelNo" => "5102", "Name" => "IRMA KENDATI"],
            // ["PersonnelNo" => "5103", "Name" => "TRI EKA PUTRI R"],
            // ["PersonnelNo" => "5104", "Name" => "ZUYINA LINA"],
            // ["PersonnelNo" => "5111", "Name" => "AYU PURNAMA SARI"],
            // ["PersonnelNo" => "9226", "Name" => "MUHAMMAD ZYDAN KURNIANSYAH"],
            // ["PersonnelNo" => "287", "Name" => "KEVIN NATHANAEL ABRAHAM"],
            // ["PersonnelNo" => "8780", "Name" => "IMAM ROPIKOH"],
            // ["PersonnelNo" => "8781", "Name" => "JAKA PRADANA"],
            // ["PersonnelNo" => "8782", "Name" => "SUNARKO"],
            // ["PersonnelNo" => "8783", "Name" => "ANITA KAROLINA YOAN RAYANI"],
            // ["PersonnelNo" => "8784", "Name" => "LA ODE ALFANI"],
            // ["PersonnelNo" => "8785", "Name" => "ALI GINANJAR"],
            // ["PersonnelNo" => "8198", "Name" => "MUHAMMAD TAUFIQ NURRAHMAN"],
            // ["PersonnelNo" => "290", "Name" => "ACHMAD FAISOL"],
            // ["PersonnelNo" => "5105", "Name" => "LIA DESI SETYA PURWANTI"],
            // ["PersonnelNo" => "5107", "Name" => "SITI NURHALIMAH"],
            // ["PersonnelNo" => "293", "Name" => "HAMDAN RISAL RIZKY"],
            // ["PersonnelNo" => "291", "Name" => "M. BAYU MARHAENDRA JAYA"],
            // ["PersonnelNo" => "9228", "Name" => "YUDA WICAKSONO"],
            // ["PersonnelNo" => "9227", "Name" => "AGNESIA ICHA PUTRI ANASTASYA"],
            // ["PersonnelNo" => "294", "Name" => "SELLA MANZILAH ROHMAH"],
            // ["PersonnelNo" => "8206", "Name" => "RUDYANTO"],
            // ["PersonnelNo" => "296", "Name" => "ANGGA YUDIANTO"],
            // ["PersonnelNo" => "298", "Name" => "YUSUP IMAM SUFII"],
            // ["PersonnelNo" => "8197", "Name" => "ADAM SAPUTRA"],
            // ["PersonnelNo" => "299", "Name" => "ADITYA WARDHANY"],
            // ["PersonnelNo" => "5110", "Name" => "WARNIDA"],
            // ["PersonnelNo" => "9230", "Name" => "SITI ASMAUL HUSNAH"],
            // ["PersonnelNo" => "5115", "Name" => "HUTABARAT PUTRI ALICYA"],
            // ["PersonnelNo" => "9231", "Name" => "YOGI RIZKI RAMADHAN"],
            // ["PersonnelNo" => "5118", "Name" => "DARUL HIKMAH"],
            // ["PersonnelNo" => "303", "Name" => "MOH IVAN ALIF ALIFI"],
            // ["PersonnelNo" => "304", "Name" => "FRANCH MAYLANA AL JUFRI"],
            // ["PersonnelNo" => "307", "Name" => "DESI UMI SOLIKAH"],
            // ["PersonnelNo" => "306", "Name" => "FADHILA HERDATIARNI ARTISTIEKAWATI"],
            // ["PersonnelNo" => "309", "Name" => "DWI LUVI YANTI"],
            // ["PersonnelNo" => "5120", "Name" => "MEGA ROSITIANA"],
            // ["PersonnelNo" => "5121", "Name" => "CINDIKIA SAFIARI DEWI"],
            // ["PersonnelNo" => "5122", "Name" => "MUQODDAROH"],
            // ["PersonnelNo" => "5123", "Name" => "ASTRI ANNISHA AMALIA"],
            // ["PersonnelNo" => "310", "Name" => "MOHAMMAD SALAM NASRUDIN"],
            // ["PersonnelNo" => "5125", "Name" => "CHLAUDIA JESSICA MORONG"],
            // ["PersonnelNo" => "8300", "Name" => "IAN SETYAVANI MONROE"],
            // ["PersonnelNo" => "8301", "Name" => "AGIL ENDAR WIRAWAN"],
            // ["PersonnelNo" => "8302", "Name" => "IBNU SANTOSA"],
            // ["PersonnelNo" => "8303", "Name" => "BELLA PUTRI YOLANDA"],
            // ["PersonnelNo" => "312", "Name" => "DESI KUMALA SARI"],
            // ["PersonnelNo" => "314", "Name" => "LIVIA LORENZA BANJAR NAHOR"],
            // ["PersonnelNo" => "313", "Name" => "FATIN NAZIHAH"],
            // ["PersonnelNo" => "9233", "Name" => "EKO ARI ARDIANTO"],
            // ["PersonnelNo" => "9235", "Name" => "FERRY ARDYAN"],
            // ["PersonnelNo" => "5127", "Name" => "HARDIANTI"],
            // ["PersonnelNo" => "5129", "Name" => "ANISA FITAHUL ZANAH"],
            // ["PersonnelNo" => "5130", "Name" => "FERGY LISTIANTY"],
            // ["PersonnelNo" => "316", "Name" => "SARAH MAULUDIYAH ABIDIN"],
            // ["PersonnelNo" => "8915", "Name" => "YOSUA EKAKURNIA PUTRA"],
            // ["PersonnelNo" => "319", "Name" => "RANDY WIBISONO"],
            // ["PersonnelNo" => "6002", "Name" => "MARIA NORA LIONILDA"],
            // ["PersonnelNo" => "320", "Name" => "MAYA TRI IDAYU"],
            // ["PersonnelNo" => "321", "Name" => "ASTI KIRANA"],
            // ["PersonnelNo" => "6003", "Name" => "SUSAN SUMIATI"],
            // ["PersonnelNo" => "6001", "Name" => "SITI LESTARI"],
            // ["PersonnelNo" => "6004", "Name" => "SLAMET K. WINARNI"],
            // ["PersonnelNo" => "6005", "Name" => "SUFI WANTI"],
            // ["PersonnelNo" => "6006", "Name" => "SURYATI"],
            // ["PersonnelNo" => "5132", "Name" => "SITI FATIMAH"],
            // ["PersonnelNo" => "5133", "Name" => "SADARIA"],
            // ["PersonnelNo" => "8918", "Name" => "WINDA AAN ABETNICO"],
            // ["PersonnelNo" => "9236", "Name" => "FIRZA MARDANI"],
            // ["PersonnelNo" => "8920", "Name" => "INDRA PERMANA SAKTI"],
            // ["PersonnelNo" => "339", "Name" => "ANWAR HUDA"],
            // ["PersonnelNo" => "8922", "Name" => "BOBBY ARFIAN"],
            // ["PersonnelNo" => "6012", "Name" => "JENYVER DINI AL KHASANAH"],
            // ["PersonnelNo" => "6017", "Name" => "TSAMARA HANINA OCTAVIERI"],
            // ["PersonnelNo" => "8923", "Name" => "SEPTA TRIWIDIANTO"],
            // ["PersonnelNo" => "5134", "Name" => "JARIAH"],
            // ["PersonnelNo" => "5135", "Name" => "DESI FITRIYANI"],
            // ["PersonnelNo" => "5136", "Name" => "LESTARI ANUGRAH PUTRI"],
            // ["PersonnelNo" => "5138", "Name" => "LIDWINDA"],
            // ["PersonnelNo" => "5139", "Name" => "NOERLIANA MALIK"],
            // ["PersonnelNo" => "5141", "Name" => "TANIA SUKMA SARI"],
            // ["PersonnelNo" => "5140", "Name" => "MAHARANI OKTAVIANA SAPITRI"],
            // ["PersonnelNo" => "327", "Name" => "PUPU ANDARINI, S. SOS"],
            // ["PersonnelNo" => "8925", "Name" => "LAELA SARI"],
            // ["PersonnelNo" => "8926", "Name" => "DAVID NICODEMUS KAIMAREHE"],
            // ["PersonnelNo" => "8927", "Name" => "RIZQI LILIANA SURYA"],
            // ["PersonnelNo" => "6018", "Name" => "WIDYA ANANDA PUTRI"],
            // ["PersonnelNo" => "6019", "Name" => "YUNI RAFIKA SARI"],
            // ["PersonnelNo" => "6020", "Name" => "HALIMATON SAKDIAH"],
            // ["PersonnelNo" => "6025", "Name" => "PUTRI LAJUNA"],
            // ["PersonnelNo" => "8928", "Name" => "M. IRFAN EFENDI"],
            // ["PersonnelNo" => "8929", "Name" => "AHMAD FITRIADI"],
            // ["PersonnelNo" => "5142", "Name" => "KHAULA PUTRI MIRANDA"],
            // ["PersonnelNo" => "5145", "Name" => "SULASIH"],
            // ["PersonnelNo" => "8930", "Name" => "RESTI FEBRIANI WULANDARI"],
            // ["PersonnelNo" => "8931", "Name" => "MUHAMMAD AKBAR"],
            // ["PersonnelNo" => "330", "Name" => "MUHAMMAD NUR QOMARI"],
            // ["PersonnelNo" => "6028", "Name" => "AYU DAMAYANTI"],
            // ["PersonnelNo" => "6131", "Name" => "SRI ANITA BR KARO"],
            // ["PersonnelNo" => "6030", "Name" => "SARI SARTIKA"],
            // ["PersonnelNo" => "6031", "Name" => "NOVITA SARI DEWI"],
            // ["PersonnelNo" => "6032", "Name" => "AZZURA HASIBUAN"],
            // ["PersonnelNo" => "6036", "Name" => "YEZA ANANDA PUTRI"],
            // ["PersonnelNo" => "6034", "Name" => "ELISABET RISKA VALENTINE"],
            // ["PersonnelNo" => "6037", "Name" => "NINDY ANGGRAENI S.FARM APL"],
            // ["PersonnelNo" => "6038", "Name" => "ETAPURNAMA SARI SAGALA"],
            // ["PersonnelNo" => "5146", "Name" => "NOPIYANI"],
            // ["PersonnelNo" => "5147", "Name" => "NIA KURNIASIH"],
            // ["PersonnelNo" => "5148", "Name" => "SELFI HALDIYANTI"],
            // ["PersonnelNo" => "5149", "Name" => "RIRIN"],
            // ["PersonnelNo" => "5150", "Name" => "ADELGONDA DARNI"],
            // ["PersonnelNo" => "5153", "Name" => "DEASY LANGELO"],
            // ["PersonnelNo" => "5154", "Name" => "NINING SUWARNI"],
            // ["PersonnelNo" => "5155", "Name" => "NURUL LATHIFAH HANUM"],
            // ["PersonnelNo" => "6039", "Name" => "ISTIANA PURNAWANTI"],
            // ["PersonnelNo" => "6040", "Name" => "NURLIYANTI PASARIBU"],
            // ["PersonnelNo" => "6041", "Name" => "SHINTA AULIA"],
            // ["PersonnelNo" => "6045", "Name" => "SITI MUAMANAH"],
            // ["PersonnelNo" => "6044", "Name" => "SALMIA PUTRI"],
            // ["PersonnelNo" => "6046", "Name" => "FITRIANA"],
            // ["PersonnelNo" => "6047", "Name" => "DIANA BR SEMBIRING"],
            // ["PersonnelNo" => "6048", "Name" => "HENY MAHENDRAYANI"],
            // ["PersonnelNo" => "6050", "Name" => "JUANTI MANDASARIA MD KEB"],
            // ["PersonnelNo" => "6049", "Name" => "MAIZARAH"],
            // ["PersonnelNo" => "6057", "Name" => "PANI AGUSTIANI"],
            // ["PersonnelNo" => "6056", "Name" => "SRI REJEKI"],
            // ["PersonnelNo" => "6054", "Name" => "MUTIA RAIZA"],
            // ["PersonnelNo" => "6053", "Name" => "AINUN NAILI"],
            // ["PersonnelNo" => "331", "Name" => "AN ABDI SALAM"],
            // ["PersonnelNo" => "6058", "Name" => "BUDI LUCIA ANIEFIANTARI W. NY"],
            // ["PersonnelNo" => "6059", "Name" => "ANNISA PUTRI"],
            // ["PersonnelNo" => "8934", "Name" => "SANG MADE ANGGA RADITHA"],
            // ["PersonnelNo" => "5157", "Name" => "YUNI RAHMA UNSIA"],
            // ["PersonnelNo" => "111335", "Name" => "DIDIK EKO PRASETYO"],
            // ["PersonnelNo" => "8935", "Name" => "RODI ATMAJI"],
            // ["PersonnelNo" => "8936", "Name" => "RIZKY ANANDA"],
            // ["PersonnelNo" => "336", "Name" => "ANTO SAPUTRA"],
            // ["PersonnelNo" => "5158", "Name" => "SEFIANA ERIKA SARI"],
            // ["PersonnelNo" => "6062", "Name" => "WIDIA PEBRIANTI GINTING"],
            // ["PersonnelNo" => "8938", "Name" => "ADRI REZKI"],
            // ["PersonnelNo" => "9239", "Name" => "JANUAR RADILUS WERKUSEVIC"],
            // ["PersonnelNo" => "8939", "Name" => "MUHAMMAD PADLI"],
            // ["PersonnelNo" => "8940", "Name" => "NI LUH PUTU ASTITI FEBRIANI"],
            // ["PersonnelNo" => "338", "Name" => "DINDA ALYA ARYANI"],
            // ["PersonnelNo" => "8941", "Name" => "SELFANA HENDRIKS"],
            // ["PersonnelNo" => "8942", "Name" => "NURUL AL AMIN"],
            // ["PersonnelNo" => "5160", "Name" => "RIRIN SELFIANA"],
            // ["PersonnelNo" => "5161", "Name" => "INDRIA KUSUMA ANGGRAINI"],
            // ["PersonnelNo" => "6061", "Name" => "ANNISA KHAIRANI H"],
            // ["PersonnelNo" => "6063", "Name" => "MAQFIRAH"],
            // ["PersonnelNo" => "6064", "Name" => "MAISARAH ANANDA"],
            // ["PersonnelNo" => "5276", "Name" => "YULI YANTI"],
            // ["PersonnelNo" => "6067", "Name" => "DEVIANTI LESTARI"],
            // ["PersonnelNo" => "8943", "Name" => "EKO SUKATNO"],
            // ["PersonnelNo" => "8944", "Name" => "PUPUT IRMAWATI"],
            // ["PersonnelNo" => "340", "Name" => "MULIA SARI"],
            // ["PersonnelNo" => "8945", "Name" => "WA ODE NUR HASMI"],
            // ["PersonnelNo" => "5163", "Name" => "RETNO HANDAYANI"],
            // ["PersonnelNo" => "5165", "Name" => "AYU SRIWENING"],
            // ["PersonnelNo" => "8946", "Name" => "BAMBANG BUDIARSO"],
            // ["PersonnelNo" => "6068", "Name" => "NOVA ELYZA NASUTION"],
            // ["PersonnelNo" => "6069", "Name" => "ADE RIYANI"],
            // ["PersonnelNo" => "6070", "Name" => "PUTRI ADELIA AZAHRA"],
            // ["PersonnelNo" => "6071", "Name" => "AULIA DESRI YUNITA"],
            // ["PersonnelNo" => "6073", "Name" => "FEYBI CAROLINA"],
            // ["PersonnelNo" => "6074", "Name" => "DEVINA RIFKA HUSAHI"],
            // ["PersonnelNo" => "6075", "Name" => "SAHARIAH"],
            // ["PersonnelNo" => "6077", "Name" => "IKA PURWITANINGSIH"],
            // ["PersonnelNo" => "348", "Name" => "RENALDY FIRMANA"],
            // ["PersonnelNo" => "349", "Name" => "DEFI AINI NADHIFAH"],
            // ["PersonnelNo" => "8949", "Name" => "SITI RAHMAWATI"],
            // ["PersonnelNo" => "350", "Name" => "NANANG SETIAWAN"],
            // ["PersonnelNo" => "8950", "Name" => "ANDI HASMIATY"],
            // ["PersonnelNo" => "5170", "Name" => "MUTIARA ISMAIL"],
            // ["PersonnelNo" => "5172", "Name" => "RAIDA PUTRI LAIA"],
            // ["PersonnelNo" => "5174", "Name" => "ALKA"],
            // ["PersonnelNo" => "5175", "Name" => "TIKA KARTIKA"],
            // ["PersonnelNo" => "5177", "Name" => "LINDA PUSPITA SARI"],
            // ["PersonnelNo" => "70038", "Name" => "SERLIYANI"],
            // ["PersonnelNo" => "8951", "Name" => "NUR HAYATI JAMIL"],
            // ["PersonnelNo" => "6081", "Name" => "EKA PALASARI"],
            // ["PersonnelNo" => "6076", "Name" => "IRAYANTI"],
            // ["PersonnelNo" => "6078", "Name" => "DHANA OCTORA SYAHPUTRA"],
            // ["PersonnelNo" => "352", "Name" => "THIVAL ABROR ROMADHAN"],
            // ["PersonnelNo" => "5178", "Name" => "ULFA SABILULLAH"],
            // ["PersonnelNo" => "353", "Name" => "TRI CAHYO NUGROHO"],
            // ["PersonnelNo" => "8953", "Name" => "A.M. FARIDH WAHYUDIN TAMSIL"],
            // ["PersonnelNo" => "9241", "Name" => "ELLYA NOOR AZIZAH"],
            // ["PersonnelNo" => "5179", "Name" => "WINDY PRATIWIE"],
            // ["PersonnelNo" => "5180", "Name" => "RIANA WAHYU LORENSA"],
            // ["PersonnelNo" => "5181", "Name" => "MILLATUL MUTAMIMMAH"],
            // ["PersonnelNo" => "5187", "Name" => "DWIYANA PERTIWI"],
            // ["PersonnelNo" => "5188", "Name" => "PUSPITA AYUNINGTYAS"],
            // ["PersonnelNo" => "6082", "Name" => "MAYSARAH LUBIS"],
            // ["PersonnelNo" => "6083", "Name" => "ASTRIA LIANA INTAN SARI"],
            // ["PersonnelNo" => "6084", "Name" => "LULU NIA SUGIA"],
            // ["PersonnelNo" => "6085", "Name" => "ZELIKA ABEL PUTRISIA"],
            // ["PersonnelNo" => "6139", "Name" => "WANDA LUTFIANI"],
            // ["PersonnelNo" => "6087", "Name" => "SRI LESTARI"],
            // ["PersonnelNo" => "6088", "Name" => "SWASTIKA DESTRANTI"],
            // ["PersonnelNo" => "6089", "Name" => "KARINA KADESTA"],
            // ["PersonnelNo" => "8955", "Name" => "ZAHARA"],
            // ["PersonnelNo" => "8956", "Name" => "AGUNG ZULKIFLI"],
            // ["PersonnelNo" => "8957", "Name" => "AZWIRA YATI"],
            // ["PersonnelNo" => "8958", "Name" => "M. YUNUS"],
            // ["PersonnelNo" => "355", "Name" => "BAMBANG ARDIANSAH"],
            // ["PersonnelNo" => "6091", "Name" => "ELA NUR AENI"],
            // ["PersonnelNo" => "8959", "Name" => "PURNIYANTI"],
            // ["PersonnelNo" => "70039", "Name" => "DEWI PURNAMASARI"],
            // ["PersonnelNo" => "5196", "Name" => "RAHELIA PETRUS"],
            // ["PersonnelNo" => "5195", "Name" => "NIA NUR FINDA"],
            // ["PersonnelNo" => "5193", "Name" => "DIANA KUSUMA DEWI"],
            // ["PersonnelNo" => "5194", "Name" => "DIAN NURHAYATI"],
            // ["PersonnelNo" => "6093", "Name" => "ARDANA SYAHPUTRI"],
            // ["PersonnelNo" => "6094", "Name" => "FINA WULANDARI"],
            // ["PersonnelNo" => "6095", "Name" => "MUZAIYANA"],
            // ["PersonnelNo" => "6096", "Name" => "EVI SARWANI"],
            // ["PersonnelNo" => "6098", "Name" => "TRI ASTUTI NUR HIDAYAH"],
            // ["PersonnelNo" => "60698", "Name" => "TANTI RAHMATILAH"],
            // ["PersonnelNo" => "8963", "Name" => "RONI BUDIAWAN"],
            // ["PersonnelNo" => "8965", "Name" => "SLAMET RIYADI"],
            // ["PersonnelNo" => "8966", "Name" => "MULYATI BUNGSUWATI"],
            // ["PersonnelNo" => "357", "Name" => "FITRIANA BAROROH"],
            // ["PersonnelNo" => "5204", "Name" => "TRI INDAH KUSUMA DEWI"],
            // ["PersonnelNo" => "5205", "Name" => "ASRI BULAN"],
            // ["PersonnelNo" => "8967", "Name" => "VERAWATI"],
            // ["PersonnelNo" => "8968", "Name" => "ARIA PUSPITA"],
            // ["PersonnelNo" => "5210", "Name" => "IIS SAFITRI"],
            // ["PersonnelNo" => "6100", "Name" => "NAZLA AULIA"],
            // ["PersonnelNo" => "6101", "Name" => "FENNY KHAIRIANTI"],
            // ["PersonnelNo" => "6102", "Name" => "MUTIARA SYAHNANDA"],
            // ["PersonnelNo" => "6103", "Name" => "FIRERA DHANILIA"],
            // ["PersonnelNo" => "6107", "Name" => "TISCA MIAVIENTY"],
            // ["PersonnelNo" => "6108", "Name" => "YUNI MARIDA"],
            // ["PersonnelNo" => "6109", "Name" => "SRI RAHAYU"],
            // ["PersonnelNo" => "8970", "Name" => "I NYOMAN ARDATRINATHA, S.PD"],
            // ["PersonnelNo" => "8971", "Name" => "BAYU PRASETYO"],
            // ["PersonnelNo" => "8972", "Name" => "DENIES HERMAWAN"],
            // ["PersonnelNo" => "8973", "Name" => "AKHMAD BAIHAQI"],
            // ["PersonnelNo" => "8975", "Name" => "ASEP ABDUL MALIK"],
            // ["PersonnelNo" => "8976", "Name" => "NIKA ESIH ULANDINA"],
            // ["PersonnelNo" => "8977", "Name" => "GILANGTRIS RAMADHANI"],
            // ["PersonnelNo" => "363", "Name" => "ILHAM YUSEFAFEBI ANTONO"],
            // ["PersonnelNo" => "8979", "Name" => "FIRMAN SUHESTIYONO"],
            // ["PersonnelNo" => "8980", "Name" => "RACHMA YUNITA"],
            // ["PersonnelNo" => "5214", "Name" => "SARAH SARASWATI"],
            // ["PersonnelNo" => "5220", "Name" => "MELISA MELYAWATI SODIKIN"],
            // ["PersonnelNo" => "6144", "Name" => "EKA FITRIYANA"],
            // ["PersonnelNo" => "5222", "Name" => "ANYAPRAMESTI PUTRI SAGITA"],
            // ["PersonnelNo" => "8983", "Name" => "DESYNTA DIANASARI"],
            // ["PersonnelNo" => "6121", "Name" => "IMELDA TRI AGUSTINA"],
            // ["PersonnelNo" => "6122", "Name" => "SUCI NURAQIDAH"],
            // ["PersonnelNo" => "6124", "Name" => "SULASTRI TAMANAMPO"],
            // ["PersonnelNo" => "6125", "Name" => "ADE IRAWATI BR SEMBIRING"],
            // ["PersonnelNo" => "6126", "Name" => "PUTRI ADINDA"],
            // ["PersonnelNo" => "6127", "Name" => "SHERLY MONIKA HARIS"],
            // ["PersonnelNo" => "6128", "Name" => "WARDAH"],
            // ["PersonnelNo" => "6116", "Name" => "SRI ANITA BR KARO"],
            // ["PersonnelNo" => "6132", "Name" => "RULY DINDA MAULANI"],
            // ["PersonnelNo" => "8981", "Name" => "CALVIN JHON FRANKLIN PAPILAYA"],
            // ["PersonnelNo" => "8984", "Name" => "ACHMAD SHOLEH NUR HIDAYAT"],
            // ["PersonnelNo" => "8986", "Name" => "HERLAMBANG DEDI KURNIA SHANDI"],
            // ["PersonnelNo" => "8987", "Name" => "GINTAN AL AFGANI"],
            // ["PersonnelNo" => "8988", "Name" => "FER JULIA NINGSIH"],
            // ["PersonnelNo" => "9243", "Name" => "ARFIANI MEGA FITRIA"],
            // ["PersonnelNo" => "5225", "Name" => "ELY KRISDAYANTI"],
            // ["PersonnelNo" => "5226", "Name" => "PUTRI ANNA DEWI ELOK LESTARI"],
            // ["PersonnelNo" => "5227", "Name" => "DEWI NURDIANA"],
            // ["PersonnelNo" => "5229", "Name" => "NOVIA AULIA NUR"],
            // ["PersonnelNo" => "9249", "Name" => "I KADEK HARY WIADNYANA"],
            // ["PersonnelNo" => "6140", "Name" => "BUDI LAKSMITA"],
            // ["PersonnelNo" => "6141", "Name" => "SITI NURHASANAH BR GINTING"],
            // ["PersonnelNo" => "6142", "Name" => "LIA MUHARA BR NAINGGOLAN"],
            // ["PersonnelNo" => "6143", "Name" => "DEVI ANGRAINI NASUTION"],
            // ["PersonnelNo" => "6137", "Name" => "NENI SUPRIATIN"],
            // ["PersonnelNo" => "8989", "Name" => "ARIES WAHYU INDRAWAN"],
            // ["PersonnelNo" => "8991", "Name" => "NOVITA SARI"],
            // ["PersonnelNo" => "8992", "Name" => "SURIYANINGSIH"],
            // ["PersonnelNo" => "8993", "Name" => "ANDI MAHYUDIN"],
            // ["PersonnelNo" => "5233", "Name" => "NIRWANA"],
            // ["PersonnelNo" => "374", "Name" => "DIA SETYO RINI"],
            // ["PersonnelNo" => "70041", "Name" => "MUHAMMAD MUCHTAR JAMAL"],
            // ["PersonnelNo" => "5239", "Name" => "DEBBY SITI ROSITA SAPUTRI"],
            // ["PersonnelNo" => "376", "Name" => "APRILIA TAQIYYATUL MUTTARISAH"],
            // ["PersonnelNo" => "8994", "Name" => "WIDYA FEBRIYANI"],
            // ["PersonnelNo" => "8995", "Name" => "IMAM SYAHRONI"],
            // ["PersonnelNo" => "6146", "Name" => "DEWI HERAWATI"],
            // ["PersonnelNo" => "6148", "Name" => "EVI MULIANI"],
            // ["PersonnelNo" => "382", "Name" => "GABARIEL MAURIKE HELSON"],
            // ["PersonnelNo" => "5244", "Name" => "FARWA KHULAIPAH MUHAJAROH"],
            // ["PersonnelNo" => "5246", "Name" => "SITI NADIA PRASISKA"],
            // ["PersonnelNo" => "5247", "Name" => "JESSICA MERCHI MAHARANI"],
            // ["PersonnelNo" => "6152", "Name" => "SRI DWIYANTI"],
            // ["PersonnelNo" => "6153", "Name" => "CINDY NUR HENDYASARI"],
            // ["PersonnelNo" => "6154", "Name" => "DEWI OKTARIA"],
            // ["PersonnelNo" => "6157", "Name" => "KHADHRAH  ARMILA"],
            // ["PersonnelNo" => "6159", "Name" => "PUTRI REZA STEVANI"],
            // ["PersonnelNo" => "386", "Name" => "MOCHAMMAD SHIDIQ ROCHMATULLOH"],
            // ["PersonnelNo" => "80000", "Name" => "RISKY FEBRIANA PUTRI"],
            // ["PersonnelNo" => "80002", "Name" => "EKA NUR REZKI"],
            // ["PersonnelNo" => "5250", "Name" => "NURY ROCHMA SOFYANTI"],
            // ["PersonnelNo" => "6160", "Name" => "BONTAR RIASARI DAULAY"],
            // ["PersonnelNo" => "80006", "Name" => "DITA NUR SAKINA"],
            // ["PersonnelNo" => "1010", "Name" => "ELAINE CATHERINA MULYONO"],
            // ["PersonnelNo" => "6169", "Name" => "BARLIANA"],
            // ["PersonnelNo" => "9256", "Name" => "ANGELIN GIOVANI PUSPITASARI"],
            // ["PersonnelNo" => "9257", "Name" => "INDRYAS RAMADANI"],
            // ["PersonnelNo" => "398", "Name" => "BEBEN PRANATA RISMADIARTA"],
            // ["PersonnelNo" => "80021", "Name" => "MARVIN ADRIAN VERSTEEGH"],
            // ["PersonnelNo" => "399", "Name" => "RAIHAN ADIANSYAH"],
            // ["PersonnelNo" => "400", "Name" => "ANDRI EKA WAHYUDIANTO"],
            // ["PersonnelNo" => "9258", "Name" => "MAYA ANGGI DAMAYANTI"],
            // ["PersonnelNo" => "80022", "Name" => "YENI YANWANTARI"],
            // ["PersonnelNo" => "5257", "Name" => "TASYA SAFA CAMILA"],
            // ["PersonnelNo" => "5258", "Name" => "DIANA DWI WULANSARI"],
            // ["PersonnelNo" => "5259", "Name" => "FEBBY WINARTY"],
            // ["PersonnelNo" => "5260", "Name" => "LIDYA CITRA PURNAMA"],
            // ["PersonnelNo" => "5261", "Name" => "ANIDA"],
            // ["PersonnelNo" => "6181", "Name" => "HASNIAR PUSPITA SARI"],
            // ["PersonnelNo" => "6182", "Name" => "INAR SUNARTI"],
            // ["PersonnelNo" => "6183", "Name" => "ALIYAH ABDI N"],
            // ["PersonnelNo" => "404", "Name" => "ISNA NURROSYIDAH"],
            // ["PersonnelNo" => "80023", "Name" => "VECKY KUSOY"],
            // ["PersonnelNo" => "405", "Name" => "MIFTAHUL ULUM"],
            // ["PersonnelNo" => "406", "Name" => "MUHAMMAD NIZARUDIN"],
            // ["PersonnelNo" => "80024", "Name" => "HERU TRIYONO"],
            // ["PersonnelNo" => "407", "Name" => "DIMAS ADI PRATAMA"],
            // ["PersonnelNo" => "80025", "Name" => "NI PUTU SRI WINANTI"],
            // ["PersonnelNo" => "80026", "Name" => "YUYU YUNINGSIH, A. MPD"],
            // ["PersonnelNo" => "408", "Name" => "LISA NUR SABILA"],
            // ["PersonnelNo" => "409", "Name" => "AMARYLIS FAUSTINE TALITHA PAHLEVI"],
            // ["PersonnelNo" => "80027", "Name" => "AYU WANDIRA YUSUF"],
            // ["PersonnelNo" => "5262", "Name" => "DHIA KHARIDA ZALFA"],
            // ["PersonnelNo" => "5263", "Name" => "WINDAH NUR AMBAR NILA"],
            // ["PersonnelNo" => "5264", "Name" => "EMILIA"],
            // ["PersonnelNo" => "410", "Name" => "IRMA SYAHDANIAH"],
            // ["PersonnelNo" => "5265", "Name" => "ENI ULFI ROHMATUL LAILI"],
            // ["PersonnelNo" => "5266", "Name" => "RISMA"],
            // ["PersonnelNo" => "5267", "Name" => "RENY RETNOWATI"],
            // ["PersonnelNo" => "5268", "Name" => "YAYANG ANA SAHFITRI"],
            // ["PersonnelNo" => "5269", "Name" => "SANTI NURGIANTI"],
            // ["PersonnelNo" => "5270", "Name" => "NIKEN FRANSIALITA"],
            // ["PersonnelNo" => "411", "Name" => "BAGOS SATRIA"],
            // ["PersonnelNo" => "9259", "Name" => "HANA RAHMADIARNI"],
            // ["PersonnelNo" => "6190", "Name" => "INDAH PUTRI MUSTIKA"],
            // ["PersonnelNo" => "6191", "Name" => "MULIANA"],
            // ["PersonnelNo" => "412", "Name" => "JAKA PURNAMA"],
            // ["PersonnelNo" => "80028", "Name" => "ALI HASAN"],
            // ["PersonnelNo" => "80029", "Name" => "SANTI"],
            // ["PersonnelNo" => "80030", "Name" => "MUHAMMAD THAMRIN"],
            // ["PersonnelNo" => "413", "Name" => "BELLA ANNISA NABILA"],
            // ["PersonnelNo" => "80031", "Name" => "RETNO EL PRADHIPTA"],
            // ["PersonnelNo" => "414", "Name" => "ANTOK KURNIAWAN"],
            // ["PersonnelNo" => "80032", "Name" => "REZKY DWI NUR MUTMAINAH"],
            // ["PersonnelNo" => "415", "Name" => "ARYA ZANITRA PUTRA HERMAWAN"],
            // ["PersonnelNo" => "5271", "Name" => "ANNISA SOFYANA"],
            // ["PersonnelNo" => "5272", "Name" => "ELA RULITA"],
            // ["PersonnelNo" => "5273", "Name" => "TIARA NABILLAZEN"],
            // ["PersonnelNo" => "5274", "Name" => "RAHMAH MAULIDAH ARNANTI"],
            // ["PersonnelNo" => "5275", "Name" => "MIFTAKHUL JANAH"],
            // ["PersonnelNo" => "6192", "Name" => "FITRIANI MANSYUR"],
            // ["PersonnelNo" => "6193", "Name" => "HARIATI"],
            // ["PersonnelNo" => "6194", "Name" => "SUCI SALSABILA MUSTARI"],
            // ["PersonnelNo" => "6195", "Name" => "ANITA CHOLISTIYAWATI"],
            // ["PersonnelNo" => "416", "Name" => "DANIYA AYU KAMILA"],
            // ["PersonnelNo" => "417", "Name" => "FITRI SYAWALIYAH YUSNITA"],
            // ["PersonnelNo" => "80033", "Name" => "BISRI EFENDI"],
            // ["PersonnelNo" => "80035", "Name" => "QOMARUDDIN"],
            // ["PersonnelNo" => "80034", "Name" => "SRI SUPARNI"],
            // ["PersonnelNo" => "80036", "Name" => "AINUN JARIAH"],
            // ["PersonnelNo" => "419", "Name" => "YULIANA FATMALA"],
            // ["PersonnelNo" => "420", "Name" => "ADEZIA NAJLA FATIKHA"],
            // ["PersonnelNo" => "80037", "Name" => "ENI SAFITRI"],
            // ["PersonnelNo" => "6196", "Name" => "RAUZATULMUNA"],
            // ["PersonnelNo" => "422", "Name" => "ATHAYA ALMIRA NUR AZZAHRA"],
            // ["PersonnelNo" => "5277", "Name" => "ERLINA"],
            // ["PersonnelNo" => "5278", "Name" => "SRI WAHYUNI"],
            // ["PersonnelNo" => "423", "Name" => "DELLA WIWEKO ADI"],
            // ["PersonnelNo" => "424", "Name" => "SHEREN THALITA KHITA"],
            // ["PersonnelNo" => "70043", "Name" => "DIAH ANGGRAENI"],
            // ["PersonnelNo" => "5280", "Name" => "SYLVIA REGGY MINETHA"],
            // ["PersonnelNo" => "5279", "Name" => "HELDA"],
            // ["PersonnelNo" => "5281", "Name" => "PUTRI YULIANA LUTMAWATI"],
            // ["PersonnelNo" => "6197", "Name" => "AMBAR PRASETYANINGRUM"],
            // ["PersonnelNo" => "80038", "Name" => "NAFISAH RIDHOTI"],
            // ["PersonnelNo" => "425", "Name" => "ANGGI SAFIRA SARA RIZKIYAH"],
            // ["PersonnelNo" => "80039", "Name" => "HAMID FEBRIYAN GHOZALI"],
            // ["PersonnelNo" => "80040", "Name" => "SOIBATUS SALAMIYA"],
            // ["PersonnelNo" => "5282", "Name" => "MARSHANDA DWI PUTRI"],
            // ["PersonnelNo" => "5283", "Name" => "PUTRI ADELIA"],
            // ["PersonnelNo" => "5284", "Name" => "ELLYSDA SAGITA DOSIOFA SAMBIGA"],
            // ["PersonnelNo" => "5285", "Name" => "MANJA DARA JELITA CINTYAWATI"],
            // ["PersonnelNo" => "80041", "Name" => "DENI KURNIAWAN"],
            // ["PersonnelNo" => "5286", "Name" => "ARBETI CATUR SEPRIYANA"],
            // ["PersonnelNo" => "5287", "Name" => "ERNA TRISTIANA"],
            // ["PersonnelNo" => "6198", "Name" => "RISKA RAMADANI"],
            // ["PersonnelNo" => "6199", "Name" => "SRI ANITA BR KARO"],
            // ["PersonnelNo" => "80043", "Name" => "APRILLIA FEBRIANTI"],
            // ["PersonnelNo" => "426", "Name" => "LISA AULIA ZAHRA"],
            // ["PersonnelNo" => "80042", "Name" => "MUHAMMAD BASOFI"],
            // ["PersonnelNo" => "427", "Name" => "DEDI SETIAWAN"],
            // ["PersonnelNo" => "6200", "Name" => "ENDANG DARLIAH"],
            // ["PersonnelNo" => "6201", "Name" => "JULI FITRIANA"],
            // ["PersonnelNo" => "6202", "Name" => "SITI AISYAH"],
            // ["PersonnelNo" => "6203", "Name" => "AFRINA MEY PUTRI BALQIS"],
            // ["PersonnelNo" => "6204", "Name" => "SHAFA PUTRI INSANI"],
            // ["PersonnelNo" => "6205", "Name" => "NIKKY ARYANINGSIH LOGO"],
            // ["PersonnelNo" => "6206", "Name" => "RIRIS APRIL RIA"],
            // ["PersonnelNo" => "80044", "Name" => "FIRMA KUASAN"],
            // ["PersonnelNo" => "428", "Name" => "ZAHRO LAILI"],
            // ["PersonnelNo" => "6207", "Name" => "HASMAWATI M"],
            // ["PersonnelNo" => "6208", "Name" => "LUY ALMA SAKHA RANA TSABITA"],
            // ["PersonnelNo" => "6209", "Name" => "NORIYANA INDRI SUNDARI"],
            // ["PersonnelNo" => "70044", "Name" => "KHATIMATUSSA'ADAH"],
            // ["PersonnelNo" => "6211", "Name" => "AULIA CHINTYA BELLA"],
            // ["PersonnelNo" => "6212", "Name" => "SALMA IZZATUNNAFSI"],
            // ["PersonnelNo" => "6213", "Name" => "ISMI ANDRIANI"],
            // ["PersonnelNo" => "6214", "Name" => "NURUL ADINDA"],
            // ["PersonnelNo" => "429", "Name" => "LIZA ALIF SISWANTI"],
            // ["PersonnelNo" => "80045", "Name" => "MUHAMMAD RAPI"],
            ["PersonnelNo" => "430", "Name" => "ANDRIE PURWANTO"],
        ];

        foreach ($data as $user) {
            DB::table('tbl_employees')->insert([
                'PersonnelNo' => $user['PersonnelNo'],
                'Name' => $user['Name'],
            ]);
        }
    }
}
