<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // ["PersonnelNo" => "12345", "Name" => "ADMIN"],
            // ["PersonnelNo" => "123456", "Name" => "KARYAWAN"],
            // ["PersonnelNo" => "19", "Name" => "ENI PUJI RAHAYU"],
            // ["PersonnelNo" => "14", "Name" => "DESSY DAMAYANTI"],
            // ["PersonnelNo" => "27", "Name" => "IMA YUNANI"],
            // ["PersonnelNo" => "46", "Name" => "NUR INDAYAH"],
            // ["PersonnelNo" => "11", "Name" => "BUDI SANTOSO"],
            // ["PersonnelNo" => "15", "Name" => "DIDIK ERWANTO"],
            // ["PersonnelNo" => "50", "Name" => "PURWANTO"],
            // ["PersonnelNo" => "65", "Name" => "SUGIONO"],
            // ["PersonnelNo" => "62", "Name" => "SUDARMONO"],
            // ["PersonnelNo" => "21", "Name" => "ERVI RIANINGSIH"],
            // ["PersonnelNo" => "35", "Name" => "LUSI LINDA ERLINAWATI"],
            // ["PersonnelNo" => "42", "Name" => "MOCH ARIF RASYIDI"],
            // ["PersonnelNo" => "31", "Name" => "JAINUDIN"],
            // ["PersonnelNo" => "47", "Name" => "NUR KHOLIS SISWANTO"],
            // ["PersonnelNo" => "64", "Name" => "SUGENG AGUNG WIDODO ARYANTO"],
            // ["PersonnelNo" => "56", "Name" => "ROCHMAN"],
            // ["PersonnelNo" => "70001", "Name" => "RAIS SUMARNO"],
            // ["PersonnelNo" => "73", "Name" => "WINDY EKA SUSANTI"],
            // ["PersonnelNo" => "4", "Name" => "AGUS SETYOADI"],
            // ["PersonnelNo" => "66", "Name" => "SURYANTO"],
            // ["PersonnelNo" => "28", "Name" => "IMROATUS SHOLIKHAH"],
            // ["PersonnelNo" => "75", "Name" => "YAYAN GUNAWILAGA"],
            // ["PersonnelNo" => "5", "Name" => "AGUS SUSANTO"],
            // ["PersonnelNo" => "10", "Name" => "ARIYANTO"],
            // ["PersonnelNo" => "18", "Name" => "ELYFAH SETYOWATI"],
            // ["PersonnelNo" => "25", "Name" => "HASAN AMIRUDIN"],
            // ["PersonnelNo" => "32", "Name" => "KARNADI SUDIRJA"],
            // ["PersonnelNo" => "33", "Name" => "KEMALAWATI"],
            // ["PersonnelNo" => "38", "Name" => "MARIA JOVITA H.S"],
            // ["PersonnelNo" => "40", "Name" => "MATIUS WAHYU BUDI SANTOSO"],
            // ["PersonnelNo" => "44", "Name" => "NOOR AINI"],
            // ["PersonnelNo" => "57", "Name" => "ROHMAD KUNCORO D"],
            // ["PersonnelNo" => "68", "Name" => "TITIK ERIANI KUSMIATI"],
            // ["PersonnelNo" => "3", "Name" => "ABDULLOH MAS'UD, SE"],
            // ["PersonnelNo" => "394", "Name" => "ELAINE CATHERINA MULYONO, S. FARM., APT."],
            // ["PersonnelNo" => "54", "Name" => "RINI KUSUMA WARDANI"],
            // ["PersonnelNo" => "37", "Name" => "MUHAMMAD MISBAHUL ILMI"],
            // ["PersonnelNo" => "34", "Name" => "LILIS KARIAWATI"],
            // ["PersonnelNo" => "26", "Name" => "IKA UMI AZIZAH"],
            // ["PersonnelNo" => "13", "Name" => "CHATERINA NIMAS TITIS WINASTI"],
            // ["PersonnelNo" => "9", "Name" => "ANDIONO ARI M NUR"],
            // ["PersonnelNo" => "141", "Name" => "YOLANDA LAURENCIA GEOVANNY"],
            // ["PersonnelNo" => "53", "Name" => "REYNANDA VIOLINA AGUS DAMAYANTI"],
            // ["PersonnelNo" => "76", "Name" => "YEHEZKIEL LINANDI"],
            // ["PersonnelNo" => "24", "Name" => "HARIYANTO"],
            // ["PersonnelNo" => "2", "Name" => "ABDUL GHOFUR"],
            // ["PersonnelNo" => "72", "Name" => "WEKA NASTITI PRANA YUANTI"],
            // ["PersonnelNo" => "134", "Name" => "NURUL HUDA"],
            // ["PersonnelNo" => "6", "Name" => "ALFIAN RIZQI ROHMANDIANSYAH"],
            // ["PersonnelNo" => "103", "Name" => "DENY ANDRIANTO"],
            // ["PersonnelNo" => "9001", "Name" => "ACHMAT ALBASIR"],
            // ["PersonnelNo" => "9003", "Name" => "Aditia Rizqi Darmawan"],
            // ["PersonnelNo" => "104", "Name" => "FANNY ERYA SAMANTA"],
            // ["PersonnelNo" => "9005", "Name" => "AGUS PRASETIYO"],
            // ["PersonnelNo" => "9008", "Name" => "AMALIA FITRI"],
            // ["PersonnelNo" => "105", "Name" => "FERY SUSANTO"],
            // ["PersonnelNo" => "9009", "Name" => "ANDRE MADONI"],
            // ["PersonnelNo" => "162", "Name" => "EKO AJI SATRIA"],
            // ["PersonnelNo" => "107", "Name" => "SUNARTI"],
            // ["PersonnelNo" => "365", "Name" => "CICI DISTRIANAH"],
            // ["PersonnelNo" => "77", "Name" => "SITI JARROH"],
            // ["PersonnelNo" => "9014", "Name" => "DEBI INDAH WAHYUNI"],
            // ["PersonnelNo" => "9115", "Name" => "DEDIK DWI SAPUTRA"],
            // ["PersonnelNo" => "9152", "Name" => "DIANA TYAS SAPUTRI"],
            // ["PersonnelNo" => "131", "Name" => "SITI MAYSARO"],
            // ["PersonnelNo" => "109", "Name" => "MAWAN YULIANTO"],
            // ["PersonnelNo" => "282", "Name" => "DIMAS ADITYAH"],
            // ["PersonnelNo" => "110", "Name" => "BUDIONO"],
            // ["PersonnelNo" => "111", "Name" => "DHANA INDRA SENTOSA"],
            // ["PersonnelNo" => "79", "Name" => "LILIS PUJIASTUTIK"],
            // ["PersonnelNo" => "96", "Name" => "SULASTRI PRF"],
            // ["PersonnelNo" => "9118", "Name" => "Efendi"],
            // ["PersonnelNo" => "9119", "Name" => "EFENDI HERMAWAN"],
            // ["PersonnelNo" => "9120", "Name" => "EKA WULANDARI"],
            // ["PersonnelNo" => "9121", "Name" => "ELY EKAWATI"],
            // ["PersonnelNo" => "9122", "Name" => "ERIKA WANDA WULANDARI"],
            // ["PersonnelNo" => "9124", "Name" => "ERNIA"],
            // ["PersonnelNo" => "9125", "Name" => "EVA LESTARI NINGSIH"],
            // ["PersonnelNo" => "112", "Name" => "CHOTIMAH"],
            // ["PersonnelNo" => "81", "Name" => "HERWIN"],
            // ["PersonnelNo" => "82", "Name" => "AUNUL ISLAMIYAH"],
            // ["PersonnelNo" => "83", "Name" => "ZAENAL DWI IFANI"],
            // ["PersonnelNo" => "206", "Name" => "FITRI ROMAYATI"],
            // ["PersonnelNo" => "9013", "Name" => "FITRI SETIA ARIYANTI"],
            // ["PersonnelNo" => "9128", "Name" => "HASANAH"],
            // ["PersonnelNo" => "84", "Name" => "LUTFI ANDRE IRAWAN"],
            // ["PersonnelNo" => "114", "Name" => "DANI SUPRAYETNO"],
            // ["PersonnelNo" => "147", "Name" => "ALFIAN AZMI ACHMAD HABIBI"],
            // ["PersonnelNo" => "9130", "Name" => "INDAH WULANDARI"],
            // ["PersonnelNo" => "116", "Name" => "SITI FATIMA JAZILAH"],
            // ["PersonnelNo" => "85", "Name" => "NUR SAIDAH"],
            // ["PersonnelNo" => "9131", "Name" => "INTAN WAHYU WILUJENG"],
            // ["PersonnelNo" => "117", "Name" => "DAMI"],
            // ["PersonnelNo" => "259", "Name" => "JUROTUN NISAH"],
            // ["PersonnelNo" => "132", "Name" => "LUSIANA PAIJEM"],
            // ["PersonnelNo" => "9134", "Name" => "LIA RAHMAWATI"],
            // ["PersonnelNo" => "119", "Name" => "SAFIYEH"],
            // ["PersonnelNo" => "86", "Name" => "ALFIAN"],
            // ["PersonnelNo" => "120", "Name" => "S. HARINI"],
            // ["PersonnelNo" => "9135", "Name" => "LILA OLIVYA PRIVANA"],
            // ["PersonnelNo" => "9136", "Name" => "LINA DIANITA"],
            // ["PersonnelNo" => "154", "Name" => "LUZIANA"],
            // ["PersonnelNo" => "133", "Name" => "NANIK SUHERMAWATI"],
            // ["PersonnelNo" => "9139", "Name" => "MIFTAHUL ULUM"],
            // ["PersonnelNo" => "121", "Name" => "MULYADI"],
            // ["PersonnelNo" => "88", "Name" => "UCI USWATUN CHASANAH"],
            // ["PersonnelNo" => "89", "Name" => "AGUS PRIYO WIYONO"],
            // ["PersonnelNo" => "122", "Name" => "INAKUM"],
            // ["PersonnelNo" => "90", "Name" => "SITI MASLIKAH"],
            // ["PersonnelNo" => "9140", "Name" => "MUCHAMMAD SADHAM HUSEN"],
            // ["PersonnelNo" => "123", "Name" => "ADE WISMA TRI WAHYU"],
            // ["PersonnelNo" => "124", "Name" => "KUMAISAROH"],
            // ["PersonnelNo" => "125", "Name" => "LUTFI SHOFIYUDDIN"],
            // ["PersonnelNo" => "9142", "Name" => "MUCHLAS PUTRA SUDHANA"],
            // ["PersonnelNo" => "91", "Name" => "AHMAD SYAFII"],
            // ["PersonnelNo" => "9143", "Name" => "MUFARIDA"],
            // ["PersonnelNo" => "342", "Name" => "MUHAMMAD HUSAIN ABDILLAH"],
            // ["PersonnelNo" => "9145", "Name" => "MUHAMMAD ROSELI"],
            // ["PersonnelNo" => "9051", "Name" => "NABILA PUTRI GHOZALI"],
            // ["PersonnelNo" => "93", "Name" => "SUGENG RAHARJO"],
            // ["PersonnelNo" => "94", "Name" => "SUMIATUN"],
            // ["PersonnelNo" => "126", "Name" => "NOSA HARIATI"],
            // ["PersonnelNo" => "9147", "Name" => "NOER NOVITA SETIAWATI"],
            // ["PersonnelNo" => "145", "Name" => "PARNO"],
            // ["PersonnelNo" => "80", "Name" => "SULASTRI HBL"],
            // ["PersonnelNo" => "9058", "Name" => "RATNA FITASARI"],
            // ["PersonnelNo" => "197", "Name" => "AVRILIA MAS UDAH"],
            // ["PersonnelNo" => "9060", "Name" => "RIA RESTY ANGGRAENI"],
            // ["PersonnelNo" => "9061", "Name" => "RISTANTO"],
            // ["PersonnelNo" => "99", "Name" => "YUDI SUASWORO"],
            // ["PersonnelNo" => "100", "Name" => "MUCH. SHOLEH"],
            // ["PersonnelNo" => "101", "Name" => "HELMI FAUZI"],
            // ["PersonnelNo" => "168", "Name" => "RUDY WAHYU SAPUTRA"],
            // ["PersonnelNo" => "128", "Name" => "ABDUL KARIM"],
            // ["PersonnelNo" => "9110", "Name" => "RUSDI"],
            // ["PersonnelNo" => "9065", "Name" => "SAMSUL HADI"],
            // ["PersonnelNo" => "178", "Name" => "SENDI PRATAMA"],
            // ["PersonnelNo" => "9070", "Name" => "SITI ROBIBAH"],
            // ["PersonnelNo" => "152", "Name" => "SOEFAIDIK KUSWANTORO"],
            // ["PersonnelNo" => "9071", "Name" => "SRI WATININGSIH"],
            // ["PersonnelNo" => "153", "Name" => "SUMARIYONO HERMAWAN"],
            // ["PersonnelNo" => "9075", "Name" => "SUWARNI"],
            // ["PersonnelNo" => "8075", "Name" => "SAIFUL AFFANDI"],
            // ["PersonnelNo" => "9107", "Name" => "TEGUH DWI SAPUTRO"],
            // ["PersonnelNo" => "9077", "Name" => "TEGUH SANTOSO"],
            // ["PersonnelNo" => "183", "Name" => "TRI ANDRIANTO ROCHMATULLOH"],
            // ["PersonnelNo" => "9079", "Name" => "TRI AYU NING TIYAS"],
            // ["PersonnelNo" => "177", "Name" => "TRI WAHYUNI SURYA DEWI"],
            // ["PersonnelNo" => "8047", "Name" => "HENDRIKUS RICKY MITAN"],
            // ["PersonnelNo" => "9083", "Name" => "WIJAYANTI KUSUMANINGTYAS"],
            // ["PersonnelNo" => "5004", "Name" => "DWI LUSIANA"],
            // ["PersonnelNo" => "8014", "Name" => "ANNIZA REQYTA AMIR"],
            // ["PersonnelNo" => "8001", "Name" => "AA PUTU SUASTINI"],
            // ["PersonnelNo" => "8023", "Name" => "DEDDY AFERIYANTO"],
            // ["PersonnelNo" => "5012", "Name" => "SELFINA NUGRAHENI"],
            // ["PersonnelNo" => "70008", "Name" => "YEYEN MARYANI"],
            // ["PersonnelNo" => "70009", "Name" => "ALFIRA RAFINSA YASRI"],
            // ["PersonnelNo" => "70002", "Name" => "HENIK YULAIKA"],
            // ["PersonnelNo" => "8081", "Name" => "SRI WAHYUNI"],
            // ["PersonnelNo" => "8085", "Name" => "TIKA ARDIANTI"],
            // ["PersonnelNo" => "8056", "Name" => "LEA CARLA BASTARANI"],
            // ["PersonnelNo" => "5002", "Name" => "NINDITA PINTANING TRI ASTUTI"],
            // ["PersonnelNo" => "5010", "Name" => "SITI AMINAH"],
            // ["PersonnelNo" => "143", "Name" => "ANGGRAINI WIDIASTUTI"],
            // ["PersonnelNo" => "167", "Name" => "EVANDA BELLA ERSALINA"],
            // ["PersonnelNo" => "151", "Name" => "ERI DWI SETYORINI"],
            // ["PersonnelNo" => "142", "Name" => "JUNI IRINIA LESTARI"],
            // ["PersonnelNo" => "184", "Name" => "YOGI ANDREANSYAH"],
            // ["PersonnelNo" => "186", "Name" => "ALI MUCHTAR"],
            // ["PersonnelNo" => "187", "Name" => "ILFI NUR DIANA"],
            // ["PersonnelNo" => "188", "Name" => "DEVI ELIS AGUS BUDIARTO"],
            // ["PersonnelNo" => "189", "Name" => "MOHAMMAD ARDYAS FANDY RAMMDHANI"],
            // ["PersonnelNo" => "149", "Name" => "RIZKI LUTFIYATIN NISA"],
            // ["PersonnelNo" => "137", "Name" => "HERI SUSANTO"],
            // ["PersonnelNo" => "164", "Name" => "MOCHAMAD MAHMUNIR"],
            // ["PersonnelNo" => "144", "Name" => "SUTONO"],
            // ["PersonnelNo" => "158", "Name" => "ACHMAD DAVID CANDRA"],
            // ["PersonnelNo" => "156", "Name" => "CRISTIANTO"],
            // ["PersonnelNo" => "8018", "Name" => "BY LEWI MATHEUS DETHAN"],
            // ["PersonnelNo" => "191", "Name" => "JOHAN ISWARA WIJAYA"],
            // ["PersonnelNo" => "9004", "Name" => "ADYTIA PRASETYA AMANDA PUTRA"],
            // ["PersonnelNo" => "9057", "Name" => "PUK CINTAMI"],
            // ["PersonnelNo" => "9069", "Name" => "SITI MASULAH"],
            // ["PersonnelNo" => "8000", "Name" => "ADELIA RACHMAWATI CHARISA"],
            // ["PersonnelNo" => "8021", "Name" => "DARMAWATI"],
            // ["PersonnelNo" => "8059", "Name" => "MICHAEL ONGKO WIJAYA"],
            // ["PersonnelNo" => "70006", "Name" => "SANTOSO"],
            // ["PersonnelNo" => "9088", "Name" => "ANNISA PUTRI APRILIA"],
            // ["PersonnelNo" => "9100", "Name" => "NAFIRA MAULIDIYA"],
            // ["PersonnelNo" => "9099", "Name" => "MINARSIH"],
            // ["PersonnelNo" => "9098", "Name" => "LINDA SRI WIJAYANTI"],
            // ["PersonnelNo" => "9097", "Name" => "LIDYA WALIMATUS ZAHRA"],
            // ["PersonnelNo" => "9095", "Name" => "FITA AFSARI"],
            // ["PersonnelNo" => "9093", "Name" => "ENDANG EKOWATI"],
            // ["PersonnelNo" => "8005", "Name" => "AGUS NUGROHO NOTO SUSANTO"],
            // ["PersonnelNo" => "9091", "Name" => "DIMAS BUKHIN NUGRAHA"],
            // ["PersonnelNo" => "8008", "Name" => "A.M. AKBAR"],
            // ["PersonnelNo" => "70004", "Name" => "BAYU SETIYAWAN"],
            // ["PersonnelNo" => "9086", "Name" => "ANIS CHOIRUN NISAK"],
            // ["PersonnelNo" => "9096", "Name" => "ISNAINI B S SISTHA YATIM"],
            // ["PersonnelNo" => "70012", "Name" => "MALIK DWI SURYO ATMOJA"],
            // ["PersonnelNo" => "63", "Name" => "SUGENG"],
            // ["PersonnelNo" => "29", "Name" => "INDRIANI"],
            // ["PersonnelNo" => "195", "Name" => "BAYU WHISNU WHARDANA"],
            // ["PersonnelNo" => "196", "Name" => "ACHMAD HIDAYATURROZIQ"],
            // ["PersonnelNo" => "8114", "Name" => "YULIA STEVANI WOWOR"],
            // ["PersonnelNo" => "5011", "Name" => "YURIKE ELVIRA INTAN LESTARI"],
            // ["PersonnelNo" => "140", "Name" => "KIEVIN ALIFFIANSYAH ARDI"],
            // ["PersonnelNo" => "201", "Name" => "WINDRATIARA MULIANI"],
            // ["PersonnelNo" => "9159", "Name" => "HENNY SETIYOWATI"],
            // ["PersonnelNo" => "9157", "Name" => "JIYANI"],
            // ["PersonnelNo" => "8913", "Name" => "NI KADEK DESIANI"],
            // ["PersonnelNo" => "205", "Name" => "HILMI DWI HARTANTO"],
            // ["PersonnelNo" => "208", "Name" => "MOH FARIS"],
            // ["PersonnelNo" => "8140", "Name" => "JUNAEDY ABDILLAH AVRIVIANTIKA"],
            // ["PersonnelNo" => "8147", "Name" => "SHEHRIN HAMONANGAN"],
            // ["PersonnelNo" => "211", "Name" => "SETYO BUDI UTOMO"],
            // ["PersonnelNo" => "8149", "Name" => "GLORY RIAMA HOSIANNA"],
            // ["PersonnelNo" => "5015", "Name" => "IFA WIJAYANTI"],
            // ["PersonnelNo" => "216", "Name" => "MAULUDI WIBAWA"],
            // ["PersonnelNo" => "217", "Name" => "FREDI RISDA SAPUTRA"],
            // ["PersonnelNo" => "9165", "Name" => "AGUS WIRANTONO"],
            // ["PersonnelNo" => "8151", "Name" => "YUSRIL"],
            // ["PersonnelNo" => "8154", "Name" => "SINTA YUNI ARTHA"],
            // ["PersonnelNo" => "221", "Name" => "DWI ANTO"],
            // ["PersonnelNo" => "202109", "Name" => "SUKMAWATI"],
            // ["PersonnelNo" => "223", "Name" => "ELLYANA DWI SOENTORO"],
            // ["PersonnelNo" => "9179", "Name" => "SASA MULYANTI"],
            // ["PersonnelNo" => "9190", "Name" => "RISKA PRIYANTI"],
            // ["PersonnelNo" => "9192", "Name" => "LINDA KUSNIYA"],
            // ["PersonnelNo" => "9195", "Name" => "EVI LUSIANA WATI"],
            // ["PersonnelNo" => "226", "Name" => "MUHAMMAD ARIF ROIS MAHARDIKA"],
            // ["PersonnelNo" => "9992", "Name" => "LILI ENDAH PRIHASTUTI"],
            // ["PersonnelNo" => "228", "Name" => "DWI RENY WULANDARI"],
            // ["PersonnelNo" => "9196", "Name" => "IDA WIJAYANTI"],
            // ["PersonnelNo" => "9199", "Name" => "KHOSIROH FEBRIANI"],
            // ["PersonnelNo" => "9206", "Name" => "AFRIDA MITA SYAHRIA"],
            // ["PersonnelNo" => "230", "Name" => "MOH. ADI SUSANTO"],
            // ["PersonnelNo" => "235", "Name" => "MOCHAMAD UFRIYANTO"],
            // ["PersonnelNo" => "232", "Name" => "CAESAR JULIO SEBASTIAN TITO PUTRA JUNAEDI"],
            // ["PersonnelNo" => "9216", "Name" => "DESI ARSITASARI"],
            // ["PersonnelNo" => "92123", "Name" => "HERI KRISTIONO"],
            // ["PersonnelNo" => "8948", "Name" => "AFI GLEDISTIN"],
            // ["PersonnelNo" => "239", "Name" => "MUHAMMAD DIMAS PRIYANTO"],
            // ["PersonnelNo" => "255", "Name" => "SUDARNO"],
            // ["PersonnelNo" => "256", "Name" => "YUSTIA GRESDIANTI"],
            // ["PersonnelNo" => "257", "Name" => "ANDRE ARENDRA"],
            // ["PersonnelNo" => "8162", "Name" => "MUHAMMAD NOOR"],
            // ["PersonnelNo" => "8159", "Name" => "SRI WAHYUNI"],
            // ["PersonnelNo" => "8160", "Name" => "SRI REJEKI HAPSARI"],
            // ["PersonnelNo" => "8161", "Name" => "IWAN PURNAMA"],
            // ["PersonnelNo" => "8169", "Name" => "KHASAN"],
            // ["PersonnelNo" => "260", "Name" => "VAHLEVI PERMATASARI"],
            // ["PersonnelNo" => "263", "Name" => "CHOMSIAH"],
            // ["PersonnelNo" => "5040", "Name" => "YULI INDAH KUSWATI"],
            // ["PersonnelNo" => "264", "Name" => "MAHARDIANA NURFIDAH"],
            // ["PersonnelNo" => "265", "Name" => "YUGFAR WICAKSONO"],
            // ["PersonnelNo" => "266", "Name" => "TUBAGUS AKHMAD RAMA FAUZI"],
            // ["PersonnelNo" => "268", "Name" => "HAFIS ALAMSYAH"],
            // ["PersonnelNo" => "8179", "Name" => "MUHAMMAD BAGJA AWALLUDIN MUGHNI"],
            // ["PersonnelNo" => "269", "Name" => "MERCUSI DWINDA KARTIKASARI"],
            // ["PersonnelNo" => "5042", "Name" => "MEGA MUSLIANA"],
            // ["PersonnelNo" => "5044", "Name" => "MARLIANA"],
            // ["PersonnelNo" => "5045", "Name" => "SELVY KADIR"],
            // ["PersonnelNo" => "5047", "Name" => "DENA ELVINA PRATIWI"],
            // ["PersonnelNo" => "8904", "Name" => "TUTI SUGIYANTI"],
            // ["PersonnelNo" => "272", "Name" => "NAURA CHAIRUNNISA SIGIT"],
            // ["PersonnelNo" => "5050", "Name" => "SARI FEBRIANA"],
            // ["PersonnelNo" => "273", "Name" => "ANDRI YUDHA TIRTAYASA"],
            // ["PersonnelNo" => "5051", "Name" => "RITA MUSTOFIA"],
            // ["PersonnelNo" => "5065", "Name" => "MEGA RAHMAWATI"],
            // ["PersonnelNo" => "5068", "Name" => "FRANCISKA YULIANA"],
            // ["PersonnelNo" => "276", "Name" => "DWIKI SATRIYO SANTOSO"],
            // ["PersonnelNo" => "5072", "Name" => "NURPADILA S"],
            // ["PersonnelNo" => "277", "Name" => "AMRINA ROSYADA"],
            // ["PersonnelNo" => "70031", "Name" => "JULIANA EVASARI SIAHAAN"],
            // ["PersonnelNo" => "9222", "Name" => "MUCHAMMAD ARIF HIDAYAH SAPUTRA"],
            // ["PersonnelNo" => "5078", "Name" => "TINA ROCHAYATI"],
            // ["PersonnelNo" => "5086", "Name" => "TRISWANTI"],
            // ["PersonnelNo" => "5090", "Name" => "NANA ISTIANI"],
            // ["PersonnelNo" => "70036", "Name" => "LIES MARINI"],
            // ["PersonnelNo" => "5000", "Name" => "RISNA PUJI LESTARI"],
            // ["PersonnelNo" => "5096", "Name" => "SUNGKONO"],
            // ["PersonnelNo" => "5095", "Name" => "JEFRI POTUTU"],
            // ["PersonnelNo" => "5190", "Name" => "PUTRI RAHAYU"],
            // ["PersonnelNo" => "283", "Name" => "PADMAWURI FARADISY"],
            // ["PersonnelNo" => "8290", "Name" => "ERIC HASUARY"],
            // ["PersonnelNo" => "284", "Name" => "OKTARINDA DAMAYANTI"],
            // ["PersonnelNo" => "285", "Name" => "RONY JATMIKO"],
            // ["PersonnelNo" => "373", "Name" => "JUAN ROONEY ADITIA YUDAN PRATAMA"],
            // ["PersonnelNo" => "288", "Name" => "KANTI APRILIONI"],
            // ["PersonnelNo" => "289", "Name" => "MOCHAMMAD SANDI"],
            // ["PersonnelNo" => "8786", "Name" => "NUNU RAHFLIA"],
            // ["PersonnelNo" => "5106", "Name" => "GITA ASA PERDANA"],
            // ["PersonnelNo" => "292", "Name" => "ANDRYAN RIZQI ADHCHA SUSANTO"],
            // ["PersonnelNo" => "9229", "Name" => "EVA NOVIANA WARDHANI"],
            // ["PersonnelNo" => "295", "Name" => "NEHEMIA DWI PURWO NUGROHO"],
            // ["PersonnelNo" => "300", "Name" => "DWI PRADEVI YUNIARTA"],
            // ["PersonnelNo" => "5114", "Name" => "SITI NUR HOPIPAH"],
            // ["PersonnelNo" => "5117", "Name" => "IRMA SULISTIA"],
            // ["PersonnelNo" => "301", "Name" => "ALFIYATUS SHOLIKHAH"],
            // ["PersonnelNo" => "302", "Name" => "ANASTASIA ALVITADONA"],
            // ["PersonnelNo" => "8306", "Name" => "MOH. RAMDAN NGGILU"],
            // ["PersonnelNo" => "326", "Name" => "KHANSA FADHILAH RAMADHANIA"],
            // ["PersonnelNo" => "5119", "Name" => "WINA SETIATI"],
            // ["PersonnelNo" => "308", "Name" => "ALMAYANI NASUTION, S.KOM"],
            // ["PersonnelNo" => "5124", "Name" => "TARLIN WENDHANTI"],
            // ["PersonnelNo" => "8304", "Name" => "JULITA TODING"],
            // ["PersonnelNo" => "8307", "Name" => "FRANSYOROSMETLI AG"],
            // ["PersonnelNo" => "9232", "Name" => "EKA PRATAMA SAPUTRA"],
            // ["PersonnelNo" => "9234", "Name" => "WAHYU PUTRA RAMADANI"],
            // ["PersonnelNo" => "315", "Name" => "BAGAS SGORO"],
            // ["PersonnelNo" => "5126", "Name" => "DIAH OKTAFIA"],
            // ["PersonnelNo" => "5128", "Name" => "AMILIA VIDIA LAKSONO"],
            // ["PersonnelNo" => "8914", "Name" => "SRI UMI RAHAYU, SE"],
            // ["PersonnelNo" => "317", "Name" => "ZALIZA UBAIDA PURENITTA"],
            // ["PersonnelNo" => "8916", "Name" => "DHANI IKHSAN DERMAWAN"],
            // ["PersonnelNo" => "6007", "Name" => "ERA WIJAYANTI"],
            // ["PersonnelNo" => "6008", "Name" => "ERNIS RETNO HARDINI"],
            // ["PersonnelNo" => "6009", "Name" => "ASRI KRISLANI"],
            // ["PersonnelNo" => "6010", "Name" => "JUWARNI"],
            // ["PersonnelNo" => "6011", "Name" => "ASTUTI SRI WIDIYATI"],
            // ["PersonnelNo" => "5131", "Name" => "AI WAWA"],
            // ["PersonnelNo" => "8917", "Name" => "ROSIANI MUSLIMAH"],
            // ["PersonnelNo" => "323", "Name" => "DINY EKA SAVITRI"],
            // ["PersonnelNo" => "8919", "Name" => "ZUSA EFFENDI"],
            // ["PersonnelNo" => "9237", "Name" => "MUHAMAD ALDINO WICAKSONO"],
            // ["PersonnelNo" => "9238", "Name" => "ARISKY SATRIO UTOMO"],
            // ["PersonnelNo" => "324", "Name" => "NUFIYANTO IRAWAN"],
            // ["PersonnelNo" => "8921", "Name" => "FITRIANI"],
            // ["PersonnelNo" => "6013", "Name" => "SUWARSINI"],
            // ["PersonnelNo" => "6014", "Name" => "ANANDA TUSTAMMA SALSABILA"],
            // ["PersonnelNo" => "6015", "Name" => "KUSRINI"],
            // ["PersonnelNo" => "6016", "Name" => "RETNO HARYANTI SETIOWATI"],
            // ["PersonnelNo" => "325", "Name" => "PAULUS SUPRAYITNO"],
            // ["PersonnelNo" => "5197", "Name" => "RESTI FEBRIANI WULANDARI"],
            // ["PersonnelNo" => "8924", "Name" => "LUH ENDRI APRILIANI"],
            // ["PersonnelNo" => "328", "Name" => "RIDHA OCTA NUR AFIFAH"],
            // ["PersonnelNo" => "6021", "Name" => "INTAN PURNAMA SARI"],
            // ["PersonnelNo" => "6022", "Name" => "NUR AKMALIA"],
            // ["PersonnelNo" => "6023", "Name" => "ANSARIAH"],
            // ["PersonnelNo" => "6024", "Name" => "DEWI MULYANI ASIH"],
            // ["PersonnelNo" => "5143", "Name" => "ALFI ILMIYATUN NAFIAH"],
            // ["PersonnelNo" => "5144", "Name" => "NOFI SULISTYOWATI"],
            // ["PersonnelNo" => "329", "Name" => "A. GILANG ROMADHON"],
            // ["PersonnelNo" => "8932", "Name" => "JIHAN IBBTI SAMAH"],
            // ["PersonnelNo" => "6026", "Name" => "TRI IS YANIK"],
            // ["PersonnelNo" => "6027", "Name" => "PUTRI SRI DEVI"],
            // ["PersonnelNo" => "6033", "Name" => "ENDANG SUPRIANI BR SEMBIRING"],
            // ["PersonnelNo" => "6035", "Name" => "WIDI ERA PRATIWI"],
            // ["PersonnelNo" => "5151", "Name" => "SILVIA V DONDONGI"],
            // ["PersonnelNo" => "5152", "Name" => "ISTY KAMAH"],
            // ["PersonnelNo" => "6043", "Name" => "SUSILAWATI"],
            // ["PersonnelNo" => "5199", "Name" => "ADE SASTIKA"],
            // ["PersonnelNo" => "6051", "Name" => "DEWI ASRIYANI"],
            // ["PersonnelNo" => "6055", "Name" => "AFIFAH GHONIYAH RITONGA"],
            // ["PersonnelNo" => "6052", "Name" => "EVA YULIANA"],
            // ["PersonnelNo" => "5156", "Name" => "MONICA ANJELIA"],
            // ["PersonnelNo" => "8933", "Name" => "MEILINA SITANGGANG"],
            // ["PersonnelNo" => "332", "Name" => "PAULINUS DARMAN"],
            // ["PersonnelNo" => "333", "Name" => "HENDRIK EKO PRASETYO"],
            // ["PersonnelNo" => "334", "Name" => "RIZKY RAHAYU"],
            // ["PersonnelNo" => "5159", "Name" => "MEGAWATI"],
            // ["PersonnelNo" => "6060", "Name" => "SENJAWATI"],
            // ["PersonnelNo" => "8937", "Name" => "ARI AGUSTIN"],
            // ["PersonnelNo" => "337", "Name" => "HO KEYNE"],
            // ["PersonnelNo" => "5162", "Name" => "SARIFAH AYU VITIOLA"],
            // ["PersonnelNo" => "6065", "Name" => "SITI NURFADILAH"],
            // ["PersonnelNo" => "6066", "Name" => "YULI YANTI"],
            // ["PersonnelNo" => "9240", "Name" => "MOCH RIZAL ISNAN"],
            // ["PersonnelNo" => "341", "Name" => "SYAIDAH ROHMATUL UMMAH"],
            // ["PersonnelNo" => "343", "Name" => "HILMI HAQQI SAUSANTI"],
            // ["PersonnelNo" => "5164", "Name" => "CITRA ARUM LESTARI"],
            // ["PersonnelNo" => "5166", "Name" => "NI KOMANG DIVA SETIANI"],
            // ["PersonnelNo" => "5167", "Name" => "MIRA NOVIANTI"],
            // ["PersonnelNo" => "5168", "Name" => "NOVI ANDRIANI"],
            // ["PersonnelNo" => "5169", "Name" => "YULIANI SAFITRI"],
            // ["PersonnelNo" => "8947", "Name" => "VERONIKA DEWI PUSPITASARI W."],
            // ["PersonnelNo" => "70037", "Name" => "BUDI DARMAWAN"],
            // ["PersonnelNo" => "6072", "Name" => "MARSA NOFIA"],
            // ["PersonnelNo" => "344", "Name" => "MOHAMMAD REZKI MAULANA"],
            // ["PersonnelNo" => "345", "Name" => "FIRDA DWI HARYANTI"],
            // ["PersonnelNo" => "346", "Name" => "DEWI ZAHROTUN NISA"],
            // ["PersonnelNo" => "347", "Name" => "R. ALIFAN RAHMAT BAYU HARWANTO"],
            // ["PersonnelNo" => "5171", "Name" => "FEBI MELIYANA"],
            // ["PersonnelNo" => "335", "Name" => "DIDIK EKO PRASETYO"],
            // ["PersonnelNo" => "5173", "Name" => "PUTRI PRATIWI"],
            // ["PersonnelNo" => "5176", "Name" => "DINDA HALIFA HASAN"],
            // ["PersonnelNo" => "6079", "Name" => "ENDANG LISMA AYU"],
            // ["PersonnelNo" => "6080", "Name" => "NURUL FADILA AMALIA"],
            // ["PersonnelNo" => "351", "Name" => "YEKTI YUSNIAN"],
            // ["PersonnelNo" => "8952", "Name" => "MIA EKA LESTARI"],
            // ["PersonnelNo" => "8954", "Name" => "MASRUKI"],
            // ["PersonnelNo" => "354", "Name" => "FEBIANTI YULIANA"],
            // ["PersonnelNo" => "5182", "Name" => "TITA SAPUTRI"],
            // ["PersonnelNo" => "5184", "Name" => "RESMA FEBIAWANTICHA"],
            // ["PersonnelNo" => "5185", "Name" => "SRI KURNIA INDRAWATI"],
            // ["PersonnelNo" => "5186", "Name" => "YULTIANA SARTIKA ENDANG"],
            // ["PersonnelNo" => "6090", "Name" => "SRI SUPATMI"],
            // ["PersonnelNo" => "356", "Name" => "SANDRA LUKITA SARI"],
            // ["PersonnelNo" => "8960", "Name" => "FEBRIANSYAH PUTRA"],
            // ["PersonnelNo" => "5189", "Name" => "MAYANGSARI"],
            // ["PersonnelNo" => "5191", "Name" => "FIFI YUNITA TRISNA ASIH"],
            // ["PersonnelNo" => "6097", "Name" => "DARMAWATI"],
            // ["PersonnelNo" => "6099", "Name" => "ZULAYKA RAISYA PUTRI NST"],
            // ["PersonnelNo" => "8961", "Name" => "BILKIS FAJARIAH"],
            // ["PersonnelNo" => "8962", "Name" => "ELMI NURUL MAYASARI"],
            // ["PersonnelNo" => "5198", "Name" => "DHANINTA REGGYANA"],
            // ["PersonnelNo" => "5200", "Name" => "DIAH INDAH SARI"],
            // ["PersonnelNo" => "5201", "Name" => "LOLITA MARTHINALOVA"],
            // ["PersonnelNo" => "8964", "Name" => "SRI RAHMADANI"],
            // ["PersonnelNo" => "5202", "Name" => "LUSIANA DAMAYANTI"],
            // ["PersonnelNo" => "5203", "Name" => "TITIS YUNITA SARI"],
            // ["PersonnelNo" => "5206", "Name" => "ATIKAH"],
            // ["PersonnelNo" => "5207", "Name" => "SHAFIRA NAYA RAMADHANI"],
            // ["PersonnelNo" => "5208", "Name" => "INTAN YULIANA"],
            // ["PersonnelNo" => "358", "Name" => "HENDRA KRISTIAWAN"],
            // ["PersonnelNo" => "5209", "Name" => "SINTIA SANDI ALMALA"],
            // ["PersonnelNo" => "5211", "Name" => "ZIZKA NUR AINI"],
            // ["PersonnelNo" => "6104", "Name" => "PUTRI PATRICIA"],
            // ["PersonnelNo" => "6106", "Name" => "KURNIAWATI"],
            // ["PersonnelNo" => "359", "Name" => "CHURIL FIRDAH"],
            // ["PersonnelNo" => "360", "Name" => "DIAH PARAMITHA SARI"],
            // ["PersonnelNo" => "8969", "Name" => "I WAYAN SUWARTIKA"],
            // ["PersonnelNo" => "361", "Name" => "MICHAEL PERSADA SEMBIRING"],
            // ["PersonnelNo" => "362", "Name" => "ABDUS SYUKUR"],
            // ["PersonnelNo" => "8974", "Name" => "HERIYANTO"],
            // ["PersonnelNo" => "8978", "Name" => "MASNI MUSTIR"],
            // ["PersonnelNo" => "364", "Name" => "NUR AGHNAITA HAYATI"],
            // ["PersonnelNo" => "5212", "Name" => "INTAN SARI HARUMNISA"],
            // ["PersonnelNo" => "5213", "Name" => "SEPTI ADELIA"],
            // ["PersonnelNo" => "5215", "Name" => "SISKA RANI DEVA YANTI"],
            // ["PersonnelNo" => "5216", "Name" => "YULIANA B"],
            // ["PersonnelNo" => "5217", "Name" => "RAHMAWATI"],
            // ["PersonnelNo" => "5218", "Name" => "NINI RAMADANTI"],
            // ["PersonnelNo" => "5219", "Name" => "NENENG SRIATIKAH IRMAWATI"],
            // ["PersonnelNo" => "6119", "Name" => "YAYUK SUSANTI"],
            // ["PersonnelNo" => "6120", "Name" => "KISTIN MUTAWASITOH"],
            // ["PersonnelNo" => "6123", "Name" => "NURHASANAH"],
            // ["PersonnelNo" => "6129", "Name" => "RIZKI DWI UTARI"],
            // ["PersonnelNo" => "6130", "Name" => "LINDA SARI"],
            // ["PersonnelNo" => "366", "Name" => "KHARISMA FIRDAUS"],
            // ["PersonnelNo" => "8982", "Name" => "NITA SUNDARI"],
            // ["PersonnelNo" => "8985", "Name" => "STHECY WIDYA NENGSY KELMASKOSSU"],
            // ["PersonnelNo" => "367", "Name" => "JANUAR DIMAS RIFA'I"],
            // ["PersonnelNo" => "5223", "Name" => "VITRI GUSTINI"],
            // ["PersonnelNo" => "368", "Name" => "RHEVINDRA PERMATA ANGGRIAWAN"],
            // ["PersonnelNo" => "5224", "Name" => "PUTRI IZZANA SYAHFIRA"],
            // ["PersonnelNo" => "9242", "Name" => "LULUB AZIZAH RETNOWATI"],
            // ["PersonnelNo" => "9244", "Name" => "FILKANOVA ERFIN"],
            // ["PersonnelNo" => "369", "Name" => "IFTIROSYA HAKIKIA"],
            // ["PersonnelNo" => "5228", "Name" => "NENY LUTFIANI"],
            // ["PersonnelNo" => "5230", "Name" => "MEGA NARVIA"],
            // ["PersonnelNo" => "5231", "Name" => "ICHA TRIWAHYUNI"],
            // ["PersonnelNo" => "370", "Name" => "NISA ARIFIA"],
            // ["PersonnelNo" => "8990", "Name" => "APRIYANTI"],
            // ["PersonnelNo" => "371", "Name" => "MUHAMMAD MUNIR"],
            // ["PersonnelNo" => "372", "Name" => "DEWI SINTA ANDANI"],
            // ["PersonnelNo" => "5232", "Name" => "DESI YULVINA BAHRI"],
            // ["PersonnelNo" => "5234", "Name" => "TIYAS WINDYANDINI"],
            // ["PersonnelNo" => "375", "Name" => "AYU AZZAHRA NAILA FANI"],
            // ["PersonnelNo" => "9246", "Name" => "MUHAMMAD NUR AGUNG LAKSONO"],
            // ["PersonnelNo" => "70040", "Name" => "ENDAH LESTARI SUPARDI"],
            // ["PersonnelNo" => "5235", "Name" => "NOVA SOPIANA"],
            // ["PersonnelNo" => "5236", "Name" => "MAULINA HANDAYANI"],
            // ["PersonnelNo" => "5237", "Name" => "SUKESIH"],
            // ["PersonnelNo" => "5238", "Name" => "DIAH WAHYU ANDRIANI"],
            // ["PersonnelNo" => "5240", "Name" => "YANI MULYANINGSIH"],
            // ["PersonnelNo" => "6145", "Name" => "RANI ANGGRAINI"],
            // ["PersonnelNo" => "6147", "Name" => "MUMUN SITI MUNASIH"],
            // ["PersonnelNo" => "6149", "Name" => "SALIYAH EGI ANDISTA"],
            // ["PersonnelNo" => "6150", "Name" => "SUSTER DEWI SINAMBELA,S.E"],
            // ["PersonnelNo" => "6151", "Name" => "DEWI SARTINA"],
            // ["PersonnelNo" => "8997", "Name" => "WIDYA SEPTIA NINGSIH"],
            // ["PersonnelNo" => "8996", "Name" => "KUSNUL ARIFAH"],
            // ["PersonnelNo" => "381", "Name" => "NIKEN AYU SAFITRI"],
            // ["PersonnelNo" => "8998", "Name" => "IKA HANDINI"],
            // ["PersonnelNo" => "8999", "Name" => "SUKMA KARTIKA RUBYASARI"],
            // ["PersonnelNo" => "383", "Name" => "PUTRIANY RAHMAWATI"],
            // ["PersonnelNo" => "384", "Name" => "MAULIDA ALFINA ZAHRO"],
            // ["PersonnelNo" => "8200", "Name" => "AGUS HIDAYAT"],
            // ["PersonnelNo" => "385", "Name" => "I GUSTI NGURAH AGUNG OKA DHANA, S.SI"],
            // ["PersonnelNo" => "5241", "Name" => "HERLINA QURROTA'AINI"],
            // ["PersonnelNo" => "5243", "Name" => "REZKY MILARAHMA"],
            // ["PersonnelNo" => "5245", "Name" => "FATIMAH AZZAHRA"],
            // ["PersonnelNo" => "5242", "Name" => "LIA DESI SETYA PURWANTI"],
            // ["PersonnelNo" => "6155", "Name" => "MUHAMMAD ALIMIN"],
            // ["PersonnelNo" => "6156", "Name" => "FITRIANA"],
            // ["PersonnelNo" => "6158", "Name" => "ERNAWATY MALAU"],
            // ["PersonnelNo" => "387", "Name" => "SITI MAYASAROH"],
            // ["PersonnelNo" => "80001", "Name" => "GREGORIUS SEPTIAN HANGGARA"],
            // ["PersonnelNo" => "80003", "Name" => "MOCH EFENDI"],
            // ["PersonnelNo" => "80004", "Name" => "DEWI MURNIATI"],
            // ["PersonnelNo" => "5248", "Name" => "TETI SUAINI"],
            // ["PersonnelNo" => "5249", "Name" => "DYAH PARAMITHA HASAN"],
            // ["PersonnelNo" => "5251", "Name" => "QORRI AININA"],
            // ["PersonnelNo" => "6161", "Name" => "MUSTIKA SARI"],
            // ["PersonnelNo" => "6162", "Name" => "INDRI NOVALINDA"],
            // ["PersonnelNo" => "6163", "Name" => "NURIDAWATI"],
            // ["PersonnelNo" => "6164", "Name" => "HENY MAHENDRAYANI"],
            // ["PersonnelNo" => "391", "Name" => "SHABRINA FIRDATUL JANNAH"],
            // ["PersonnelNo" => "390", "Name" => "NADA NABEELA OKTAVIARTA"],
            // ["PersonnelNo" => "389", "Name" => "ALIEF PUTRI PARAWANGSA JUHARTO"],
            // ["PersonnelNo" => "388", "Name" => "IRMA RETNO DEWI"],
            // ["PersonnelNo" => "392", "Name" => "LUTHFIATUL LAILY FIRDAUSI"],
            // ["PersonnelNo" => "80005", "Name" => "GUNAWAN KURNIANTO"],
            // ["PersonnelNo" => "80007", "Name" => "FAZLUL ROZI"],
            // ["PersonnelNo" => "80008", "Name" => "NOVITA SILVIA SIREGAR"],
            // ["PersonnelNo" => "393", "Name" => "MOHAMAD ZAINI"],
            // ["PersonnelNo" => "80009", "Name" => "MUHARIANI SUMIA NINGSIH"],
            // ["PersonnelNo" => "395", "Name" => "EGGY FIRMANSYAH"],
            // ["PersonnelNo" => "80010", "Name" => "SISKA YULIA"],
            // ["PersonnelNo" => "9247", "Name" => "MUCHAMMAD ARDIANSYAH"],
            // ["PersonnelNo" => "9248", "Name" => "BIAGGI ARICO SEMBIRING"],
            // ["PersonnelNo" => "5252", "Name" => "SITI MARIAM"],
            // ["PersonnelNo" => "9250", "Name" => "NOVI FERNANDA"],
            // ["PersonnelNo" => "9251", "Name" => "LAILYA RACHMAWATI"],
            // ["PersonnelNo" => "6165", "Name" => "NUNUNG NURHAYATI"],
            // ["PersonnelNo" => "6166", "Name" => "DAYU PUTRI LESTARI"],
            // ["PersonnelNo" => "6167", "Name" => "NENA LUSTIWATI"],
            // ["PersonnelNo" => "6168", "Name" => "VERAWATY HERDANI"],
            // ["PersonnelNo" => "396", "Name" => "ACH. ROBBY AL FAZRI"],
            // ["PersonnelNo" => "6170", "Name" => "SRI WAHYUNI"],
            // ["PersonnelNo" => "6171", "Name" => "VIVI ARYANI"],
            // ["PersonnelNo" => "6172", "Name" => "JIHAN GOLDAREN MAHENDRA"],
            // ["PersonnelNo" => "80011", "Name" => "RIYA AGUSTINI"],
            // ["PersonnelNo" => "8096", "Name" => "DJUNAIDI"],
            // ["PersonnelNo" => "80012", "Name" => "ANNISA SEPTIANI"],
            // ["PersonnelNo" => "80013", "Name" => "KUSMIATI"],
            // ["PersonnelNo" => "80014", "Name" => "MUHAMMAD FAJAR ROMADHON"],
            // ["PersonnelNo" => "9252", "Name" => "MUHAMMAD AMIN ROBIHAM"],
            // ["PersonnelNo" => "9253", "Name" => "FANDHI ACHMAD"],
            // ["PersonnelNo" => "5253", "Name" => "DWITA TRI ASHAYU"],
            // ["PersonnelNo" => "5254", "Name" => "AYANG ADELIA"],
            // ["PersonnelNo" => "5255", "Name" => "HERLINA SUSANTI"],
            // ["PersonnelNo" => "5256", "Name" => "DESABELLA BRILIANTIN"],
            // ["PersonnelNo" => "80015", "Name" => "JUNIARTI PRASSETYO"],
            // ["PersonnelNo" => "397", "Name" => "NOVI ERNAWATI"],
            // ["PersonnelNo" => "80016", "Name" => "HANNISA"],
            // ["PersonnelNo" => "80017", "Name" => "STIVANA MARGARETHA SUPIT"],
            // ["PersonnelNo" => "80018", "Name" => "ELA HAMIDA"],
            // ["PersonnelNo" => "9254", "Name" => "NANDA ALFIRA"],
            // ["PersonnelNo" => "9255", "Name" => "DYVA SISILYA DWI MARGARETNA"],
            // ["PersonnelNo" => "70042", "Name" => "TUTI ALAWIYAH"],
            // ["PersonnelNo" => "80019", "Name" => "RISKA WAHYUNINGTIAS"],
            // ["PersonnelNo" => "6173", "Name" => "NURHIJMAH"],
            // ["PersonnelNo" => "6174", "Name" => "RETNO HARYANTI"],
            // ["PersonnelNo" => "6175", "Name" => "UHA JUHATI"],
            // ["PersonnelNo" => "6176", "Name" => "DIAH RIZKY RAMADHANI"],
            // ["PersonnelNo" => "6177", "Name" => "RIRIS VALENTINA HUTAJULU"],
            // ["PersonnelNo" => "6178", "Name" => "NOVA AULIA"],
            // ["PersonnelNo" => "6179", "Name" => "NENI ANDLINA KOTO"],
            // ["PersonnelNo" => "6180", "Name" => "SAFRINA"],
            // ["PersonnelNo" => "80020", "Name" => "ADITYA ARBI HIMAWAN"],
            // ["PersonnelNo" => "8097", "Name" => "ANGGI DWI HANDAYANI"],
            // ["PersonnelNo" => "8098", "Name" => "HABAKUK"],
            // ["PersonnelNo" => "8099", "Name" => "SEVI NUR JANNAH"]
            // ["PersonnelNo" => "273", "Name" => "ANDRI YUDHA TIRTAYASA"],
            // ["PersonnelNo" => "347", "Name" => "R. ALIFAN RAHMAT BAYU HARWANTO"],
            // ["PersonnelNo" => "9091", "Name" => "DIMAS BUKHIN NUGRAHA"],
            // ["PersonnelNo" => "9091", "Name" => "A.M. AKBAR"],
            // ["PersonnelNo" => "70004", "Name" => "BAYU SETIYAWAN"],
            // ["PersonnelNo" => "418", "Name" => "HERI RAMADHAN RS"],
            ["PersonnelNo" => "421", "Name" => "DYAH AJENG PUSPA YUNITA"],
            // Tambahkan data lainnya...
        ];

        foreach ($data as $user) {
            DB::table('tbl_employees')->insert([
                'PersonnelNo' => $user['PersonnelNo'],
                'Name' => $user['Name'],
            ]);
        }
    }
}
