<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ["PersonnelNo" => "12345", "Name" => "Admin"],
            ["PersonnelNo" => "123456", "Name" => "Test Karyawan"],
            ["PersonnelNo" => "20720002", "Name" => "GATOT SUPRIYADI"],
            ["PersonnelNo" => "20720001", "Name" => "PUJUD RUDIANTO"],
            ["PersonnelNo" => "20720003", "Name" => "AL MISBAH"],
            ["PersonnelNo" => "20720004", "Name" => "SULIADI"],
            ["PersonnelNo" => "20720009", "Name" => "MUHAMMAD IMRON"],
            ["PersonnelNo" => "20720007", "Name" => "GATOT SARONO"],
            ["PersonnelNo" => "20720008", "Name" => "SUKARTO A. DJAKARIA"],
            ["PersonnelNo" => "20716006", "Name" => "DIYAH MUKTI  KARTIKA SARI"],
            ["PersonnelNo" => "20720010", "Name" => "OLIVIA ANDRIANI"],
            ["PersonnelNo" => "21122028", "Name" => "ANDREW KUSUMA KIEMAN"],
            ["PersonnelNo" => "20523029", "Name" => "DIMAS CHRISTIAN"],
            ["PersonnelNo" => "20623032", "Name" => "HENDRAWAN HWADIANTO"],
            ["PersonnelNo" => "20720011", "Name" => "PAINO"],
            ["PersonnelNo" => "20720012", "Name" => "SULKAN"],
            ["PersonnelNo" => "20720013", "Name" => "SOLIKUN"],
            ["PersonnelNo" => "20720014", "Name" => "AKHMAD ZAINUL ARIFIN"],
            ["PersonnelNo" => "15", "Name" => "MOHAMAD RIFIN"],
            ["PersonnelNo" => "20720016", "Name" => "MADIONO"],
            ["PersonnelNo" => "20720017", "Name" => "MASHURIN"],
            ["PersonnelNo" => "20720018", "Name" => "MARIYONO"],
            ["PersonnelNo" => "20720019", "Name" => "NUR ROCHMAT"],
            ["PersonnelNo" => "20720020", "Name" => "INDRA LIQUISSA"],
            ["PersonnelNo" => "20720021", "Name" => "MOCH.  RIFA'I"],
            ["PersonnelNo" => "20720022", "Name" => "AHMAD YANI"],
            ["PersonnelNo" => "20122005", "Name" => "ISKANDAR, SE"],
            ["PersonnelNo" => "20720023", "Name" => "SUKADI"],
            ["PersonnelNo" => "20720024", "Name" => "SULISTYOWATI"],
            ["PersonnelNo" => "20720025", "Name" => "TONTI KUSUMA MARTARIKA"],
            ["PersonnelNo" => "20720026", "Name" => "MEI MARIA SUSANTI"],
            ["PersonnelNo" => "20921027", "Name" => "JULIANA"],
            ["PersonnelNo" => "20523031", "Name" => "EKO ROY NOVA PRASETYO"],
            ["PersonnelNo" => "20623033", "Name" => "MARTHA MEISA"],
            ["PersonnelNo" => "20723030", "Name" => "NARENDRA WIBISONO"],
            ["PersonnelNo" => "20923034", "Name" => "YONATHAN TEDJA ABDI"],
            ["PersonnelNo" => "20923035", "Name" => "DESYANA FRISKA KUMALASARI"],
            ["PersonnelNo" => "21023036", "Name" => "HERI MUNANDAR"],
            ["PersonnelNo" => "21023037", "Name" => "SUGENG"],
            ["PersonnelNo" => "38", "Name" => "EDY KURNIADI"],
            ["PersonnelNo" => "21123039", "Name" => "INTAN PERMATA SARI"],
            ["PersonnelNo" => "21123040", "Name" => "EKA SARAS LUKITASARI"],
            ["PersonnelNo" => "21124042", "Name" => "RISA ROSANDY"],
            ["PersonnelNo" => "43", "Name" => "MARIYAH ULFAH"],
            ["PersonnelNo" => "44", "Name" => "MUFRIKHATUL BASYARIA"],
            ["PersonnelNo" => "45", "Name" => "KHAFID ANDRIAN"],
            ["PersonnelNo" => "46", "Name" => "HADI UTOMO"],
            ["PersonnelNo" => "47", "Name" => "M. ROIKHAN"],
            ["PersonnelNo" => "48", "Name" => "HERI SETIAWAN"],
            ["PersonnelNo" => "49", "Name" => "SUWANDI"],
            ["PersonnelNo" => "50", "Name" => "MOCHAMAT CHOIRUL"],
            ["PersonnelNo" => "51", "Name" => "MISDAK"],
            ["PersonnelNo" => "52", "Name" => "NUR LAILI"],
            ["PersonnelNo" => "53", "Name" => "MOH. NURROJI"],
            ["PersonnelNo" => "54", "Name" => "KASDI"],
            ["PersonnelNo" => "21124055", "Name" => "MOH. ANDI RAHMAWAN"],
            ["PersonnelNo" => "56", "Name" => "ARIF ARIANTO"],
            ["PersonnelNo" => "57", "Name" => "MUHAMAD YUSUF"],
            ["PersonnelNo" => "58", "Name" => "MUHAMMAD NURMAN Y"],
            ["PersonnelNo" => "59", "Name" => "AGUNG PURWONO"],
            ["PersonnelNo" => "60", "Name" => "NGADIO DIHARJO"],
            ["PersonnelNo" => "61", "Name" => "M. SAIFUR RIZAL"],
            ["PersonnelNo" => "62", "Name" => "MOH. MUKROMIN"],
            ["PersonnelNo" => "63", "Name" => "NOR HADI"],
            ["PersonnelNo" => "64", "Name" => "CACUK SUPROBO"],
            ["PersonnelNo" => "65", "Name" => "SYAIFUL HUDA"],
            ["PersonnelNo" => "66", "Name" => "ADI KRISNANTO"],
            ["PersonnelNo" => "67", "Name" => "ABD SUTRISNO"],
            ["PersonnelNo" => "68", "Name" => "JUNADI"],
            ["PersonnelNo" => "69", "Name" => "RIO PRATAMA"],
            ["PersonnelNo" => "70", "Name" => "ROHMAT FATAHUDIN"],
            ["PersonnelNo" => "71", "Name" => "ABD MUNIP"],
            ["PersonnelNo" => "72", "Name" => "DENY SETIADI"],
            ["PersonnelNo" => "73", "Name" => "ANANG SUPRIANTO"],
            ["PersonnelNo" => "74", "Name" => "MOCH. SYAIFUDIN"],
            ["PersonnelNo" => "75", "Name" => "ISWANDI"],
            ["PersonnelNo" => "76", "Name" => "HENDRA MARDIYANTO"],
            ["PersonnelNo" => "77", "Name" => "M YASIN"],
            ["PersonnelNo" => "78", "Name" => "MUHAMMAD FATHUL ALIM"],
            ["PersonnelNo" => "79", "Name" => "SEPTA DWI LESMANA"],
            ["PersonnelNo" => "80", "Name" => "MUCHAMAD ALWI"],
            ["PersonnelNo" => "81", "Name" => "ERLI DWI PARAMITA"],
            ["PersonnelNo" => "82", "Name" => "M. BENY STIAWAN"],
            ["PersonnelNo" => "83", "Name" => "MUHAMAD ABDUL MAJID"],
            ["PersonnelNo" => "84", "Name" => "IMAM SAFII"],
            ["PersonnelNo" => "85", "Name" => "RUDIHARTO"],
            ["PersonnelNo" => "86", "Name" => "ARIF KUSTIONO"],
            ["PersonnelNo" => "87", "Name" => "ACH. MUZAMMIL"],
            ["PersonnelNo" => "88", "Name" => "JUNOTO"],
            ["PersonnelNo" => "89", "Name" => "BUDI DARMAWAN"],
            ["PersonnelNo" => "90", "Name" => "MARADEN DODIK W"],
            ["PersonnelNo" => "91", "Name" => "DIMAS AL MUSA"],
            ["PersonnelNo" => "92", "Name" => "Arista Dwi Kusuma Melati"],
            ["PersonnelNo" => "93", "Name" => "UMAR SAID"],
            ["PersonnelNo" => "94", "Name" => "SARIONO"],
            ["PersonnelNo" => "95", "Name" => "ACHMAD MUKLAS"],
            ["PersonnelNo" => "96", "Name" => "MARTONO"],
            ["PersonnelNo" => "97", "Name" => "Slamet Prihatin"],
            ["PersonnelNo" => "98", "Name" => "HENDRA WIDODO"],
            ["PersonnelNo" => "99", "Name" => "ONY SURYANTO"],
            ["PersonnelNo" => "100", "Name" => "BUADI"],
            ["PersonnelNo" => "101", "Name" => "SHOLAKHUDIN"],
            ["PersonnelNo" => "102", "Name" => "ILHAMSYAH TULUS SEMBODO"],
            ["PersonnelNo" => "103", "Name" => "Eko Yunanto"],
            ["PersonnelNo" => "104", "Name" => "SELAMET"],
            ["PersonnelNo" => "105", "Name" => "MOCHAMAD YUSUF"],
            ["PersonnelNo" => "106", "Name" => "DIAN ARITAMA"],
            ["PersonnelNo" => "107", "Name" => "DWI PRASETYO"],
            ["PersonnelNo" => "108", "Name" => "SETYO BUDI"],
            ["PersonnelNo" => "109", "Name" => "HARI ISWANTO"],
            ["PersonnelNo" => "110", "Name" => "YANUAR ABADI"],
            ["PersonnelNo" => "111", "Name" => "JOKO SUPENO"],
            ["PersonnelNo" => "21124112", "Name" => "ONY HARIANTO"],
            ["PersonnelNo" => "113", "Name" => "RUSDIANTO"],
            ["PersonnelNo" => "114", "Name" => "MOKH.KHABIBATUR RIZKI"],
            ["PersonnelNo" => "115", "Name" => "ABDUL MUJIB RAMADHAN"],
            ["PersonnelNo" => "116", "Name" => "WAWAN HADI PRAYITNO"],
            ["PersonnelNo" => "117", "Name" => "MOCHAMMAD IDRIS"],
            ["PersonnelNo" => "118", "Name" => "AGUS HIDAYAT"],
            ["PersonnelNo" => "119", "Name" => "ACHMAD SUKAMTO"],
            ["PersonnelNo" => "120", "Name" => "HERI SANTOSO"],
            ["PersonnelNo" => "121", "Name" => "ARIFIN"],
            ["PersonnelNo" => "122", "Name" => "AGUS SUGIANTO"],
            ["PersonnelNo" => "123", "Name" => "IMRON HANAFI"],
            ["PersonnelNo" => "124", "Name" => "DARTO WIYONO"],
            ["PersonnelNo" => "21124125", "Name" => "HERU KURNIAWAN"],
            ["PersonnelNo" => "126", "Name" => "ACHWAN AYUB"],
            ["PersonnelNo" => "127", "Name" => "KHOIRUL FANANI"],
            ["PersonnelNo" => "128", "Name" => "SYAMSUL MAARIF"],
            ["PersonnelNo" => "129", "Name" => "RUSDI ABDILLAH"],
            ["PersonnelNo" => "130", "Name" => "AHMAD MUHAJIR"],
            ["PersonnelNo" => "131", "Name" => "SAMSUL ARIF"],
            ["PersonnelNo" => "132", "Name" => "SUJAI"],
            ["PersonnelNo" => "133", "Name" => "SYAFII"],
            ["PersonnelNo" => "134", "Name" => "IRWAN QOMARUDIN"],
            ["PersonnelNo" => "135", "Name" => "JAYADI"],
            ["PersonnelNo" => "136", "Name" => "MUCH FARIED SETYOBUDI"],
            ["PersonnelNo" => "137", "Name" => "DWI YULIANTOK"],
            ["PersonnelNo" => "138", "Name" => "HERU SETYO BUDI"],
            ["PersonnelNo" => "139", "Name" => "MESAJI"],
            ["PersonnelNo" => "140", "Name" => "MUSTOFA ARIF"],
            ["PersonnelNo" => "141", "Name" => "AGUS ALAMIN"],
            ["PersonnelNo" => "142", "Name" => "SYAHRIYAR MAHYUDIN"],
            ["PersonnelNo" => "143", "Name" => "DENDY SANTOSO"],
            ["PersonnelNo" => "144", "Name" => "M. YUNUS"],
            ["PersonnelNo" => "21124145", "Name" => "MASHURI"],
            ["PersonnelNo" => "146", "Name" => "EKO ARYO RIWANTO"],
            ["PersonnelNo" => "21124147", "Name" => "LIA MARATUS"],
            ["PersonnelNo" => "148", "Name" => "SYAMSUL HUDA"],
            ["PersonnelNo" => "149", "Name" => "AKHMAD SAHUDI"],
            ["PersonnelNo" => "150", "Name" => "IVA VALILLAH"],
            ["PersonnelNo" => "151", "Name" => "IPONG TRI HANDOKO"],
            ["PersonnelNo" => "152", "Name" => "ABDUL IMRON"],
            ["PersonnelNo" => "153", "Name" => "ANAS RIYADI"],
            ["PersonnelNo" => "154", "Name" => "CAHYONO CATUR WIBOWO"],
            ["PersonnelNo" => "155", "Name" => "SUTIKNO"],
            ["PersonnelNo" => "21124156", "Name" => "PURI DAHAYUS"],
            ["PersonnelNo" => "157", "Name" => "AKHMAD JAINUL ARIFIN"],
            ["PersonnelNo" => "21124158", "Name" => "USLIMIN HUDI SLAMET"],
            ["PersonnelNo" => "159", "Name" => "HENDRA RULIS DWI SASONGKO"],
            ["PersonnelNo" => "160", "Name" => "SUPARTO"],
            ["PersonnelNo" => "21124161", "Name" => "SOEGIANTO"],
            ["PersonnelNo" => "162", "Name" => "EKO PUJI SETIAWAN"],
            ["PersonnelNo" => "163", "Name" => "MUCH. SUWANDI"],
            ["PersonnelNo" => "164", "Name" => "MEVI"],
            ["PersonnelNo" => "165", "Name" => "KAPI HERMAWAN"],
            ["PersonnelNo" => "166", "Name" => "WIYANTO"],
            ["PersonnelNo" => "167", "Name" => "NUR ROHMAD"],
            ["PersonnelNo" => "168", "Name" => "MOHAMMAD AGUS SETIAWAN"],
            ["PersonnelNo" => "169", "Name" => "WULYADI"],
            ["PersonnelNo" => "21124170", "Name" => "VIVING ARIYAS SUDANA"],
            ["PersonnelNo" => "171", "Name" => "MUHAMMAD RAHADIAN A"],
            ["PersonnelNo" => "172", "Name" => "MOHAMMAD ROSULI"],
            ["PersonnelNo" => "173", "Name" => "SUPARLAN"],
            ["PersonnelNo" => "174", "Name" => "SYAHRUL ISNAINI"],
            ["PersonnelNo" => "175", "Name" => "BUDI CAHYONO"],
            ["PersonnelNo" => "176", "Name" => "NURIADIN"],
            ["PersonnelNo" => "177", "Name" => "MOKHAMAD KODIR"],
            ["PersonnelNo" => "178", "Name" => "SAMSUL HADI"],
            ["PersonnelNo" => "179", "Name" => "MUTROFIN"],
            ["PersonnelNo" => "180", "Name" => "SUDIRMAN"],
            ["PersonnelNo" => "21124181", "Name" => "WULIYONO"],
            ["PersonnelNo" => "21124182", "Name" => "SUTEJO"],
            ["PersonnelNo" => "183", "Name" => "KARJO"],
            ["PersonnelNo" => "21124184", "Name" => "LITA MUSTOPA"],
            ["PersonnelNo" => "185", "Name" => "YESY SELVIA AGUSTIEN"],
            ["PersonnelNo" => "186", "Name" => "GATOT KURNIAWAN"],
            ["PersonnelNo" => "21124187", "Name" => "MUNADI"],
            ["PersonnelNo" => "188", "Name" => "SUGIONO"],
            ["PersonnelNo" => "189", "Name" => "MOH. AGUS MUSLIM"],
            ["PersonnelNo" => "190", "Name" => "USNADI"],
            ["PersonnelNo" => "191", "Name" => "SUKARIYADI"],
            ["PersonnelNo" => "192", "Name" => "M. MUTHOHIRIN"],
            ["PersonnelNo" => "193", "Name" => "NOURIS AFRIZAL FAUZI"],
            ["PersonnelNo" => "194", "Name" => "AHMAD SYAIFUDIN"],
            ["PersonnelNo" => "195", "Name" => "MUJI HARIANTO"],
            ["PersonnelNo" => "196", "Name" => "DENI IRWANSAH"],
            ["PersonnelNo" => "197", "Name" => "RIZKY ARDIAN PRATAMA"],
            ["PersonnelNo" => "198", "Name" => "ALIFFIA FAHRIL MADA"],
            ["PersonnelNo" => "199", "Name" => "AAN UTAMIANSYAH"],
            ["PersonnelNo" => "200", "Name" => "IMAM TOHARI"],
            ["PersonnelNo" => "201", "Name" => "SOFYAN ALBANI ANDI OKTORA"],
            ["PersonnelNo" => "202", "Name" => "TITIK DWI ANGGRAINI"],
            ["PersonnelNo" => "21124203", "Name" => "SITI UTMANIARSIH"],
            ["PersonnelNo" => "204", "Name" => "SUGIHARTO"],
            ["PersonnelNo" => "205", "Name" => "JAMIIL MUSLIMIN"],
            ["PersonnelNo" => "206", "Name" => "KUDIHARTO MULYO"],
            ["PersonnelNo" => "207", "Name" => "WAWAN YULIANTO"],
            ["PersonnelNo" => "208", "Name" => "ADI PRAYITNO"],
            ["PersonnelNo" => "209", "Name" => "AKHMAD MUSLIKUDIN"],
            ["PersonnelNo" => "210", "Name" => "YOGI SUDARMANTO"],
            ["PersonnelNo" => "211", "Name" => "PANIR RASITO NUGROHO"],
            ["PersonnelNo" => "212", "Name" => "KELFIN LUQI ANTO"],
            ["PersonnelNo" => "213", "Name" => "GALY VEBRY SASMITA"],
            ["PersonnelNo" => "214", "Name" => "ARIO PRIHATMOKO"],
            ["PersonnelNo" => "215", "Name" => "SHOFII"],
            ["PersonnelNo" => "216", "Name" => "SUNARDI"],
            ["PersonnelNo" => "217", "Name" => "IWAN SUSANTO"],
            ["PersonnelNo" => "218", "Name" => "A HENDRIK FAUZI"],
            ["PersonnelNo" => "219", "Name" => "MHD SANTRI"],
            ["PersonnelNo" => "220", "Name" => "NANDA AYU PRATIWI"],
            ["PersonnelNo" => "221", "Name" => "ACHMAT ZAKARIA"],
            ["PersonnelNo" => "222", "Name" => "MOHAMAD HENDRA KRISDIANTO"],
            ["PersonnelNo" => "223", "Name" => "YANA NINGTYAS"],
            ["PersonnelNo" => "224", "Name" => "DEDI IRAWAN"],
            ["PersonnelNo" => "225", "Name" => "ADEK ADI SAPUTRO"],
            ["PersonnelNo" => "226", "Name" => "NOVI AGUS PRAYITNO"],
            ["PersonnelNo" => "227", "Name" => "Masud Syaifuddin"],
            ["PersonnelNo" => "228", "Name" => "LUCKY DWI APRILIYANTO"],
            ["PersonnelNo" => "229", "Name" => "Mochammad Ali Maskur Musa"],
            ["PersonnelNo" => "21124230", "Name" => "WIDODO"],
            ["PersonnelNo" => "231", "Name" => "Ari"],
            ["PersonnelNo" => "232", "Name" => "Sompi Arbi Sani"],
            ["PersonnelNo" => "233", "Name" => "RUDI HERMANTO"],
            ["PersonnelNo" => "234", "Name" => "Jefri Ardiantoko"],
            ["PersonnelNo" => "235", "Name" => "LYAN HERU PRAMONO"],
            ["PersonnelNo" => "236", "Name" => "Dendy Kriswanto"],
            ["PersonnelNo" => "237", "Name" => "Dhandi Ganang Nugroho"],
            ["PersonnelNo" => "238", "Name" => "Muhammad Firman Syawaludin"],
            ["PersonnelNo" => "239", "Name" => "KHURNIAWANTO"],
            ["PersonnelNo" => "240", "Name" => "Muhammad Febriyanto"],
            ["PersonnelNo" => "241", "Name" => "NUR ALI"],
            ["PersonnelNo" => "242", "Name" => "IDO SURYO UTOMO"],
            ["PersonnelNo" => "243", "Name" => "Feri Fernando"],
            ["PersonnelNo" => "244", "Name" => "SUGIANTO"],
            ["PersonnelNo" => "245", "Name" => "SAIFUL ARIFIN"],
            ["PersonnelNo" => "246", "Name" => "AHMAD JAZULI YUSUF"],
            ["PersonnelNo" => "247", "Name" => "MUHAMMAD. YUDA ZAKARIYAH"],
            ["PersonnelNo" => "248", "Name" => "Mohammad Ali Masykuri"],
            ["PersonnelNo" => "249", "Name" => "SABILAL AINUR ROSYID"],
            ["PersonnelNo" => "250", "Name" => "Novita Dian"],
            ["PersonnelNo" => "251", "Name" => "Adityo Tri Wicaksono"],
            ["PersonnelNo" => "252", "Name" => "FENDI ARDIANSYAH"],
            ["PersonnelNo" => "253", "Name" => "PUTRA JUNI KRISMON"],
            ["PersonnelNo" => "254", "Name" => "WULYONO ADE PURNOMO"],
            ["PersonnelNo" => "255", "Name" => "Gatot Ismawan"],
            ["PersonnelNo" => "256", "Name" => "Anggit Ardian prasetya"],
            ["PersonnelNo" => "257", "Name" => "M. IMRON ROFII"],
            ["PersonnelNo" => "258", "Name" => "MUKHAMMAD NURKHOLIS"],
            ["PersonnelNo" => "259", "Name" => "Duta Abhika"],
            ["PersonnelNo" => "260", "Name" => "LUKMAN HANAFI"],
            ["PersonnelNo" => "261", "Name" => "Wibi Pristiyanto"],
            ["PersonnelNo" => "262", "Name" => "ANDRATYANO TAMA ALFREDA"],
            ["PersonnelNo" => "263", "Name" => "Putri Fatmawati"],
            ["PersonnelNo" => "21124264", "Name" => "ACHMAD SOLEHUDIN AL AYYUBI"],
            ["PersonnelNo" => "265", "Name" => "ARDIANT FIRMANSYAH"],
            ["PersonnelNo" => "266", "Name" => "YOGI EKA PRATAMA"],
            ["PersonnelNo" => "267", "Name" => "JAYANTI WAHYUNINGTIAS"],
            ["PersonnelNo" => "268", "Name" => "SUGENG JAINUDIN"],
            ["PersonnelNo" => "269", "Name" => "BAMBANG PARDIAWAN"],
            ["PersonnelNo" => "270", "Name" => "GUFRON"],
            ["PersonnelNo" => "271", "Name" => "LEO ANGGA RIKSA"],
            ["PersonnelNo" => "272", "Name" => "WAWAN HERMANTO"],
            ["PersonnelNo" => "273", "Name" => "SULIYAT DARMAJI"],
            ["PersonnelNo" => "274", "Name" => "AHMAD SOBIRIN"],
            ["PersonnelNo" => "275", "Name" => "MOKHAMAD FAHRUDIN"],
            ["PersonnelNo" => "276", "Name" => "HERI SISWANTO"],
            ["PersonnelNo" => "277", "Name" => "SAIAN"],
            ["PersonnelNo" => "278", "Name" => "HOIRUL UMAM"],
            ["PersonnelNo" => "279", "Name" => "DIDIK SANTOSO"],
            ["PersonnelNo" => "280", "Name" => "AHMAD NURUDDIN"],
            ["PersonnelNo" => "281", "Name" => "DWI CAHYONO"],
            ["PersonnelNo" => "282", "Name" => "AHMAD DAROINI"],
            ["PersonnelNo" => "283", "Name" => "MOH HAMDI ROSIDI"],
            ["PersonnelNo" => "284", "Name" => "YUDI INDRA MUKTI"],
            ["PersonnelNo" => "285", "Name" => "MOKHAMMAD YUSRON"],
            ["PersonnelNo" => "286", "Name" => "SYAMSUL ARIFIN"],
            ["PersonnelNo" => "287", "Name" => "DUL KAMIM"],
            ["PersonnelNo" => "288", "Name" => "MOCHAMAD SAIFUL"],
            ["PersonnelNo" => "289", "Name" => "M. AFIFUDIN"],
            ["PersonnelNo" => "290", "Name" => "DODI KURNIAWAN"],
            ["PersonnelNo" => "291", "Name" => "DIAN ISTIANTO"],
            ["PersonnelNo" => "292", "Name" => "NUGROHO DWI HERMANTO"],
            ["PersonnelNo" => "293", "Name" => "MUHAMMAD JAWAHIR"],
            ["PersonnelNo" => "294", "Name" => "FIRDAUS"],
            ["PersonnelNo" => "295", "Name" => "WAHYUDI"],
            ["PersonnelNo" => "296", "Name" => "Mulyono"],
            ["PersonnelNo" => "297", "Name" => "ROBI TRIYANTO"],
            ["PersonnelNo" => "298", "Name" => "JUMALI"],
            ["PersonnelNo" => "299", "Name" => "HADI EKO PURWANTO"],
            ["PersonnelNo" => "300", "Name" => "NURHADI IRAWAN"],
            ["PersonnelNo" => "301", "Name" => "SAMTO"],
            ["PersonnelNo" => "302", "Name" => "MOCH KUSAENI"],
            ["PersonnelNo" => "303", "Name" => "SAIFUL WAHID"],
            ["PersonnelNo" => "304", "Name" => "JUWITO"],
            ["PersonnelNo" => "305", "Name" => "ISMANTO"],
            ["PersonnelNo" => "306", "Name" => "MUKHAMAT EDY PRIYANTO"],
            ["PersonnelNo" => "307", "Name" => "MUSTAKIM"],
            ["PersonnelNo" => "308", "Name" => "DIDIT PRAMONO"],
            ["PersonnelNo" => "309", "Name" => "ISBANDI WIBOWO"],
            ["PersonnelNo" => "310", "Name" => "SUYONO"],
            ["PersonnelNo" => "311", "Name" => "NURCHAMID"],
            ["PersonnelNo" => "312", "Name" => "WINARTO"],
            ["PersonnelNo" => "313", "Name" => "SAMSUL ARIFIN"],
            ["PersonnelNo" => "314", "Name" => "AGUS PURWONO"],
            ["PersonnelNo" => "315", "Name" => "BASUKI"],
            ["PersonnelNo" => "316", "Name" => "Iswanto"],
            ["PersonnelNo" => "317", "Name" => "MARIONO"],
            ["PersonnelNo" => "318", "Name" => "MUJIB IBNUS SALAM"],
            ["PersonnelNo" => "319", "Name" => "SAHUDI"],
            ["PersonnelNo" => "320", "Name" => "WAHYU KUKUH SETIYONO"],
            ["PersonnelNo" => "321", "Name" => "Wahyu Habib Alwi"],
            ["PersonnelNo" => "322", "Name" => "RIO FAJAR MURZAQQI S"],
            ["PersonnelNo" => "323", "Name" => "ADI SAPUTRO"],
            ["PersonnelNo" => "324", "Name" => "SULISWANTO"],
            ["PersonnelNo" => "325", "Name" => "EKO DWI S"],
            ["PersonnelNo" => "326", "Name" => "IBNU KHOTTOB"],
            ["PersonnelNo" => "327", "Name" => "Achmad Hidayat"],
            ["PersonnelNo" => "328", "Name" => "ARIS KURNIAWAN"],
            ["PersonnelNo" => "329", "Name" => "CHOIRUL ANWAR"],
            ["PersonnelNo" => "330", "Name" => "SUPRIYO"],
            ["PersonnelNo" => "331", "Name" => "MAHMUD ISA HARIS IRSADI"],
            ["PersonnelNo" => "332", "Name" => "BAMBANG SUTRISNO"],
            ["PersonnelNo" => "333", "Name" => "RUSDIANTO"],
            ["PersonnelNo" => "334", "Name" => "RIONO"],
            ["PersonnelNo" => "335", "Name" => "MOHAMAD ROFIQ"],
            ["PersonnelNo" => "336", "Name" => "YEYEN ARIYANTO"],
            ["PersonnelNo" => "337", "Name" => "NANANG SUHARTANTO"],
            ["PersonnelNo" => "338", "Name" => "HANANTO"],
            ["PersonnelNo" => "339", "Name" => "Adi Tri Suwono"],
            ["PersonnelNo" => "340", "Name" => "AHMAD MACHFUDI HARIYANTO"],
            ["PersonnelNo" => "341", "Name" => "SUARIFIN"],
            ["PersonnelNo" => "342", "Name" => "Akhmad Muklas"],
            ["PersonnelNo" => "343", "Name" => "Muhammad Setiawan Efendi"],
            ["PersonnelNo" => "344", "Name" => "MUHAMMAD SALIM"],
            ["PersonnelNo" => "345", "Name" => "Muhammad Ainun Ajib"],
            ["PersonnelNo" => "346", "Name" => "Ferry Syahrul Fahmeizar"],
            ["PersonnelNo" => "347", "Name" => "Achmad Mufarikhin"],
            ["PersonnelNo" => "348", "Name" => "Aldi Wulyono"],
            ["PersonnelNo" => "349", "Name" => "Hafid Muslih"],
            ["PersonnelNo" => "350", "Name" => "M. ZAINUDDIN"],
            ["PersonnelNo" => "351", "Name" => "SUHARI"],
            ["PersonnelNo" => "352", "Name" => "ALFIN SEPTI NOR CAHYO"],
            ["PersonnelNo" => "353", "Name" => "Angga Bagus Wijayanto"],
            ["PersonnelNo" => "354", "Name" => "Abdul Ghofur"],
            ["PersonnelNo" => "355", "Name" => "M. Bayu Setiawan "],
            ["PersonnelNo" => "356", "Name" => "Afif Maruf"],
            ["PersonnelNo" => "357", "Name" => "Misbahul Mustofa"],
            ["PersonnelNo" => "358", "Name" => "SUMARNO"],
            ["PersonnelNo" => "359", "Name" => "MATUKIN"],
            ["PersonnelNo" => "360", "Name" => "SHOLEH DAFID SHOBIRIN"],
            ["PersonnelNo" => "361", "Name" => "RIDWAN"],
            ["PersonnelNo" => "362", "Name" => "MOH. ROSYADUL ULUM"],
            ["PersonnelNo" => "363", "Name" => "DARJI"],
            ["PersonnelNo" => "364", "Name" => "RISKI DANI SETIAWAN"],
            ["PersonnelNo" => "365", "Name" => "IFAN WAHYUDI"],
            ["PersonnelNo" => "366", "Name" => "MOCHAMAD ALFIN FRENALDI"],
            ["PersonnelNo" => "21124367", "Name" => "DEDDY SUTOMO"],
            ["PersonnelNo" => "368", "Name" => "HANGGA JUNIANTARA"],
            ["PersonnelNo" => "369", "Name" => "RIKY INDRA KURNIAWAN"],
            ["PersonnelNo" => "370", "Name" => "JOYO TIRTO UTOMO"],
            ["PersonnelNo" => "371", "Name" => "KUSNO"],
            ["PersonnelNo" => "372", "Name" => "MAT RUKAN"],
            ["PersonnelNo" => "373", "Name" => "MOKHAMAD NURHASAN"],
            ["PersonnelNo" => "374", "Name" => "SUGIONO"],
            ["PersonnelNo" => "375", "Name" => "UTOMO"],
            ["PersonnelNo" => "376", "Name" => "WAHAB"],
            ["PersonnelNo" => "377", "Name" => "SUPII"],
            ["PersonnelNo" => "378", "Name" => "HADI PAISO"],
            ["PersonnelNo" => "379", "Name" => "TANI SUWITO"],
            ["PersonnelNo" => "380", "Name" => "SUROSO"],
            ["PersonnelNo" => "381", "Name" => "BANDI ACHMADI"],
            ["PersonnelNo" => "384", "Name" => "MUHAMMAD BINTANG YOGI S"],
            ["PersonnelNo" => "385", "Name" => "MOCHAMAD FAUZI"],
            ["PersonnelNo" => "386", "Name" => "NAKASONY AMINULOH"],
            ["PersonnelNo" => "387", "Name" => "DWI ROHMANSYAH"],
            ["PersonnelNo" => "388", "Name" => "AKHMAD HELMI YAHYA"],
            ["PersonnelNo" => "389", "Name" => "ANA RUPIK ASTUTIK"],
            ["PersonnelNo" => "390", "Name" => "ULFAIDAH"],
            ["PersonnelNo" => "391", "Name" => "DIDIK SUPRIYO"],
            ["PersonnelNo" => "392", "Name" => "JUYOKO"],
            ["PersonnelNo" => "393", "Name" => "SELAMET"],
            ["PersonnelNo" => "394", "Name" => "ABD ROHIM"],
            ["PersonnelNo" => "396", "Name" => "TONI IRAWAN"],
            ["PersonnelNo" => "397", "Name" => "RIFAN AZIS DARMAWAN"],
            ["PersonnelNo" => "398", "Name" => "NDARU ADI PRATAMA"],
            ["PersonnelNo" => "20720001", "Name" => "PUJUD RUDIANTO"],
            ["PersonnelNo" => "345", "Name" => "MUHAMMAD AINUN AJIB"],
            ["PersonnelNo" => "400", "Name" => "BAGUS REYNALDI"],
            ["PersonnelNo" => "47", "Name" => "M.ROIKHAN"],
            ["PersonnelNo" => "50", "Name" => "MOCHAMAT CHOIRUL"],
            ["PersonnelNo" => "52", "Name" => "NUR LAILI"],
            ["PersonnelNo" => "249", "Name" => "SABILAL AINUR ROSYID"],
            ["PersonnelNo" => "103", "Name" => "EKO YUNANTO"],
            ["PersonnelNo" => "273", "Name" => "SULIYAT DARMAJI"],
            ["PersonnelNo" => "401", "Name" => "EDI SUTIKNO"],
            ["PersonnelNo" => "403", "Name" => "AKHMAD VARIS EDY TIYA"],
            ["PersonnelNo" => "404", "Name" => "FADHLURROHMAN AKMAL DZAKI ANWAR"],
            ["PersonnelNo" => "405", "Name" => "DIMAS OKTAVIANUS"],
            ["PersonnelNo" => "402", "Name" => "TAMIRAN"],
            ["PersonnelNo" => "296", "Name" => "MULYONO"],
            ["PersonnelNo" => "342", "Name" => "AKHMAD MUKLAS"],
            ["PersonnelNo" => "412", "Name" => "RIZA ADAM"],
            ["PersonnelNo" => "413", "Name" => "RIYAN GILANG FIRMANSYAH"],
            ["PersonnelNo" => "20324414", "Name" => "MELINDA YULIANI"],
            ["PersonnelNo" => "20124406", "Name" => "HENRY WIJAYA"],
            ["PersonnelNo" => "407", "Name" => "AHMAD RIZAL SETYAWAN"],
            ["PersonnelNo" => "383", "Name" => "ABID MUZAQQI ROSYAD"],
            ["PersonnelNo" => "21124041", "Name" => "RETNO LESTARI"],
            ["PersonnelNo" => "399", "Name" => "MAULANA VICKY SYAHRUDDIN"],
            ["PersonnelNo" => "20424415", "Name" => "WELLY SANTOSO"],
            ["PersonnelNo" => "382", "Name" => "MOCHAMAD ROFIK"],
            ["PersonnelNo" => "395", "Name" => "SLAMET"],
            ["PersonnelNo" => "408", "Name" => "MOCHAMAD BASORI"],
            ["PersonnelNo" => "410", "Name" => "GAGUK TRI ASMORO"],
            ["PersonnelNo" => "409", "Name" => "MOH ALFAN"],
            ["PersonnelNo" => "20524416", "Name" => "MARCELLUS FABIAN MAHENDRA"],
            ["PersonnelNo" => "20624420", "Name" => "VERONICA DEWI"],
            ["PersonnelNo" => "20822419", "Name" => "ARIF RACHMAD WIJIANTO DIP"],
            ["PersonnelNo" => "20724422", "Name" => "IRVAN"],
            ["PersonnelNo" => "20724417", "Name" => "FRISKY RAHMAN QHADAFY"],
            ["PersonnelNo" => "20724421", "Name" => "RIKI RENGGALIS"],
            ["PersonnelNo" => "20724418", "Name" => "TARA ICASIA TJUKIPTO"],
            ["PersonnelNo" => "423", "Name" => "FEBBY TRI WULANDARI"],
            ["PersonnelNo" => "20824424", "Name" => "SARI SETIORINI"],
            ["PersonnelNo" => "20924425", "Name" => "MOCH. KUSAENI"],
            ["PersonnelNo" => "426", "Name" => "TOMI SUSANTO"],
            ["PersonnelNo" => "427", "Name" => "ROZA KHOMARULLOH"],
            ["PersonnelNo" => "428", "Name" => "M. ISMAIL FAUZI"],
            ["PersonnelNo" => "429", "Name" => "WAHYU NOPIYANTO"],
            ["PersonnelNo" => "430", "Name" => "PUJI EKO PRIYONO"],
            ["PersonnelNo" => "431", "Name" => "MOHAMMAD SABILUL KHOIRI"],
            ["PersonnelNo" => "432", "Name" => "LUKY OKTAVIAN"],
            ["PersonnelNo" => "433", "Name" => "DION ADI PRAYUGO"],
            ["PersonnelNo" => "434", "Name" => "MUHAMMAD LUKMAN CHAKIM"],
            ["PersonnelNo" => "435", "Name" => "YUSUF FIRMANSYAH"],
            ["PersonnelNo" => "436", "Name" => "EGA CANDRA SAPUTRA"],
            ["PersonnelNo" => "437", "Name" => "RISTRA NAUFAL KUSUMAWARDANI"],
            ["PersonnelNo" => "20924425", "Name" => "JUNIANASARI / HONG CHIENG"],
            ["PersonnelNo" => "20924440", "Name" => "MOCH. FIRDAUS FASA ZULFIKRI"],
            ["PersonnelNo" => "441", "Name" => "NATHANAEL ROUVINNO VABRYANO"],
            ["PersonnelNo" => "442", "Name" => "MUHAMMAD ZANUARYAN"],
            ["PersonnelNo" => "20924439", "Name" => "JESSICA PRISCILLIA GUNAWAN"],
            ["PersonnelNo" => "443", "Name" => "YUSUF WAHYUDI"],
            ["PersonnelNo" => "446", "Name" => "M.SISWANTORO"],
            ["PersonnelNo" => "20924438", "Name" => "TONI WIDODO"],
            ["PersonnelNo" => "21024445", "Name" => "RAFLI SETYAWAN NAJID"],
            ["PersonnelNo" => "447", "Name" => "FIRMANSYAH DWI PUTRA"],
            ["PersonnelNo" => "448", "Name" => "MOKHAMMAD SUMADI"],
            ["PersonnelNo" => "449", "Name" => "DHIMAS EKA FHERDYANSYAH"],
            ["PersonnelNo" => "450", "Name" => "AFKARADO"],
            ["PersonnelNo" => "451", "Name" => "MUHAMMAD RENALDI FERDIANSYAH"],
            ["PersonnelNo" => "452", "Name" => "ALFIN BUDI MAULANA"],
            ["PersonnelNo" => "21024453", "Name" => "NADINE AYSHA LAFINETHDA"],
            ["PersonnelNo" => "21024455", "Name" => "YEGITA ADI PRASETYA"],
            ["PersonnelNo" => "21024454", "Name" => "AGUS ERWANTO"],
            ["PersonnelNo" => "459", "Name" => "WAHYU PURWO WIDODO"],
            ["PersonnelNo" => "458", "Name" => "NARKO WIBOWO"],
            ["PersonnelNo" => "21024462", "Name" => "AFIF DWI RISDIANTO"],
            ["PersonnelNo" => "463", "Name" => "DIMAS ANANDA DWI A"],
            ["PersonnelNo" => "464", "Name" => "SHENDY SURYA MA'SUM"],
            ["PersonnelNo" => "465", "Name" => "MOH. YAZID BAYDHOWI"],
            ["PersonnelNo" => "466", "Name" => "IBNU MAS'UD"],
            ["PersonnelNo" => "467", "Name" => "MOCHAMMAD DIMAS PRASETYO"],
            ["PersonnelNo" => "468", "Name" => "MUHAMMAD AGUS ALI FAUZAN"],
            ["PersonnelNo" => "469", "Name" => "DIKI PURWANTO"],
            ["PersonnelNo" => "470", "Name" => "REYNALDI DIKA PRASETYA"],
            ["PersonnelNo" => "21024456", "Name" => "YAYAK JUNIARTA"],
            ["PersonnelNo" => "470", "Name" => "REYNALDI DIKA PRASETYA"],
            ["PersonnelNo" => "473", "Name" => "ABI NURROHMAN"],
            ["PersonnelNo" => "474", "Name" => "MUHAMMAD SYAHRU G"],
            ["PersonnelNo" => "476", "Name" => "YUSUF ARDIANO FEBRIANTO"],
            ["PersonnelNo" => "21124457", "Name" => "ADE SELLO SAPUALAM"],
            ["PersonnelNo" => "21124460", "Name" => "MEFILIANA LIEGUNA"],
            ["PersonnelNo" => "477", "Name" => "WAHYU ADITYA"],
            ["PersonnelNo" => "478", "Name" => "MUHAMMAD ZAINUL ARIF"],
            ["PersonnelNo" => "475", "Name" => "MOCHAMMAD ALFIN HAMZAH"],
            ["PersonnelNo" => "479", "Name" => "RICKY AQUINALDO"],
            ["PersonnelNo" => "21124461", "Name" => "MONIKA SWASTIKA,,SE.MM"],
            ["PersonnelNo" => "21124482", "Name" => "BORISKI SINAGA RICARD"],
            ["PersonnelNo" => "21124483", "Name" => "JOHAN CHENWIDY"],
            ["PersonnelNo" => "21124484", "Name" => "RICHARD"],
            ["PersonnelNo" => "480", "Name" => "REZA RIZQI SETIANTO"],
            ["PersonnelNo" => "481", "Name" => "RISKI RANDIKA ARYA PRATAMA"],
            ["PersonnelNo" => "21124471", "Name" => "AHMAD SHANI IVAN FAUZI"],
            ["PersonnelNo" => "21124485", "Name" => "SUDARNO"],
            ["PersonnelNo" => "21224492", "Name" => "KHOIRUN NISA ASHAR"],
            ["PersonnelNo" => "486", "Name" => "ALI MUSTOFA"],
            ["PersonnelNo" => "487", "Name" => "SARUL"],
            ["PersonnelNo" => "488", "Name" => "MUHAMMAD IRFAN HIKMAWAN"],
            ["PersonnelNo" => "489", "Name" => "SYUHADAK"],
            ["PersonnelNo" => "490", "Name" => "MUHAMMAD FARREL ISRAFIL ADAM"],
            ["PersonnelNo" => "491", "Name" => "DIO ANGGA SAPUTRA"],
            ["PersonnelNo" => "495", "Name" => "RACHMAD FAUZUL ADHIM"],
            ["PersonnelNo" => "497", "Name" => "MOH. YUSRIL AMIN ABDILLAH"],
            ["PersonnelNo" => "498", "Name" => "MOHAMAD JAINUDIN"],
            ["PersonnelNo" => "499", "Name" => "MUHAMMAD MAULUDIN"],
            ["PersonnelNo" => "496", "Name" => "MISBAHUL MUNIR"],
            ["PersonnelNo" => "500", "Name" => "MUHAMMAD BAGUS KURNIAWAN"],
            ["PersonnelNo" => "501", "Name" => "ACHMAD ANDI SANTOSO"],
            ["PersonnelNo" => "502", "Name" => "DIDIK HARIYANTO"],
            ["PersonnelNo" => "503", "Name" => "IWAN SULIONO"],
            ["PersonnelNo" => "505", "Name" => "DHIKY FERDIYANTO"],
            ["PersonnelNo" => "506", "Name" => "R. HARIYANTO WAHYUDIONO"],
            ["PersonnelNo" => "507", "Name" => "M. BAGUS ASTAWAF"],
            ["PersonnelNo" => "508", "Name" => "ACMAD RIDUWAN"],
            ["PersonnelNo" => "509", "Name" => "AHMAD SUPRIADI"],
            ["PersonnelNo" => "510", "Name" => "SUNALAM"],
            ["PersonnelNo" => "511", "Name" => "DEBI SUSILO"],
            ["PersonnelNo" => "504", "Name" => "ANDRE KURNIANTO"],
            ["PersonnelNo" => "515", "Name" => "AGUNG SETYAWAN"],
            ["PersonnelNo" => "512", "Name" => "RIZA WIJAYA"],
            ["PersonnelNo" => "513", "Name" => "MUHAMMAD ROFIK"],
            ["PersonnelNo" => "514", "Name" => "AHMAD ABDUL AZIZ MUHAIMIN"],
            ["PersonnelNo" => "516", "Name" => "ACHMAD ZAINUL ARIFIN"],
            ["PersonnelNo" => "517", "Name" => "DENDYN DWI MA'ARUF"],
            ["PersonnelNo" => "518", "Name" => "MOCH. EFENDI"],
            ["PersonnelNo" => "519", "Name" => "SUCIPTO"],
            ["PersonnelNo" => "520", "Name" => "SUTRISNO"],
            ["PersonnelNo" => "21224494", "Name" => "IVAN HENDRI PRASETYO"],
            ["PersonnelNo" => "20125493", "Name" => "HENDRO SUTARTO"],
            ["PersonnelNo" => "521", "Name" => "BUDI PURWANTO"],
            ["PersonnelNo" => "522", "Name" => "IZAM MAULIDIL AHMAD"],
            ["PersonnelNo" => "523", "Name" => "YOGI FAHRUL TRIYANDA"],
            ["PersonnelNo" => "524", "Name" => "NANANG ISTANTO"],
            ["PersonnelNo" => "525", "Name" => "ALDI SENO AJI"],
            ["PersonnelNo" => "526", "Name" => "FERDINANTO AINUR ROHMAN"],
            ["PersonnelNo" => "527", "Name" => "TEDDY RAHMADANI FIQH MIENDZA"],
            ["PersonnelNo" => "528", "Name" => "MUHAMMAD AMINUDDIN"],
            ["PersonnelNo" => "529", "Name" => "ANIL ABIDIN"],
            ["PersonnelNo" => "530", "Name" => "ABDUL ROSYID"],
            ["PersonnelNo" => "531", "Name" => "ROHMAD JULIANTO"],
            ["PersonnelNo" => "532", "Name" => "MOCH. INDRA ARDIANSYAH"],
            ["PersonnelNo" => "533", "Name" => "MUHAMMAD IKHWAN"],
            ["PersonnelNo" => "534", "Name" => "YULI SUPRIANTO"],
            ["PersonnelNo" => "535", "Name" => "AGUNG WIDIYANTO"],
            ["PersonnelNo" => "536", "Name" => "RADITYA ENDRU WIJAYA"],
            ["PersonnelNo" => "537", "Name" => "AKHMAD FENDY PRADANA"],
            ["PersonnelNo" => "540", "Name" => "MUHAMMAD YUSUF"],
            ["PersonnelNo" => "541", "Name" => "MUHAMMAD IQBAL KHALIDY"],
            ["PersonnelNo" => "542", "Name" => "M. RYAN SYAH PUTRA"],
            ["PersonnelNo" => "544", "Name" => "SUHENDRIK HIDAYAT"],
            ["PersonnelNo" => "545", "Name" => "MUCHAMAD RIZKI"],
            ["PersonnelNo" => "543", "Name" => "QODAMU SHIDQIN"],
            ["PersonnelNo" => "546", "Name" => "MUHAMMAD YONGKY FERNANDO"],
            ["PersonnelNo" => "20225472", "Name" => "AGUS DWI PRASETYO"],
            ["PersonnelNo" => "20225538", "Name" => "ANNANTA SETIAWAN HARI PRAKOSO"],
            ["PersonnelNo" => "552", "Name" => "RAHMADONI FUAT BIMANTARA"],
            ["PersonnelNo" => "553", "Name" => "MOKHAMAD KHOZINATUL ASROR"],
            ["PersonnelNo" => "547", "Name" => "MUKMININ"],
            ["PersonnelNo" => "548", "Name" => "TRIANTO PRASETYO"],
            ["PersonnelNo" => "550", "Name" => "SAIFUL ARIFIN"],
            ["PersonnelNo" => "549", "Name" => "MOHAMMAD SIFAK"],
            ["PersonnelNo" => "551", "Name" => "RUMAWAN"],
            ["PersonnelNo" => "554", "Name" => "HANIF INDRIYANTO"],
            ["PersonnelNo" => "555", "Name" => "FAJAR DWI RAMADANI"],
            ["PersonnelNo" => "556", "Name" => "SYAHDAN HABIBILLAH SETYONO"],
            ["PersonnelNo" => "557", "Name" => "ANDRIANZAH ADI S"],
            ["PersonnelNo" => "559", "Name" => "AHMAD NUR SUHUFI"],
            ["PersonnelNo" => "560", "Name" => "MUHAMMAD SAMSUL HADI"],
            ["PersonnelNo" => "561", "Name" => "BENY RUDIANSYAH"],
            ["PersonnelNo" => "20225539", "Name" => "ARIFFANDI SASTYA INDRAJAYA"],
            ["PersonnelNo" => "20225562", "Name" => "RENANDHA LUTHFY AGUSTIA"],
            ["PersonnelNo" => "563", "Name" => "SUKISWANTO"],
            ["PersonnelNo" => "564", "Name" => "CHABIBULLOH"],
            ["PersonnelNo" => "565", "Name" => "IVAN ARI CANDRA"],
            ["PersonnelNo" => "566", "Name" => "MUSROFIK"],
            ["PersonnelNo" => "567", "Name" => "DODOT IWANDOYO"],
            ["PersonnelNo" => "568", "Name" => "DEDIK SULAIMAN"],
            ["PersonnelNo" => "569", "Name" => "SAMSUL HUDA"],
            ["PersonnelNo" => "20225558", "Name" => "GALATIONO VIANUS SANTO"],
            ["PersonnelNo" => "570", "Name" => "HADI SANTOSO"],
            ["PersonnelNo" => "571", "Name" => "SUGIADI"],
            ["PersonnelNo" => "572", "Name" => "RUDIANTO"],
            ["PersonnelNo" => "573", "Name" => "MOCHAMMAD ARIFUDIN HISBULLOH"],
            ["PersonnelNo" => "574", "Name" => "SYAIFUL ANWAR"],
            ["PersonnelNo" => "575", "Name" => "YOGA PRATAMA"],
            ["PersonnelNo" => "576", "Name" => "HERI SISWANTO"],
            ["PersonnelNo" => "578", "Name" => "FIRMAN ARIYANTO"],
            ["PersonnelNo" => "579", "Name" => "RUDIANTO"],
            ["PersonnelNo" => "580", "Name" => "NOVAN KEREN"],
            ["PersonnelNo" => "581", "Name" => "MUHAMMAD FATKUR ROKHMAN"],
            ["PersonnelNo" => "582", "Name" => "SULTONIL ADZIM"],
            ["PersonnelNo" => "583", "Name" => "MOCHAMAD FAUZI"],
            ["PersonnelNo" => "584", "Name" => "DWI HERI SUSANTO"],
            ["PersonnelNo" => "577", "Name" => "MOCHAMMAD ZAINUL ABIDIN"],
            ["PersonnelNo" => "585", "Name" => "HARI SUPRAYITNO"],
            ["PersonnelNo" => "586", "Name" => "SUPRAPTO"],
            ["PersonnelNo" => "587", "Name" => "FEBRI KRISTIAWAN"],
            ["PersonnelNo" => "588", "Name" => "ADAM NIRWANA"],
            ["PersonnelNo" => "589", "Name" => "MUCHAMMAD SULTON HIDAYATULLOH"],
            ["PersonnelNo" => "590", "Name" => "MOHAMAD NAMIRUL SAID"],
            ["PersonnelNo" => "591", "Name" => "MUHAMMAD VERDIAN WILDAN MA'RUF"],
            ["PersonnelNo" => "592", "Name" => "MUHAMMAD SULTONIL ADIM"],
            ["PersonnelNo" => "593", "Name" => "HENDI ASHARI"],
            ["PersonnelNo" => "594", "Name" => "ARIF HARIANTO"],
            ["PersonnelNo" => "595", "Name" => "NOVAN SUPRIADI"],
            ["PersonnelNo" => "596", "Name" => "IMAM SUBEKTI"],
            ["PersonnelNo" => "597", "Name" => "RENDY PANDU WINATA"],
            ["PersonnelNo" => "20325598", "Name" => "DAMARIS TANOJO"],
            ["PersonnelNo" => "601", "Name" => "AGUS SUBIYANTO"],
            ["PersonnelNo" => "600", "Name" => "FAIZAL HIDAYAH"],
            ["PersonnelNo" => "602", "Name" => "MASULAH WAHYU AGUNG PRASTYO"],
            ["PersonnelNo" => "603", "Name" => "AGUS SUPRAYITNO"],
            ["PersonnelNo" => "604", "Name" => "ADITYA KELVIN ADRIYANTO"],
            ["PersonnelNo" => "605", "Name" => "MOH. KHUSAENI"],
            // Tambahkan data lainnya...
        ];

        foreach ($data as $user) {
            DB::table('employees')->insert([
                'PersonnelNo' => $user['PersonnelNo'],
                'Name' => $user['Name'],
            ]);
        }
    }
}
