<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $data = [
        //     // ["PersonnelNo" => "12345", "name" => "ADMIN", "password" => "12345"],
        //     // ["PersonnelNo" => "123456", "name" => "KARYAWAN", "password" => "123456"],
        //     ["PersonnelNo" => "421", "name" => "DYAH AJENG PUSPA YUNITA", "password" => "421"],
        //     // Tambahkan data lainnya...
        // ];

        $data = [
            // ["PersonnelNo" => "39", "name" => "MARYUTI", "password" => "39"],
            // ["PersonnelNo" => "36", "name" => "MUHAMMAD AINUR ROSYIDDIN", "password" => "36"],
            // ["PersonnelNo" => "61", "name" => "SUCI ANINGSIH", "password" => "61"],
            // ["PersonnelNo" => "48", "name" => "NURMA MERDIANA", "password" => "48"],
            // ["PersonnelNo" => "8100", "name" => "ERIANDI SURBAKTI", "password" => "8100"],
            // ["PersonnelNo" => "8", "name" => "ANDHAN LUPI WIRENI", "password" => "8"],
            // ["PersonnelNo" => "41", "name" => "MEILY HANDAYANI", "password" => "41"],
            // ["PersonnelNo" => "45", "name" => "NOVITA DWI WAHYUNI", "password" => "45"],
            // ["PersonnelNo" => "23", "name" => "FLORENSIA RETHA BUDIANTY", "password" => "23"],
            // ["PersonnelNo" => "22", "name" => "FAUZI ALVIANTO", "password" => "22"],
            // ["PersonnelNo" => "74", "name" => "YASHINTA MAHARANI HARIYADI", "password" => "74"],
            // ["PersonnelNo" => "52", "name" => "RATNA TUSI WULANDARI", "password" => "52"],
            // ["PersonnelNo" => "59", "name" => "SEPTIYAN YOGI BAHTIAR", "password" => "59"],
            // ["PersonnelNo" => "16", "name" => "DINDA SUKMAWATI", "password" => "16"],
            // ["PersonnelNo" => "55", "name" => "RISTIANTO", "password" => "55"],
            // ["PersonnelNo" => "12", "name" => "CAHYA RISKITA", "password" => "12"],
            // ["PersonnelNo" => "7", "name" => "ALVYANTI VIDIA FEBRIANI", "password" => "7"],
            // ["PersonnelNo" => "67", "name" => "SUSIO MUDJIONO", "password" => "67"],
            // ["PersonnelNo" => "71", "name" => "WAHYUDI", "password" => "71"],
            // ["PersonnelNo" => "69", "name" => "UMAR NURBANA", "password" => "69"],
            // ["PersonnelNo" => "166", "name" => "SINTA MAHARANI", "password" => "166"],
            // ["PersonnelNo" => "58", "name" => "SALSABILA AISYAH BUNDARTI", "password" => "58"],
            // ["PersonnelNo" => "1", "name" => "MUCHTAR LUTHFI MALIK AL AZHAR", "password" => "1"],
            // ["PersonnelNo" => "169", "name" => "ABIM SURYA MAHENDRA", "password" => "169"],
            // ["PersonnelNo" => "9151", "name" => "ADE FIKI JULIANDA", "password" => "9151"],
            // ["PersonnelNo" => "9007", "name" => "Ali Imron Rosyidi", "password" => "9007"],
            // ["PersonnelNo" => "106", "name" => "ROCHMANI", "password" => "106"],
            // ["PersonnelNo" => "171", "name" => "ANDRE AGASI NOR RIHI", "password" => "171"],
            // ["PersonnelNo" => "9010", "name" => "ANIS PUJI SARINI", "password" => "9010"],
            // ["PersonnelNo" => "9011", "name" => "ANITA NUR FADILA", "password" => "9011"],
            // ["PersonnelNo" => "182", "name" => "ARIEL SEPTIAN RIVELLINO", "password" => "182"],
            // ["PersonnelNo" => "9113", "name" => "AYU NUR RASTIN", "password" => "9113"],
            // ["PersonnelNo" => "175", "name" => "CHEVA ANIN INDRIYANI", "password" => "175"],
            // ["PersonnelNo" => "9116", "name" => "DELLA DAMAYANTI", "password" => "9116"],
            // ["PersonnelNo" => "78", "name" => "DEDI IRAWAN", "password" => "78"],
            // ["PersonnelNo" => "9117", "name" => "Dodik Kurniawan", "password" => "9117"],
            // ["PersonnelNo" => "9123", "name" => "ERLI KUSTANTI", "password" => "9123"],
            // ["PersonnelNo" => "170", "name" => "FERI WIBOWO TRI PRASTIYO", "password" => "170"],
            // ["PersonnelNo" => "113", "name" => "WIJAYA KUSUMA", "password" => "113"],
            // ["PersonnelNo" => "172", "name" => "HERI TEGUH ARIFIANTO", "password" => "172"],
            // ["PersonnelNo" => "9153", "name" => "Iana Hanifah", "password" => "9153"],
            // ["PersonnelNo" => "9129", "name" => "IMROATUN LADHIFAH", "password" => "9129"],
            // ["PersonnelNo" => "115", "name" => "NANDA GITA SHAFIRA", "password" => "115"],
            // ["PersonnelNo" => "161", "name" => "INDRA KURNIAWAN PRASETYO", "password" => "161"],
            // ["PersonnelNo" => "9132", "name" => "JOKO MARTOPO", "password" => "9132"],
            // ["PersonnelNo" => "150", "name" => "MAGDALENA DAMAI PRAMUDIA", "password" => "150"],
            // ["PersonnelNo" => "9137", "name" => "MAIMANAH", "password" => "9137"],
            // ["PersonnelNo" => "9138", "name" => "MEGA PUTRI LIA ANJANI", "password" => "9138"],
            // ["PersonnelNo" => "213", "name" => "MOHAMMAD IQBAL SYAIFUDIN", "password" => "213"],
            // ["PersonnelNo" => "92", "name" => "SITI SOEDARMI", "password" => "92"],
            // ["PersonnelNo" => "9052", "name" => "NADYA ANISAFITRI", "password" => "9052"],
            // ["PersonnelNo" => "9146", "name" => "NASRIYA", "password" => "9146"],
            // ["PersonnelNo" => "127", "name" => "HERNOWO YUDHA PRABOWO", "password" => "127"],
            // ["PersonnelNo" => "9148", "name" => "PALUPI HANDITASARI", "password" => "9148"],
            // ["PersonnelNo" => "95", "name" => "SLAMET PRIYANTO", "password" => "95"],
            // ["PersonnelNo" => "98", "name" => "MUHAMMAD AFIFAN", "password" => "98"],
            // ["PersonnelNo" => "9149", "name" => "RATNA PUJIATI", "password" => "9149"],
            // ["PersonnelNo" => "9062", "name" => "RITA BINA WATI", "password" => "9062"],
            // ["PersonnelNo" => "9063", "name" => "RIZKI DWI WITANTO", "password" => "9063"],
            // ["PersonnelNo" => "159", "name" => "RUSWANTO", "password" => "159"],
            // ["PersonnelNo" => "155", "name" => "SIGIT BUDIANTO", "password" => "155"],
            // ["PersonnelNo" => "9068", "name" => "SITI ALFIYAH", "password" => "9068"],
            // ["PersonnelNo" => "9150", "name" => "STEFANI SELVIA SARI", "password" => "9150"],
            // ["PersonnelNo" => "163", "name" => "SULIANTO", "password" => "163"],
            // ["PersonnelNo" => "129", "name" => "BENY RATNO", "password" => "129"],
            // ["PersonnelNo" => "9074", "name" => "SUTIASE", "password" => "9074"],
            // ["PersonnelNo" => "130", "name" => "SUBEKI PURNOMO", "password" => "130"],
            // ["PersonnelNo" => "5007", "name" => "HAYUN RATNA PUSPITASARI", "password" => "5007"],
            // ["PersonnelNo" => "5005", "name" => "DITA NAUMI AYU ERLIANA", "password" => "5005"],
            // ["PersonnelNo" => "5009", "name" => "NOVI ENDAH PUSPITASARI", "password" => "5009"],
            // ["PersonnelNo" => "9081", "name" => "URIFAH", "password" => "9081"],
            // ["PersonnelNo" => "9155", "name" => "VIVI NOVITASARI TRI WAHYUNINGTYAS", "password" => "9155"],
            // ["PersonnelNo" => "8068", "name" => "PIPIN FITRIYANTO", "password" => "8068"],
            // ["PersonnelNo" => "8045", "name" => "HENDRA SETIAWAN", "password" => "8045"],
            // ["PersonnelNo" => "8069", "name" => "PUTU MAHENDRA", "password" => "8069"],
            // ["PersonnelNo" => "8052", "name" => "IRVAN", "password" => "8052"],
            // ["PersonnelNo" => "8013", "name" => "Anisa Moha", "password" => "8013"],
            // ["PersonnelNo" => "8078", "name" => "SISKA", "password" => "8078"],
            // ["PersonnelNo" => "8016", "name" => "Ayu Wandari", "password" => "8016"],
            // ["PersonnelNo" => "8044", "name" => "HENDRA PALEMBANGAN", "password" => "8044"],
            // ["PersonnelNo" => "8060", "name" => "MUCHAMMAD FAISOL", "password" => "8060"],
            // ["PersonnelNo" => "8074", "name" => "ROSSI BASTIYAR", "password" => "8074"],
            // ["PersonnelNo" => "8019", "name" => "CHRISTI SUSIE MURNIATY", "password" => "8019"],
            // ["PersonnelNo" => "8062", "name" => "MUHAMMAD AZHARI ABDI", "password" => "8062"],
            // ["PersonnelNo" => "8063", "name" => "NELSON KIAMANI", "password" => "8063"],
            // ["PersonnelNo" => "9084", "name" => "YENI DWI PURBA", "password" => "9084"],
            // ["PersonnelNo" => "8057", "name" => "MEI", "password" => "8057"],
            // ["PersonnelNo" => "8080", "name" => "SITI ROHANI", "password" => "8080"],
            // ["PersonnelNo" => "8022", "name" => "DEDI KAIMUDDIN", "password" => "8022"],
            // ["PersonnelNo" => "102", "name" => "WINDU HANDAYANI", "password" => "102"],
            // ["PersonnelNo" => "8072", "name" => "RISKA LANDRIANI", "password" => "8072"],
            // ["PersonnelNo" => "8041", "name" => "FRIDA ANDINA", "password" => "8041"],
            // ["PersonnelNo" => "8038", "name" => "FAHRUL SEPTIAN AMIN", "password" => "8038"],
            // ["PersonnelNo" => "8065", "name" => "NIRMALA", "password" => "8065"],
            // ["PersonnelNo" => "5016", "name" => "NURHAEPA", "password" => "5016"],
            // ["PersonnelNo" => "8051", "name" => "INDRI RESPATI HAYUNINGTYAS", "password" => "8051"],
            // ["PersonnelNo" => "8061", "name" => "MUHAMMAD AGUNG HIDAYAT", "password" => "8061"],
            // ["PersonnelNo" => "8073", "name" => "ROFIUDIN ANDRIANTO", "password" => "8073"],
            // ["PersonnelNo" => "8017", "name" => "BAYU WIJAYA", "password" => "8017"],
            // ["PersonnelNo" => "8071", "name" => "Rika Meilinda Dwi L", "password" => "8071"],
            // ["PersonnelNo" => "70013", "name" => "WAHYU ARIF SAPUTRA", "password" => "70013"],
            // ["PersonnelNo" => "8055", "name" => "KOMANG DEDDY MEGA SUDARMAWAN", "password" => "8055"],
            // ["PersonnelNo" => "8028", "name" => "DIAN TRISNA PUTRI", "password" => "8028"],
            // ["PersonnelNo" => "8033", "name" => "EKI ERVANDI", "password" => "8033"],
            // ["PersonnelNo" => "70003", "name" => "AFANDI", "password" => "70003"],
            // ["PersonnelNo" => "8002", "name" => "ADE DWI JAYANTI", "password" => "8002"],
            // ["PersonnelNo" => "8050", "name" => "Ika Siwi Suprapti", "password" => "8050"],
            // ["PersonnelNo" => "70005", "name" => "DWI FEBRIANSYAH", "password" => "70005"],
            // ["PersonnelNo" => "5001", "name" => "FATIMATUS ZAHROH", "password" => "5001"],
            // ["PersonnelNo" => "8042", "name" => "HABSI ARDIANSYAH", "password" => "8042"],
            // ["PersonnelNo" => "8025", "name" => "DERIANTO RAHMAN", "password" => "8025"],
            // ["PersonnelNo" => "8046", "name" => "HENDRI ISMANTO", "password" => "8046"],
            // ["PersonnelNo" => "8015", "name" => "ARI WIBOWO", "password" => "8015"],
            // ["PersonnelNo" => "8031", "name" => "DWI KHOIRIYAH", "password" => "8031"],
            // ["PersonnelNo" => "8035", "name" => "Elly Sumarni Wawi", "password" => "8035"],
            // ["PersonnelNo" => "8011", "name" => "ANGGA PRAYOGA", "password" => "8011"],
            // ["PersonnelNo" => "70007", "name" => "SUGENG", "password" => "70007"],
            // ["PersonnelNo" => "8037", "name" => "FADILA LAGAUTU", "password" => "8037"],
            // ["PersonnelNo" => "8053", "name" => "JEPRI KARTAGUNA", "password" => "8053"],
            // ["PersonnelNo" => "8054", "name" => "Jon Fereddy Hutabarat", "password" => "8054"],
            // ["PersonnelNo" => "5013", "name" => "WIWIN", "password" => "5013"],
            // ["PersonnelNo" => "148", "name" => "DINIA RAMADHAN NINGRUM HAS", "password" => "148"],
            // ["PersonnelNo" => "165", "name" => "ALDO PRAVISTA GABRIEL", "password" => "165"],
            // ["PersonnelNo" => "139", "name" => "DEBORA INGGRID KARUNIA", "password" => "139"],
            // ["PersonnelNo" => "185", "name" => "MARSHELIA TANNUS", "password" => "185"],
            // ["PersonnelNo" => "146", "name" => "YOHANA ALICIA", "password" => "146"],
            // ["PersonnelNo" => "138", "name" => "MOCH DEFRI RIZA ISTIANTO", "password" => "138"],
            // ["PersonnelNo" => "181", "name" => "ENDANG YULVIANTI", "password" => "181"],
            // ["PersonnelNo" => "173", "name" => "SUPRIYANTO", "password" => "173"],
            // ["PersonnelNo" => "176", "name" => "RIZKI ALDILLA", "password" => "176"],
            // ["PersonnelNo" => "174", "name" => "WARAS SETIAWAN", "password" => "174"],
            // ["PersonnelNo" => "180", "name" => "SITI JULAIKHAH", "password" => "180"],
            // ["PersonnelNo" => "160", "name" => "LEMUEL OKTAVIANUS DARMAWAN", "password" => "160"],
            // ["PersonnelNo" => "157", "name" => "M. NUR AROSI", "password" => "157"],
            // ["PersonnelNo" => "136", "name" => "MOKH RIZAL", "password" => "136"],
            // ["PersonnelNo" => "8083", "name" => "SUHARYATIK", "password" => "8083"],
            // ["PersonnelNo" => "8026", "name" => "DEVISA ISKANDAR", "password" => "8026"],
            // ["PersonnelNo" => "8890", "name" => "IFAN FAHMI", "password" => "8890"],
            // ["PersonnelNo" => "8891", "name" => "IRMA ERVIANA", "password" => "8891"],
            // ["PersonnelNo" => "8892", "name" => "MESI ARSITA", "password" => "8892"],
            // ["PersonnelNo" => "8893", "name" => "ANNISA REGITA", "password" => "8893"],
            // ["PersonnelNo" => "8895", "name" => "PUTRI LISDA PERMATA SARI", "password" => "8895"],
            // ["PersonnelNo" => "8896", "name" => "HARRIS AGUNG WICAKSONO", "password" => "8896"],
            // ["PersonnelNo" => "8087", "name" => "WIDIANTO", "password" => "8087"],
            // ["PersonnelNo" => "8027", "name" => "DHANI IKHSAN DERMAWAN", "password" => "8027"],
            // ["PersonnelNo" => "8897", "name" => "ASRI AGUNG", "password" => "8897"],
            // ["PersonnelNo" => "8007", "name" => "AMELIA TANTO", "password" => "8007"],
            // ["PersonnelNo" => "8090", "name" => "YOHANES BILLY THERYUZ FAREZA BARENS", "password" => "8090"],
            // ["PersonnelNo" => "8112", "name" => "PARLUHUTAN RAMBE", "password" => "8112"],
            // ["PersonnelNo" => "8012", "name" => "ANGGIANA NOVITASARI", "password" => "8012"],
            // ["PersonnelNo" => "8034", "name" => "ELEANOR FERDINAND VALENTINO", "password" => "8034"],
            // ["PersonnelNo" => "192", "name" => "EUNIKE RIAHTA TARIGAN", "password" => "192"],
            // ["PersonnelNo" => "190", "name" => "DWI JULIA BISMAWATI", "password" => "190"],
            // ["PersonnelNo" => "9006", "name" => "MUHAMMAD ALDI ZAKARIA", "password" => "9006"],
            // ["PersonnelNo" => "9045", "name" => "MOHAMMAD FERRY ARDIANSYAH", "password" => "9045"],
            // ["PersonnelNo" => "9053", "name" => "NASIFUDIN AKBAR", "password" => "9053"],
            // ["PersonnelNo" => "9064", "name" => "SAFI ANI RAHAYU", "password" => "9064"],
            // ["PersonnelNo" => "9066", "name" => "SANDI ANTI NINGTYAS", "password" => "9066"],
            // ["PersonnelNo" => "9067", "name" => "SINTA AYU K", "password" => "9067"],
            // ["PersonnelNo" => "9073", "name" => "SULAMI", "password" => "9073"],
            // ["PersonnelNo" => "193", "name" => "TIVANA DEWI FEBRIANY", "password" => "193"],
            // ["PersonnelNo" => "9112", "name" => "TONI HIMAWAN", "password" => "9112"],
            // ["PersonnelNo" => "8004", "name" => "AGUS NILAWATI", "password" => "8004"],
            // ["PersonnelNo" => "8009", "name" => "ANDRI YANA", "password" => "8009"],
            // ["PersonnelNo" => "8010", "name" => "ANGGA KURNIAWAN", "password" => "8010"],
            // ["PersonnelNo" => "8020", "name" => "DANI IRAWAN", "password" => "8020"],
            // ["PersonnelNo" => "70010", "name" => "DENI HARIADI", "password" => "70010"],
            // ["PersonnelNo" => "5008", "name" => "HETTY FITRIANA", "password" => "5008"],
            // ["PersonnelNo" => "8084", "name" => "TAUFIK AMRI", "password" => "8084"],
            // ["PersonnelNo" => "9108", "name" => "TIFLATUS SHULKHA", "password" => "9108"],
            // ["PersonnelNo" => "9106", "name" => "SOFA YUNIAR KURNIASARI", "password" => "9106"],
            // ["PersonnelNo" => "9154", "name" => "SITI NUR ASIA", "password" => "9154"],
            // ["PersonnelNo" => "9105", "name" => "SHOFIYAH NUGRAHA SALSABILA", "password" => "9105"],
            // ["PersonnelNo" => "9104", "name" => "RETNO KRISDIANTO", "password" => "9104"],
            // ["PersonnelNo" => "9103", "name" => "NUR HIDAYATI", "password" => "9103"],
            // ["PersonnelNo" => "9102", "name" => "NOVIA DWI SULISTIYOWATI", "password" => "9102"],
            // ["PersonnelNo" => "9101", "name" => "NENNY NUR A", "password" => "9101"],
            // ["PersonnelNo" => "5006", "name" => "FITRI RAHMAWATI", "password" => "5006"],
            // ["PersonnelNo" => "9094", "name" => "FINA PRINDIANI", "password" => "9094"],
            // ["PersonnelNo" => "9092", "name" => "EKA NUR FAUZIAH", "password" => "9092"],
            // ["PersonnelNo" => "9089", "name" => "BAIDAH", "password" => "9089"],
            // ["PersonnelNo" => "9087", "name" => "ANISYA NURUL CINTYA ZAHRA", "password" => "9087"],
            // ["PersonnelNo" => "9085", "name" => "ANIFFA ROSSIANA", "password" => "9085"],
            // ["PersonnelNo" => "9156", "name" => "ULVIA", "password" => "9156"],
            // ["PersonnelNo" => "194", "name" => "FAJAR NUGRAHA", "password" => "194"],
            // ["PersonnelNo" => "8113", "name" => "AKBAR", "password" => "8113"],
            // ["PersonnelNo" => "8115", "name" => "MAYA SARI", "password" => "8115"],
            // ["PersonnelNo" => "8116", "name" => "RYAN HIDAYAT", "password" => "8116"],
            // ["PersonnelNo" => "8117", "name" => "KRISTIANDI", "password" => "8117"],
            // ["PersonnelNo" => "8108", "name" => "TRI HARIONO", "password" => "8108"],
            // ["PersonnelNo" => "8118", "name" => "RUDI FIRDAUS", "password" => "8118"],
            // ["PersonnelNo" => "8109", "name" => "MUH.NASYIR", "password" => "8109"],
            // ["PersonnelNo" => "198", "name" => "VERO INDRA MARDANY", "password" => "198"],
            // ["PersonnelNo" => "5026", "name" => "MAWAR WULANDARI", "password" => "5026"],
            // ["PersonnelNo" => "5003", "name" => "KISI ANJALI", "password" => "5003"],
            // ["PersonnelNo" => "135", "name" => "MUHAMAD SARIONO", "password" => "135"],
            // ["PersonnelNo" => "199", "name" => "FEBIANANTO RIZKY ASTIA PUTRA", "password" => "199"],
            // ["PersonnelNo" => "200", "name" => "M. IQFAN NURINDRA", "password" => "200"],
            // ["PersonnelNo" => "70011", "name" => "SUDIRO", "password" => "70011"],
            // ["PersonnelNo" => "8122", "name" => "HARDIAN SYAHPUTRA", "password" => "8122"],
            // ["PersonnelNo" => "8123", "name" => "RUDI SUHENDRA", "password" => "8123"],
            // ["PersonnelNo" => "9158", "name" => "MUHAMMAD AFIFAN REMBUK", "password" => "9158"],
            // ["PersonnelNo" => "202", "name" => "NOFANDI PRASETYO", "password" => "202"],
            // ["PersonnelNo" => "9160", "name" => "AGUS HARIONO", "password" => "9160"],
            // ["PersonnelNo" => "9161", "name" => "MOCH. DANNY AMANNULLAH", "password" => "9161"],
            // ["PersonnelNo" => "204", "name" => "HENDRA ADI SURYANTO", "password" => "204"],
            // ["PersonnelNo" => "203", "name" => "MOHAMMAD TRI BAHANA LAZAURDI", "password" => "203"],
            // ["PersonnelNo" => "207", "name" => "NATALIA PUSPITA SARI", "password" => "207"],
            // ["PersonnelNo" => "9163", "name" => "RE DYANSYAH PUTRA", "password" => "9163"],
            // ["PersonnelNo" => "8134", "name" => "DEWI ZULAIKHAH", "password" => "8134"],
            // ["PersonnelNo" => "8129", "name" => "LOLA JOHN FEBYSCA", "password" => "8129"],
            // ["PersonnelNo" => "8137", "name" => "MARSELINA", "password" => "8137"],
            // ["PersonnelNo" => "8125", "name" => "MUH. NASYIR", "password" => "8125"],
            // ["PersonnelNo" => "8131", "name" => "NELWINDA MASHANAFI", "password" => "8131"],
            // ["PersonnelNo" => "8135", "name" => "KRISTIANDI", "password" => "8135"],
            // ["PersonnelNo" => "8133", "name" => "MANSYUR SULAIMAN", "password" => "8133"],
            // ["PersonnelNo" => "8128", "name" => "M. BUHARI IRVAN", "password" => "8128"],
            // ["PersonnelNo" => "8136", "name" => "PIPIT FITRIWANI KOTO", "password" => "8136"],
            // ["PersonnelNo" => "8124", "name" => "ASTRIANDANY IDEA KARSA", "password" => "8124"],
            // ["PersonnelNo" => "8130", "name" => "LIA FATHURAHMAH", "password" => "8130"],
            // ["PersonnelNo" => "8138", "name" => "IDAYANTI", "password" => "8138"],
            // ["PersonnelNo" => "8126", "name" => "PRISKILA CLAUDIA YUNI RAMBA", "password" => "8126"],
            // ["PersonnelNo" => "70014", "name" => "AWALUDIN  MULYONO", "password" => "70014"],
            // ["PersonnelNo" => "70015", "name" => "HUSEN MAULANA", "password" => "70015"],
            // ["PersonnelNo" => "8139", "name" => "RATNI L HALINDIS", "password" => "8139"],
            // ["PersonnelNo" => "5014", "name" => "EKA NUR SAFITRIH", "password" => "5014"],
            // ["PersonnelNo" => "8146", "name" => "ISNAWATI", "password" => "8146"],
            // ["PersonnelNo" => "8145", "name" => "ELPINA PIDIAWATI", "password" => "8145"],
            // ["PersonnelNo" => "8144", "name" => "SERLI SEPTAYUDA", "password" => "8144"],
            // ["PersonnelNo" => "8143", "name" => "HELTON SUEJARWO", "password" => "8143"],
            // ["PersonnelNo" => "8142", "name" => "IKA WIDIYANINGSIH", "password" => "8142"],
            // ["PersonnelNo" => "5019", "name" => "ULFA AMALIA NURJANAH", "password" => "5019"],
            // ["PersonnelNo" => "209", "name" => "AGIL DANANG PRABOWO", "password" => "209"],
            // ["PersonnelNo" => "9996", "name" => "YENI IIS SHOLIKHAH", "password" => "9996"],
            // ["PersonnelNo" => "70016", "name" => "II HIDAYAT", "password" => "70016"],
            // ["PersonnelNo" => "212", "name" => "FAHMI ULA", "password" => "212"],
            // ["PersonnelNo" => "9162", "name" => "ALFIAN FATKHUR ROKHIM", "password" => "9162"],
            // ["PersonnelNo" => "9164", "name" => "TRIO RAMADHANI", "password" => "9164"],
            // ["PersonnelNo" => "214", "name" => "ACHMAD REZAL ELI EFENDY", "password" => "214"],
            // ["PersonnelNo" => "8148", "name" => "APRILIA DARASMANTI", "password" => "8148"],
            // ["PersonnelNo" => "215", "name" => "EKO YUDI PURWANTO", "password" => "215"],
            // ["PersonnelNo" => "218", "name" => "KUDORI", "password" => "218"],
            // ["PersonnelNo" => "219", "name" => "LUQMAN HAKIM", "password" => "219"],
            // ["PersonnelNo" => "70019", "name" => "FERA MARDIANA", "password" => "70019"],
            // ["PersonnelNo" => "70017", "name" => "SITI AMINAH(JKT)", "password" => "70017"],
            // ["PersonnelNo" => "220", "name" => "DEDI SETYAWAN", "password" => "220"],
            // ["PersonnelNo" => "9166", "name" => "ANGGI ARDIANSYAH", "password" => "9166"],
            // ["PersonnelNo" => "8150", "name" => "ARISWANTO", "password" => "8150"],
            // ["PersonnelNo" => "5020", "name" => "SEPTA OKTARIA", "password" => "5020"],
            // ["PersonnelNo" => "8152", "name" => "FAIREL DAME", "password" => "8152"],
            // ["PersonnelNo" => "9167", "name" => "BELA RIZALATUL CHANIFAH", "password" => "9167"],
            // ["PersonnelNo" => "9168", "name" => "MUHAMMAD BASHORI ILHAM", "password" => "9168"],
            // ["PersonnelNo" => "9169", "name" => "HERIBERTUS RICKY NOVANDA", "password" => "9169"],
            // ["PersonnelNo" => "9170", "name" => "RANGGA IRGIWAHYU FAHREZI", "password" => "9170"],
            // ["PersonnelNo" => "9171", "name" => "WIDIA NANDA FAJAR", "password" => "9171"],
            // ["PersonnelNo" => "9172", "name" => "AYU RAHMAWATI", "password" => "9172"],
            // ["PersonnelNo" => "9173", "name" => "KARINA ROEMI KHAFIFAH", "password" => "9173"],
            // ["PersonnelNo" => "9174", "name" => "CHUSNUL WULANDARI", "password" => "9174"],
            // ["PersonnelNo" => "9175", "name" => "INNE YULIA NUR FITRIASYARI", "password" => "9175"],
            // ["PersonnelNo" => "9176", "name" => "DINDA RIKA UMI FATONA", "password" => "9176"],
            // ["PersonnelNo" => "70018", "name" => "MAHDI", "password" => "70018"],
            // ["PersonnelNo" => "5025", "name" => "YUAN APRILLIA", "password" => "5025"],
            // ["PersonnelNo" => "5017", "name" => "SUTMA VAN GOBEL", "password" => "5017"],
            // ["PersonnelNo" => "222", "name" => "IMAM MUSLIM", "password" => "222"],
            // ["PersonnelNo" => "8158", "name" => "MAYASARI", "password" => "8158"],
            // ["PersonnelNo" => "5018", "name" => "RIANTY DALENO", "password" => "5018"],
            // ["PersonnelNo" => "70020", "name" => "TRIWULAN AGUSTIN", "password" => "70020"],
            // ["PersonnelNo" => "202108", "name" => "MUHAMMAD ANDI WIJAYA", "password" => "202108"],
            // ["PersonnelNo" => "202107", "name" => "ILHAM BAGUS PRADANA", "password" => "202107"],
            // ["PersonnelNo" => "70021", "name" => "EKO FRIBUNA", "password" => "70021"],
            // ["PersonnelNo" => "5021", "name" => "FIKI OCTAVIA DEWI", "password" => "5021"],
            // ["PersonnelNo" => "5022", "name" => "REMBULAN NUR SUKARMI", "password" => "5022"],
            // ["PersonnelNo" => "202106", "name" => "AYUB EKO HARI SETYAWAN", "password" => "202106"],
            // ["PersonnelNo" => "5023", "name" => "YUNIA RISTA MANDAK", "password" => "5023"],
            // ["PersonnelNo" => "202105", "name" => "EVA AMALIYA", "password" => "202105"],
            // ["PersonnelNo" => "224", "name" => "TITIS SARI DWI SEPTEVY", "password" => "224"],
            // ["PersonnelNo" => "5024", "name" => "ELLYSDA SAGITA DOSIOFA", "password" => "5024"],
            // ["PersonnelNo" => "9177", "name" => "SULUNG BACHTIAR", "password" => "9177"],
            // ["PersonnelNo" => "9178", "name" => "APRILIA DWI KURNIAWATI", "password" => "9178"],
            // ["PersonnelNo" => "9180", "name" => "GABRIELLE LORENZA", "password" => "9180"],
            // ["PersonnelNo" => "9181", "name" => "VELLY ANGGRAENI", "password" => "9181"],
            // ["PersonnelNo" => "9182", "name" => "MAHMUDAH", "password" => "9182"],
            // ["PersonnelNo" => "9183", "name" => "SITI MUSA ADAH", "password" => "9183"],
            // ["PersonnelNo" => "9184", "name" => "YENNY SRI WAHYUNI", "password" => "9184"],
            // ["PersonnelNo" => "9185", "name" => "NISMAQUL UMMA", "password" => "9185"],
            // ["PersonnelNo" => "9186", "name" => "TITIN HERMAYANTI", "password" => "9186"],
            // ["PersonnelNo" => "9187", "name" => "AYU KURNIA FEBRI OLOWATI", "password" => "9187"],
            // ["PersonnelNo" => "9188", "name" => "NOVIA NUR ROHMA", "password" => "9188"],
            // ["PersonnelNo" => "9189", "name" => "DINDA SAFIRA AZZAHRO", "password" => "9189"],
            // ["PersonnelNo" => "9191", "name" => "FENI RAHMAWATI AGUSTIN", "password" => "9191"],
            // ["PersonnelNo" => "9193", "name" => "DWI HARYANTO", "password" => "9193"],
            // ["PersonnelNo" => "9194", "name" => "AULIA FERUCA KUMALA", "password" => "9194"],
            // ["PersonnelNo" => "225", "name" => "INDRA RIZKY HALIM PRATAMA", "password" => "225"],
            // ["PersonnelNo" => "5027", "name" => "MAULIDAH", "password" => "5027"],
            // ["PersonnelNo" => "8898", "name" => "AMELLIA NURFAIDA", "password" => "8898"],
            // ["PersonnelNo" => "9990", "name" => "WULAN MAHARDIKA", "password" => "9990"],
            // ["PersonnelNo" => "9991", "name" => "SURIANI DJAFAR", "password" => "9991"],
            // ["PersonnelNo" => "9995", "name" => "MUHAMMAD VIJAY", "password" => "9995"],
            // ["PersonnelNo" => "9993", "name" => "DORA PEBRI LIANTY", "password" => "9993"],
            // ["PersonnelNo" => "9994", "name" => "FENO TRIADI", "password" => "9994"],
            // ["PersonnelNo" => "227", "name" => "ACHMAD DENDY KURNIAWAN", "password" => "227"],
            // ["PersonnelNo" => "5028", "name" => "MITA BONITA", "password" => "5028"],
            // ["PersonnelNo" => "9197", "name" => "TRIZKA NURMALA SARI", "password" => "9197"],
            // ["PersonnelNo" => "9198", "name" => "YOSI SUTINAR WULANDARI", "password" => "9198"],
            // ["PersonnelNo" => "9200", "name" => "SITTA MAULIYA PUTRI", "password" => "9200"],
            // ["PersonnelNo" => "9201", "name" => "DINA NOVITA SARI", "password" => "9201"],
            // ["PersonnelNo" => "9202", "name" => "YANTI", "password" => "9202"],
            // ["PersonnelNo" => "9203", "name" => "SAMSUL ISWAHYUDI", "password" => "9203"],
            // ["PersonnelNo" => "9204", "name" => "HANIFAH ELYUCI RAMADANI", "password" => "9204"],
            // ["PersonnelNo" => "9205", "name" => "RISA SALSA BELLA FIRDA", "password" => "9205"],
            // ["PersonnelNo" => "229", "name" => "VINA ABRIAMNIE", "password" => "229"],
            // ["PersonnelNo" => "9207", "name" => "YUSRIL ISYAMA HENDRA", "password" => "9207"],
            // ["PersonnelNo" => "5029", "name" => "INDAR SUCIANTI", "password" => "5029"],
            // ["PersonnelNo" => "5030", "name" => "OLIVIA LAIHAD", "password" => "5030"],
            // ["PersonnelNo" => "233", "name" => "YUDI PRASETYO", "password" => "233"],
            // ["PersonnelNo" => "9208", "name" => "ARNANDO HADI WIRANATA", "password" => "9208"],
            // ["PersonnelNo" => "9209", "name" => "ILYAS MARDIYANTO", "password" => "9209"],
            // ["PersonnelNo" => "8181", "name" => "DAVID NUGROHO TRI", "password" => "8181"],
            // ["PersonnelNo" => "9998", "name" => "MOHAMAD FAIZAL", "password" => "9998"],
            // ["PersonnelNo" => "9210", "name" => "SRI MARTININGSIH", "password" => "9210"],
            // ["PersonnelNo" => "234", "name" => "PUTRI SEPTIANITA RACHMAWATI", "password" => "234"],
            // ["PersonnelNo" => "9215", "name" => "ERVINA AGUSTIN", "password" => "9215"],
            // ["PersonnelNo" => "9213", "name" => "YUNIA ROSIDAH", "password" => "9213"],
            // ["PersonnelNo" => "9214", "name" => "SINTYA DWI AGUSTIN", "password" => "9214"],
            // ["PersonnelNo" => "70022", "name" => "LUTHFI ADITYA  NUGRAHA", "password" => "70022"],
            // ["PersonnelNo" => "70023", "name" => "EKA CIPTAWIJAYA", "password" => "70023"],
            // ["PersonnelNo" => "7024", "name" => "BAYU PURNOMO", "password" => "7024"],
            // ["PersonnelNo" => "92120", "name" => "INDAH NAWANGSARI", "password" => "92120"],
            // ["PersonnelNo" => "92121", "name" => "MUHAMAD FADLI", "password" => "92121"],
            // ["PersonnelNo" => "92122", "name" => "LODIAH TANUWIJAYA", "password" => "92122"],
            // ["PersonnelNo" => "236", "name" => "ANDRIK IRAWAN", "password" => "236"],
            // ["PersonnelNo" => "237", "name" => "NATASYA BERNIKA OLIVIA IVADA", "password" => "237"],
            // ["PersonnelNo" => "238", "name" => "PUTRI RATNA SARI", "password" => "238"],
            // ["PersonnelNo" => "240", "name" => "MOH BAGUS LUQMAN HAQIQI", "password" => "240"],
            // ["PersonnelNo" => "241", "name" => "RIO EFFANDA. AMD", "password" => "241"],
            // ["PersonnelNo" => "5032", "name" => "ROSDIANA PAMUNGKAS HS", "password" => "5032"],
            // ["PersonnelNo" => "70024", "name" => "EMHA", "password" => "70024"],
            // ["PersonnelNo" => "258", "name" => "YOPI ANTARIKSA", "password" => "258"],
            // ["PersonnelNo" => "5034", "name" => "RANI AYU WARDANI", "password" => "5034"],
            // ["PersonnelNo" => "5035", "name" => "KIKI INDAHSARI", "password" => "5035"],
            // ["PersonnelNo" => "8163", "name" => "DHIANIKA ENY ARYATI", "password" => "8163"],
            // ["PersonnelNo" => "8168", "name" => "CAHYO HADI SUSANDI", "password" => "8168"],
            // ["PersonnelNo" => "8167", "name" => "RAHIMA SHARA DIPA", "password" => "8167"],
            // ["PersonnelNo" => "8166", "name" => "TOMI LESMANA GELIAN", "password" => "8166"],
            // ["PersonnelNo" => "8165", "name" => "MALAYANTI SITUMORANG", "password" => "8165"],
            // ["PersonnelNo" => "8164", "name" => "SWASTIKA ADI SURANTA", "password" => "8164"],
            // ["PersonnelNo" => "8174", "name" => "FUAD BIDOL", "password" => "8174"],
            // ["PersonnelNo" => "8173", "name" => "IRWAN", "password" => "8173"],
            // ["PersonnelNo" => "8172", "name" => "RAHMAT MANSYUR", "password" => "8172"],
            // ["PersonnelNo" => "8171", "name" => "ERMA DAMAYANTI", "password" => "8171"],
            // ["PersonnelNo" => "8170", "name" => "DESI NURMALA HAMNI", "password" => "8170"],
            // ["PersonnelNo" => "5036", "name" => "PUTRI IMELIA AJENG PRIANTI", "password" => "5036"],
            // ["PersonnelNo" => "5037", "name" => "YULIANINGSIH", "password" => "5037"],
            // ["PersonnelNo" => "5039", "name" => "MUTIARA ANNISA", "password" => "5039"],
            // ["PersonnelNo" => "261", "name" => "SUSELO BARA PERSADA", "password" => "261"],
            // ["PersonnelNo" => "262", "name" => "JUMINTAR", "password" => "262"],
            // ["PersonnelNo" => "9217", "name" => "FAUZIYAH", "password" => "9217"],
            // ["PersonnelNo" => "5038", "name" => "RIKA AGUSTIN", "password" => "5038"],
            // ["PersonnelNo" => "70025", "name" => "ADE MULYANI", "password" => "70025"],
            // ["PersonnelNo" => "8178", "name" => "SABRINA LEOVITA", "password" => "8178"],
            // ["PersonnelNo" => "8177", "name" => "NUR ALAMSYAH", "password" => "8177"],
            // ["PersonnelNo" => "8176", "name" => "YOUNGKY NUR HIDAYAT", "password" => "8176"],
            // ["PersonnelNo" => "8175", "name" => "NOVIARA ANGELIA", "password" => "8175"],
            // ["PersonnelNo" => "267", "name" => "RENDRA PRATAMA PUTRA", "password" => "267"],
            // ["PersonnelNo" => "8180", "name" => "PURWANTI", "password" => "8180"],
            // ["PersonnelNo" => "5041", "name" => "WINDA NURFADILAH", "password" => "5041"],
            // ["PersonnelNo" => "271", "name" => "ABDI MULYAWAN", "password" => "271"],
            // ["PersonnelNo" => "8183", "name" => "SELVIA ROHANIATI", "password" => "8183"],
            // ["PersonnelNo" => "270", "name" => "NURUL FITRIA", "password" => "270"],
            // ["PersonnelNo" => "8185", "name" => "SYAFARI RAMADHAN", "password" => "8185"],
            // ["PersonnelNo" => "8186", "name" => "VINKA SELLA", "password" => "8186"],
            // ["PersonnelNo" => "8187", "name" => "MUHAMMAD FAIZ RIZKI", "password" => "8187"],
            // ["PersonnelNo" => "8188", "name" => "PRIMAYONA", "password" => "8188"],
            // ["PersonnelNo" => "8189", "name" => "SRI MURYATI", "password" => "8189"],
            // ["PersonnelNo" => "5043", "name" => "DINDA RIYANI", "password" => "5043"],
            // ["PersonnelNo" => "5046", "name" => "DIAN ANDRIANI", "password" => "5046"],
            // ["PersonnelNo" => "70027", "name" => "WAHYU NINGSIH", "password" => "70027"],
            // ["PersonnelNo" => "5048", "name" => "AYU WAHYUNINGRUM", "password" => "5048"],
            // ["PersonnelNo" => "8903", "name" => "FARADILLA", "password" => "8903"],
            // ["PersonnelNo" => "8899", "name" => "INDAH TRISNA", "password" => "8899"],
            // ["PersonnelNo" => "5049", "name" => "TARI FEBRIYANTI", "password" => "5049"],
            // ["PersonnelNo" => "274", "name" => "INDARTI", "password" => "274"],
            // ["PersonnelNo" => "275", "name" => "AGGUNG ARIF HADI SISWOYO", "password" => "275"],
            // ["PersonnelNo" => "5052", "name" => "NELA WULANDARI", "password" => "5052"],
            // ["PersonnelNo" => "5053", "name" => "WIWITAMI MOKOGINTA", "password" => "5053"],
            // ["PersonnelNo" => "9218", "name" => "RICO HENDRIK SANJAYA", "password" => "9218"],
            // ["PersonnelNo" => "9219", "name" => "MUHAMMAD SYAIFULLAH", "password" => "9219"],
            // ["PersonnelNo" => "5054", "name" => "ALNI NURINTAN MULYADI", "password" => "5054"],
            // ["PersonnelNo" => "5055", "name" => "YUANITA SUDIARTI", "password" => "5055"],
            // ["PersonnelNo" => "5056", "name" => "RIZKA AMELIA WIDIYANTI", "password" => "5056"],
            // ["PersonnelNo" => "5057", "name" => "SRI DHEA KARIM", "password" => "5057"],
            // ["PersonnelNo" => "5058", "name" => "SABRINA TIKKA NUR PRATAMI", "password" => "5058"],
            // ["PersonnelNo" => "5059", "name" => "RISKA NUR CAHYANTI", "password" => "5059"],
            // ["PersonnelNo" => "5061", "name" => "NUR SELYANAWATI", "password" => "5061"],
            // ["PersonnelNo" => "5062", "name" => "PUTRI INDAH WULAN SARI", "password" => "5062"],
            // ["PersonnelNo" => "5063", "name" => "ADHISTA FRICA ANANDA", "password" => "5063"],
            // ["PersonnelNo" => "70030", "name" => "NOVI MAYASARI", "password" => "70030"],
            // ["PersonnelNo" => "9999", "name" => "KISWARANTI ANGGRAENI", "password" => "9999"],
            // ["PersonnelNo" => "8906", "name" => "SIDIK", "password" => "8906"],
            // ["PersonnelNo" => "8907", "name" => "VITA SUNARTI", "password" => "8907"],
            // ["PersonnelNo" => "8912", "name" => "NIDIA PURWATI TINAMBUNAN", "password" => "8912"],
            // ["PersonnelNo" => "5064", "name" => "RAHMANIA AZZAHRA", "password" => "5064"],
            // ["PersonnelNo" => "5066", "name" => "DIAS DAMAYANTI", "password" => "5066"],
            // ["PersonnelNo" => "8086", "name" => "FAEDHIL ANGRYAWAN", "password" => "8086"],
            // ["PersonnelNo" => "8095", "name" => "NURUL CHOLIFAH", "password" => "8095"],
            // ["PersonnelNo" => "5067", "name" => "DESSI NURHASANAH", "password" => "5067"],
            // ["PersonnelNo" => "5069", "name" => "FITRI WULANDARI", "password" => "5069"],
            // ["PersonnelNo" => "5070", "name" => "SITI NURUL AISHAH", "password" => "5070"],
            // ["PersonnelNo" => "9220", "name" => "BAGAS BAHARUDIN ANHARI", "password" => "9220"],
            // ["PersonnelNo" => "5071", "name" => "FITRA ANITA", "password" => "5071"],
            // ["PersonnelNo" => "5073", "name" => "ISTIYANA", "password" => "5073"],
            // ["PersonnelNo" => "9221", "name" => "MUCHAMAD ARIFIN APRIYANTO", "password" => "9221"],
            // ["PersonnelNo" => "70032", "name" => "LANNY NURJANAH", "password" => "70032"],
            // ["PersonnelNo" => "70033", "name" => "ADITIA PRABOWO", "password" => "70033"],
            // ["PersonnelNo" => "278", "name" => "DYAH TRI PALUPI", "password" => "278"],
            // ["PersonnelNo" => "5074", "name" => "FATHINA KHALISHAH KANSA", "password" => "5074"],
            // ["PersonnelNo" => "8088", "name" => "REMITA IDRIS", "password" => "8088"],
            // ["PersonnelNo" => "8089", "name" => "ELLA ANGRAINI", "password" => "8089"],
            // ["PersonnelNo" => "8092", "name" => "ADELIA", "password" => "8092"],
            // ["PersonnelNo" => "5075", "name" => "NURSUSILAWATI", "password" => "5075"],
            // ["PersonnelNo" => "5076", "name" => "SITI KHOTIJAH", "password" => "5076"],
            // ["PersonnelNo" => "279", "name" => "NUR ASRI HANDAYANI SEHOL", "password" => "279"],
            // ["PersonnelNo" => "8190", "name" => "ANATYAS SARI KUSUMANINGRUM", "password" => "8190"],
            // ["PersonnelNo" => "5077", "name" => "NOVITA DWI LESTARI", "password" => "5077"],
            // ["PersonnelNo" => "5079", "name" => "RIVIANA KURNIASARI", "password" => "5079"],
            // ["PersonnelNo" => "5080", "name" => "LILI MUKHOLIFAH", "password" => "5080"],
            // ["PersonnelNo" => "5081", "name" => "PUTRI DIAH OKTAVIA", "password" => "5081"],
            // ["PersonnelNo" => "5082", "name" => "LAELA SETIANI", "password" => "5082"],
            // ["PersonnelNo" => "5083", "name" => "HARININGSIH", "password" => "5083"],
            // ["PersonnelNo" => "5084", "name" => "SITI RANIA ERNAWATI", "password" => "5084"],
            // ["PersonnelNo" => "5085", "name" => "NURIYATI", "password" => "5085"],
            // ["PersonnelNo" => "8191", "name" => "JAKA SYARIEF HIDAYAT", "password" => "8191"],
            // ["PersonnelNo" => "5089", "name" => "FENSCA TERSEMAN", "password" => "5089"],
            // ["PersonnelNo" => "8192", "name" => "MUHAMMAD NASRUDIN", "password" => "8192"],
            // ["PersonnelNo" => "5088", "name" => "I WAYAN BUDIARSANA", "password" => "5088"],
            // ["PersonnelNo" => "5087", "name" => "DZULFIQAR", "password" => "5087"],
            // ["PersonnelNo" => "70035", "name" => "AYU UTARI KUSUMA", "password" => "70035"],
            // ["PersonnelNo" => "8120", "name" => "SIMON PETER SAGITA YANUAR", "password" => "8120"],
            // ["PersonnelNo" => "8029", "name" => "ANDAR WASITO", "password" => "8029"],
            // ["PersonnelNo" => "8121", "name" => "AIDUL SAPUTRA", "password" => "8121"],
            // ["PersonnelNo" => "8132", "name" => "SRI UTAMI", "password" => "8132"],
            // ["PersonnelNo" => "8141", "name" => "ADITYA MANGGALA YUDHA", "password" => "8141"],
            // ["PersonnelNo" => "6092", "name" => "RIA PUTRI ABRIANTI", "password" => "6092"],
            // ["PersonnelNo" => "8201", "name" => "HENDRIK BARITA SIMATUPANG", "password" => "8201"],
            // ["PersonnelNo" => "8205", "name" => "YUDHIE ANDRIYANTO", "password" => "8205"],
            // ["PersonnelNo" => "322", "name" => "SUCI NADHILAH ASMY", "password" => "322"],
            // ["PersonnelNo" => "8030", "name" => "DEWI WAHYU SUSANTI", "password" => "8030"],
            // ["PersonnelNo" => "5091", "name" => "KARTIKA TATIK YULIANTI", "password" => "5091"],
            // ["PersonnelNo" => "5092", "name" => "CHOIRUNNISA", "password" => "5092"],
            // ["PersonnelNo" => "281", "name" => "FATKHUR ROHMAN", "password" => "281"],
            // ["PersonnelNo" => "8024", "name" => "MEGA SARI", "password" => "8024"],
            // ["PersonnelNo" => "5290", "name" => "FITRY SABTUTI", "password" => "5290"],
            // ["PersonnelNo" => "5098", "name" => "EKO SUGIANTO", "password" => "5098"],
            // ["PersonnelNo" => "5097", "name" => "HAIRUNNISA", "password" => "5097"],
            // ["PersonnelNo" => "5093", "name" => "SITI MIFTAHUL JANAH", "password" => "5093"],
            // ["PersonnelNo" => "5094", "name" => "INNAYAH KURNIAWATI", "password" => "5094"],
            // ["PersonnelNo" => "8199", "name" => "YUSUP MURDIANSYAH", "password" => "8199"],
            // ["PersonnelNo" => "9223", "name" => "M NUR WAHYUDIN", "password" => "9223"],
            // ["PersonnelNo" => "5192", "name" => "TATAH ISMAWATI", "password" => "5192"],
            // ["PersonnelNo" => "5099", "name" => "ADINDA PRADIPTA FIERYANTO", "password" => "5099"],
            // ["PersonnelNo" => "5100", "name" => "SARAH RAHAYU", "password" => "5100"],
            // ["PersonnelNo" => "8305", "name" => "MUHAMMAD AKBAR TONE", "password" => "8305"],
            // ["PersonnelNo" => "9224", "name" => "ARIA TOFAN WAHYUDI", "password" => "9224"],
            // ["PersonnelNo" => "5101", "name" => "MEYLIYA FAUZIAH", "password" => "5101"],
            // ["PersonnelNo" => "286", "name" => "JAINUL TRIONO", "password" => "286"],
            // ["PersonnelNo" => "8767", "name" => "MARTINDA PAULA SOFA", "password" => "8767"],
            // ["PersonnelNo" => "8766", "name" => "IWAN SETIADI", "password" => "8766"],
            // ["PersonnelNo" => "8157", "name" => "DADI SUPRIATNA", "password" => "8157"],
            // ["PersonnelNo" => "8156", "name" => "CARIN PUSPA SARI", "password" => "8156"],
            // ["PersonnelNo" => "5102", "name" => "IRMA KENDATI", "password" => "5102"],
            // ["PersonnelNo" => "5103", "name" => "TRI EKA PUTRI R", "password" => "5103"],
            // ["PersonnelNo" => "5104", "name" => "ZUYINA LINA", "password" => "5104"],
            // ["PersonnelNo" => "5111", "name" => "AYU PURNAMA SARI", "password" => "5111"],
            // ["PersonnelNo" => "9226", "name" => "MUHAMMAD ZYDAN KURNIANSYAH", "password" => "9226"],
            // ["PersonnelNo" => "287", "name" => "KEVIN NATHANAEL ABRAHAM", "password" => "287"],
            // ["PersonnelNo" => "8780", "name" => "IMAM ROPIKOH", "password" => "8780"],
            // ["PersonnelNo" => "8781", "name" => "JAKA PRADANA", "password" => "8781"],
            // ["PersonnelNo" => "8782", "name" => "SUNARKO", "password" => "8782"],
            // ["PersonnelNo" => "8783", "name" => "ANITA KAROLINA YOAN RAYANI", "password" => "8783"],
            // ["PersonnelNo" => "8784", "name" => "LA ODE ALFANI", "password" => "8784"],
            // ["PersonnelNo" => "8785", "name" => "ALI GINANJAR", "password" => "8785"],
            // ["PersonnelNo" => "8198", "name" => "MUHAMMAD TAUFIQ NURRAHMAN", "password" => "8198"],
            // ["PersonnelNo" => "290", "name" => "ACHMAD FAISOL", "password" => "290"],
            // ["PersonnelNo" => "5105", "name" => "LIA DESI SETYA PURWANTI", "password" => "5105"],
            // ["PersonnelNo" => "5107", "name" => "SITI NURHALIMAH", "password" => "5107"],
            // ["PersonnelNo" => "293", "name" => "HAMDAN RISAL RIZKY", "password" => "293"],
            // ["PersonnelNo" => "291", "name" => "M. BAYU MARHAENDRA JAYA", "password" => "291"],
            // ["PersonnelNo" => "9228", "name" => "YUDA WICAKSONO", "password" => "9228"],
            // ["PersonnelNo" => "9227", "name" => "AGNESIA ICHA PUTRI ANASTASYA", "password" => "9227"],
            // ["PersonnelNo" => "294", "name" => "SELLA MANZILAH ROHMAH", "password" => "294"],
            // ["PersonnelNo" => "8206", "name" => "RUDYANTO", "password" => "8206"],
            // ["PersonnelNo" => "296", "name" => "ANGGA YUDIANTO", "password" => "296"],
            // ["PersonnelNo" => "298", "name" => "YUSUP IMAM SUFII", "password" => "298"],
            // ["PersonnelNo" => "8197", "name" => "ADAM SAPUTRA", "password" => "8197"],
            // ["PersonnelNo" => "299", "name" => "ADITYA WARDHANY", "password" => "299"],
            // ["PersonnelNo" => "5110", "name" => "WARNIDA", "password" => "5110"],
            // ["PersonnelNo" => "9230", "name" => "SITI ASMAUL HUSNAH", "password" => "9230"],
            // ["PersonnelNo" => "5115", "name" => "HUTABARAT PUTRI ALICYA", "password" => "5115"],
            // ["PersonnelNo" => "9231", "name" => "YOGI RIZKI RAMADHAN", "password" => "9231"],
            // ["PersonnelNo" => "5118", "name" => "DARUL HIKMAH", "password" => "5118"],
            // ["PersonnelNo" => "303", "name" => "MOH IVAN ALIF ALIFI", "password" => "303"],
            // ["PersonnelNo" => "304", "name" => "FRANCH MAYLANA AL JUFRI", "password" => "304"],
            // ["PersonnelNo" => "307", "name" => "DESI UMI SOLIKAH", "password" => "307"],
            // ["PersonnelNo" => "306", "name" => "FADHILA HERDATIARNI ARTISTIEKAWATI", "password" => "306"],
            // ["PersonnelNo" => "309", "name" => "DWI LUVI YANTI", "password" => "309"],
            // ["PersonnelNo" => "5120", "name" => "MEGA ROSITIANA", "password" => "5120"],
            // ["PersonnelNo" => "5121", "name" => "CINDIKIA SAFIARI DEWI", "password" => "5121"],
            // ["PersonnelNo" => "5122", "name" => "MUQODDAROH", "password" => "5122"],
            // ["PersonnelNo" => "5123", "name" => "ASTRI ANNISHA AMALIA", "password" => "5123"],
            // ["PersonnelNo" => "310", "name" => "MOHAMMAD SALAM NASRUDIN", "password" => "310"],
            // ["PersonnelNo" => "5125", "name" => "CHLAUDIA JESSICA MORONG", "password" => "5125"],
            // ["PersonnelNo" => "8300", "name" => "IAN SETYAVANI MONROE", "password" => "8300"],
            // ["PersonnelNo" => "8301", "name" => "AGIL ENDAR WIRAWAN", "password" => "8301"],
            // ["PersonnelNo" => "8302", "name" => "IBNU SANTOSA", "password" => "8302"],
            // ["PersonnelNo" => "8303", "name" => "BELLA PUTRI YOLANDA", "password" => "8303"],
            // ["PersonnelNo" => "312", "name" => "DESI KUMALA SARI", "password" => "312"],
            // ["PersonnelNo" => "314", "name" => "LIVIA LORENZA BANJAR NAHOR", "password" => "314"],
            // ["PersonnelNo" => "313", "name" => "FATIN NAZIHAH", "password" => "313"],
            // ["PersonnelNo" => "9233", "name" => "EKO ARI ARDIANTO", "password" => "9233"],
            // ["PersonnelNo" => "9235", "name" => "FERRY ARDYAN", "password" => "9235"],
            // ["PersonnelNo" => "5127", "name" => "HARDIANTI", "password" => "5127"],
            // ["PersonnelNo" => "5129", "name" => "ANISA FITAHUL ZANAH", "password" => "5129"],
            // ["PersonnelNo" => "5130", "name" => "FERGY LISTIANTY", "password" => "5130"],
            // ["PersonnelNo" => "316", "name" => "SARAH MAULUDIYAH ABIDIN", "password" => "316"],
            // ["PersonnelNo" => "8915", "name" => "YOSUA EKAKURNIA PUTRA", "password" => "8915"],
            // ["PersonnelNo" => "319", "name" => "RANDY WIBISONO", "password" => "319"],
            // ["PersonnelNo" => "6002", "name" => "MARIA NORA LIONILDA", "password" => "6002"],
            // ["PersonnelNo" => "320", "name" => "MAYA TRI IDAYU", "password" => "320"],
            // ["PersonnelNo" => "321", "name" => "ASTI KIRANA", "password" => "321"],
            // ["PersonnelNo" => "6003", "name" => "SUSAN SUMIATI", "password" => "6003"],
            // ["PersonnelNo" => "6001", "name" => "SITI LESTARI", "password" => "6001"],
            // ["PersonnelNo" => "6004", "name" => "SLAMET K. WINARNI", "password" => "6004"],
            // ["PersonnelNo" => "6005", "name" => "SUFI WANTI", "password" => "6005"],
            // ["PersonnelNo" => "6006", "name" => "SURYATI", "password" => "6006"],
            // ["PersonnelNo" => "5132", "name" => "SITI FATIMAH", "password" => "5132"],
            // ["PersonnelNo" => "5133", "name" => "SADARIA", "password" => "5133"],
            // ["PersonnelNo" => "8918", "name" => "WINDA AAN ABETNICO", "password" => "8918"],
            // ["PersonnelNo" => "9236", "name" => "FIRZA MARDANI", "password" => "9236"],
            // ["PersonnelNo" => "8920", "name" => "INDRA PERMANA SAKTI", "password" => "8920"],
            // ["PersonnelNo" => "339", "name" => "ANWAR HUDA", "password" => "339"],
            // ["PersonnelNo" => "8922", "name" => "BOBBY ARFIAN", "password" => "8922"],
            // ["PersonnelNo" => "6012", "name" => "JENYVER DINI AL KHASANAH", "password" => "6012"],
            // ["PersonnelNo" => "6017", "name" => "TSAMARA HANINA OCTAVIERI", "password" => "6017"],
            // ["PersonnelNo" => "8923", "name" => "SEPTA TRIWIDIANTO", "password" => "8923"],
            // ["PersonnelNo" => "5134", "name" => "JARIAH", "password" => "5134"],
            // ["PersonnelNo" => "5135", "name" => "DESI FITRIYANI", "password" => "5135"],
            // ["PersonnelNo" => "5136", "name" => "LESTARI ANUGRAH PUTRI", "password" => "5136"],
            // ["PersonnelNo" => "5138", "name" => "LIDWINDA", "password" => "5138"],
            // ["PersonnelNo" => "5139", "name" => "NOERLIANA MALIK", "password" => "5139"],
            // ["PersonnelNo" => "5141", "name" => "TANIA SUKMA SARI", "password" => "5141"],
            // ["PersonnelNo" => "5140", "name" => "MAHARANI OKTAVIANA SAPITRI", "password" => "5140"],
            // ["PersonnelNo" => "327", "name" => "PUPU ANDARINI, S. SOS", "password" => "327"],
            // ["PersonnelNo" => "8925", "name" => "LAELA SARI", "password" => "8925"],
            // ["PersonnelNo" => "8926", "name" => "DAVID NICODEMUS KAIMAREHE", "password" => "8926"],
            // ["PersonnelNo" => "8927", "name" => "RIZQI LILIANA SURYA", "password" => "8927"],
            // ["PersonnelNo" => "6018", "name" => "WIDYA ANANDA PUTRI", "password" => "6018"],
            // ["PersonnelNo" => "6019", "name" => "YUNI RAFIKA SARI", "password" => "6019"],
            // ["PersonnelNo" => "6020", "name" => "HALIMATON SAKDIAH", "password" => "6020"],
            // ["PersonnelNo" => "6025", "name" => "PUTRI LAJUNA", "password" => "6025"],
            // ["PersonnelNo" => "8928", "name" => "M. IRFAN EFENDI", "password" => "8928"],
            // ["PersonnelNo" => "8929", "name" => "AHMAD FITRIADI", "password" => "8929"],
            // ["PersonnelNo" => "5142", "name" => "KHAULA PUTRI MIRANDA", "password" => "5142"],
            // ["PersonnelNo" => "5145", "name" => "SULASIH", "password" => "5145"],
            // ["PersonnelNo" => "8930", "name" => "RESTI FEBRIANI WULANDARI", "password" => "8930"],
            // ["PersonnelNo" => "8931", "name" => "MUHAMMAD AKBAR", "password" => "8931"],
            // ["PersonnelNo" => "330", "name" => "MUHAMMAD NUR QOMARI", "password" => "330"],
            // ["PersonnelNo" => "6028", "name" => "AYU DAMAYANTI", "password" => "6028"],
            // ["PersonnelNo" => "6131", "name" => "SRI ANITA BR KARO", "password" => "6131"],
            // ["PersonnelNo" => "6030", "name" => "SARI SARTIKA", "password" => "6030"],
            // ["PersonnelNo" => "6031", "name" => "NOVITA SARI DEWI", "password" => "6031"],
            // ["PersonnelNo" => "6032", "name" => "AZZURA HASIBUAN", "password" => "6032"],
            // ["PersonnelNo" => "6036", "name" => "YEZA ANANDA PUTRI", "password" => "6036"],
            // ["PersonnelNo" => "6034", "name" => "ELISABET RISKA VALENTINE", "password" => "6034"],
            // ["PersonnelNo" => "6037", "name" => "NINDY ANGGRAENI S.FARM APL", "password" => "6037"],
            // ["PersonnelNo" => "6038", "name" => "ETAPURNAMA SARI SAGALA", "password" => "6038"],
            // ["PersonnelNo" => "5146", "name" => "NOPIYANI", "password" => "5146"],
            // ["PersonnelNo" => "5147", "name" => "NIA KURNIASIH", "password" => "5147"],
            // ["PersonnelNo" => "5148", "name" => "SELFI HALDIYANTI", "password" => "5148"],
            // ["PersonnelNo" => "5149", "name" => "RIRIN", "password" => "5149"],
            // ["PersonnelNo" => "5150", "name" => "ADELGONDA DARNI", "password" => "5150"],
            // ["PersonnelNo" => "5153", "name" => "DEASY LANGELO", "password" => "5153"],
            // ["PersonnelNo" => "5154", "name" => "NINING SUWARNI", "password" => "5154"],
            // ["PersonnelNo" => "5155", "name" => "NURUL LATHIFAH HANUM", "password" => "5155"],
            // ["PersonnelNo" => "6039", "name" => "ISTIANA PURNAWANTI", "password" => "6039"],
            // ["PersonnelNo" => "6040", "name" => "NURLIYANTI PASARIBU", "password" => "6040"],
            // ["PersonnelNo" => "6041", "name" => "SHINTA AULIA", "password" => "6041"],
            // ["PersonnelNo" => "6045", "name" => "SITI MUAMANAH", "password" => "6045"],
            // ["PersonnelNo" => "6044", "name" => "SALMIA PUTRI", "password" => "6044"],
            // ["PersonnelNo" => "6046", "name" => "FITRIANA", "password" => "6046"],
            // ["PersonnelNo" => "6047", "name" => "DIANA BR SEMBIRING", "password" => "6047"],
            // ["PersonnelNo" => "6048", "name" => "HENY MAHENDRAYANI", "password" => "6048"],
            // ["PersonnelNo" => "6050", "name" => "JUANTI MANDASARIA MD KEB", "password" => "6050"],
            // ["PersonnelNo" => "6049", "name" => "MAIZARAH", "password" => "6049"],
            // ["PersonnelNo" => "6057", "name" => "PANI AGUSTIANI", "password" => "6057"],
            // ["PersonnelNo" => "6056", "name" => "SRI REJEKI", "password" => "6056"],
            // ["PersonnelNo" => "6054", "name" => "MUTIA RAIZA", "password" => "6054"],
            // ["PersonnelNo" => "6053", "name" => "AINUN NAILI", "password" => "6053"],
            // ["PersonnelNo" => "331", "name" => "AN ABDI SALAM", "password" => "331"],
            // ["PersonnelNo" => "6058", "name" => "BUDI LUCIA ANIEFIANTARI W. NY", "password" => "6058"],
            // ["PersonnelNo" => "6059", "name" => "ANNISA PUTRI", "password" => "6059"],
            // ["PersonnelNo" => "8934", "name" => "SANG MADE ANGGA RADITHA", "password" => "8934"],
            // ["PersonnelNo" => "5157", "name" => "YUNI RAHMA UNSIA", "password" => "5157"],
            // ["PersonnelNo" => "111335", "name" => "DIDIK EKO PRASETYO", "password" => "111335"],
            // ["PersonnelNo" => "8935", "name" => "RODI ATMAJI", "password" => "8935"],
            // ["PersonnelNo" => "8936", "name" => "RIZKY ANANDA", "password" => "8936"],
            // ["PersonnelNo" => "336", "name" => "ANTO SAPUTRA", "password" => "336"],
            // ["PersonnelNo" => "5158", "name" => "SEFIANA ERIKA SARI", "password" => "5158"],
            // ["PersonnelNo" => "6062", "name" => "WIDIA PEBRIANTI GINTING", "password" => "6062"],
            // ["PersonnelNo" => "8938", "name" => "ADRI REZKI", "password" => "8938"],
            // ["PersonnelNo" => "9239", "name" => "JANUAR RADILUS WERKUSEVIC", "password" => "9239"],
            // ["PersonnelNo" => "8939", "name" => "MUHAMMAD PADLI", "password" => "8939"],
            // ["PersonnelNo" => "8940", "name" => "NI LUH PUTU ASTITI FEBRIANI", "password" => "8940"],
            // ["PersonnelNo" => "338", "name" => "DINDA ALYA ARYANI", "password" => "338"],
            // ["PersonnelNo" => "8941", "name" => "SELFANA HENDRIKS", "password" => "8941"],
            // ["PersonnelNo" => "8942", "name" => "NURUL AL AMIN", "password" => "8942"],
            // ["PersonnelNo" => "5160", "name" => "RIRIN SELFIANA", "password" => "5160"],
            // ["PersonnelNo" => "5161", "name" => "INDRIA KUSUMA ANGGRAINI", "password" => "5161"],
            // ["PersonnelNo" => "6061", "name" => "ANNISA KHAIRANI H", "password" => "6061"],
            // ["PersonnelNo" => "6063", "name" => "MAQFIRAH", "password" => "6063"],
            // ["PersonnelNo" => "6064", "name" => "MAISARAH ANANDA", "password" => "6064"],
            // ["PersonnelNo" => "5276", "name" => "YULI YANTI", "password" => "5276"],
            // ["PersonnelNo" => "6067", "name" => "DEVIANTI LESTARI", "password" => "6067"],
            // ["PersonnelNo" => "8943", "name" => "EKO SUKATNO", "password" => "8943"],
            // ["PersonnelNo" => "8944", "name" => "PUPUT IRMAWATI", "password" => "8944"],
            // ["PersonnelNo" => "340", "name" => "MULIA SARI", "password" => "340"],
            // ["PersonnelNo" => "8945", "name" => "WA ODE NUR HASMI", "password" => "8945"],
            // ["PersonnelNo" => "5163", "name" => "RETNO HANDAYANI", "password" => "5163"],
            // ["PersonnelNo" => "5165", "name" => "AYU SRIWENING", "password" => "5165"],
            // ["PersonnelNo" => "8946", "name" => "BAMBANG BUDIARSO", "password" => "8946"],
            // ["PersonnelNo" => "6068", "name" => "NOVA ELYZA NASUTION", "password" => "6068"],
            // ["PersonnelNo" => "6069", "name" => "ADE RIYANI", "password" => "6069"],
            // ["PersonnelNo" => "6070", "name" => "PUTRI ADELIA AZAHRA", "password" => "6070"],
            // ["PersonnelNo" => "6071", "name" => "AULIA DESRI YUNITA", "password" => "6071"],
            // ["PersonnelNo" => "6073", "name" => "FEYBI CAROLINA", "password" => "6073"],
            // ["PersonnelNo" => "6074", "name" => "DEVINA RIFKA HUSAHI", "password" => "6074"],
            // ["PersonnelNo" => "6075", "name" => "SAHARIAH", "password" => "6075"],
            // ["PersonnelNo" => "6077", "name" => "IKA PURWITANINGSIH", "password" => "6077"],
            // ["PersonnelNo" => "348", "name" => "RENALDY FIRMANA", "password" => "348"],
            // ["PersonnelNo" => "349", "name" => "DEFI AINI NADHIFAH", "password" => "349"],
            // ["PersonnelNo" => "8949", "name" => "SITI RAHMAWATI", "password" => "8949"],
            // ["PersonnelNo" => "350", "name" => "NANANG SETIAWAN", "password" => "350"],
            // ["PersonnelNo" => "8950", "name" => "ANDI HASMIATY", "password" => "8950"],
            // ["PersonnelNo" => "5170", "name" => "MUTIARA ISMAIL", "password" => "5170"],
            // ["PersonnelNo" => "5172", "name" => "RAIDA PUTRI LAIA", "password" => "5172"],
            // ["PersonnelNo" => "5174", "name" => "ALKA", "password" => "5174"],
            // ["PersonnelNo" => "5175", "name" => "TIKA KARTIKA", "password" => "5175"],
            // ["PersonnelNo" => "5177", "name" => "LINDA PUSPITA SARI", "password" => "5177"],
            // ["PersonnelNo" => "70038", "name" => "SERLIYANI", "password" => "70038"],
            // ["PersonnelNo" => "8951", "name" => "NUR HAYATI JAMIL", "password" => "8951"],
            // ["PersonnelNo" => "6081", "name" => "EKA PALASARI", "password" => "6081"],
            // ["PersonnelNo" => "6076", "name" => "IRAYANTI", "password" => "6076"],
            // ["PersonnelNo" => "6078", "name" => "DHANA OCTORA SYAHPUTRA", "password" => "6078"],
            // ["PersonnelNo" => "352", "name" => "THIVAL ABROR ROMADHAN", "password" => "352"],
            // ["PersonnelNo" => "5178", "name" => "ULFA SABILULLAH", "password" => "5178"],
            // ["PersonnelNo" => "353", "name" => "TRI CAHYO NUGROHO", "password" => "353"],
            // ["PersonnelNo" => "8953", "name" => "A.M. FARIDH WAHYUDIN TAMSIL", "password" => "8953"],
            // ["PersonnelNo" => "9241", "name" => "ELLYA NOOR AZIZAH", "password" => "9241"],
            // ["PersonnelNo" => "5179", "name" => "WINDY PRATIWIE", "password" => "5179"],
            // ["PersonnelNo" => "5180", "name" => "RIANA WAHYU LORENSA", "password" => "5180"],
            // ["PersonnelNo" => "5181", "name" => "MILLATUL MUTAMIMMAH", "password" => "5181"],
            // ["PersonnelNo" => "5187", "name" => "DWIYANA PERTIWI", "password" => "5187"],
            // ["PersonnelNo" => "5188", "name" => "PUSPITA AYUNINGTYAS", "password" => "5188"],
            // ["PersonnelNo" => "6082", "name" => "MAYSARAH LUBIS", "password" => "6082"],
            // ["PersonnelNo" => "6083", "name" => "ASTRIA LIANA INTAN SARI", "password" => "6083"],
            // ["PersonnelNo" => "6084", "name" => "LULU NIA SUGIA", "password" => "6084"],
            // ["PersonnelNo" => "6085", "name" => "ZELIKA ABEL PUTRISIA", "password" => "6085"],
            // ["PersonnelNo" => "6139", "name" => "WANDA LUTFIANI", "password" => "6139"],
            // ["PersonnelNo" => "6087", "name" => "SRI LESTARI", "password" => "6087"],
            // ["PersonnelNo" => "6088", "name" => "SWASTIKA DESTRANTI", "password" => "6088"],
            // ["PersonnelNo" => "6089", "name" => "KARINA KADESTA", "password" => "6089"],
            // ["PersonnelNo" => "8955", "name" => "ZAHARA", "password" => "8955"],
            // ["PersonnelNo" => "8956", "name" => "AGUNG ZULKIFLI", "password" => "8956"],
            // ["PersonnelNo" => "8957", "name" => "AZWIRA YATI", "password" => "8957"],
            // ["PersonnelNo" => "8958", "name" => "M. YUNUS", "password" => "8958"],
            // ["PersonnelNo" => "355", "name" => "BAMBANG ARDIANSAH", "password" => "355"],
            // ["PersonnelNo" => "6091", "name" => "ELA NUR AENI", "password" => "6091"],
            // ["PersonnelNo" => "8959", "name" => "PURNIYANTI", "password" => "8959"],
            // ["PersonnelNo" => "70039", "name" => "DEWI PURNAMASARI", "password" => "70039"],
            // ["PersonnelNo" => "5196", "name" => "RAHELIA PETRUS", "password" => "5196"],
            // ["PersonnelNo" => "5195", "name" => "NIA NUR FINDA", "password" => "5195"],
            // ["PersonnelNo" => "5193", "name" => "DIANA KUSUMA DEWI", "password" => "5193"],
            // ["PersonnelNo" => "5194", "name" => "DIAN NURHAYATI", "password" => "5194"],
            // ["PersonnelNo" => "6093", "name" => "ARDANA SYAHPUTRI", "password" => "6093"],
            // ["PersonnelNo" => "6094", "name" => "FINA WULANDARI", "password" => "6094"],
            // ["PersonnelNo" => "6095", "name" => "MUZAIYANA", "password" => "6095"],
            // ["PersonnelNo" => "6096", "name" => "EVI SARWANI", "password" => "6096"],
            // ["PersonnelNo" => "6098", "name" => "TRI ASTUTI NUR HIDAYAH", "password" => "6098"],
            // ["PersonnelNo" => "60698", "name" => "TANTI RAHMATILAH", "password" => "60698"],
            // ["PersonnelNo" => "8963", "name" => "RONI BUDIAWAN", "password" => "8963"],
            // ["PersonnelNo" => "8965", "name" => "SLAMET RIYADI", "password" => "8965"],
            // ["PersonnelNo" => "8966", "name" => "MULYATI BUNGSUWATI", "password" => "8966"],
            // ["PersonnelNo" => "357", "name" => "FITRIANA BAROROH", "password" => "357"],
            // ["PersonnelNo" => "5204", "name" => "TRI INDAH KUSUMA DEWI", "password" => "5204"],
            // ["PersonnelNo" => "5205", "name" => "ASRI BULAN", "password" => "5205"],
            // ["PersonnelNo" => "8967", "name" => "VERAWATI", "password" => "8967"],
            // ["PersonnelNo" => "8968", "name" => "ARIA PUSPITA", "password" => "8968"],
            // ["PersonnelNo" => "5210", "name" => "IIS SAFITRI", "password" => "5210"],
            // ["PersonnelNo" => "6100", "name" => "NAZLA AULIA", "password" => "6100"],
            // ["PersonnelNo" => "6101", "name" => "FENNY KHAIRIANTI", "password" => "6101"],
            // ["PersonnelNo" => "6102", "name" => "MUTIARA SYAHNANDA", "password" => "6102"],
            // ["PersonnelNo" => "6103", "name" => "FIRERA DHANILIA", "password" => "6103"],
            // ["PersonnelNo" => "6107", "name" => "TISCA MIAVIENTY", "password" => "6107"],
            // ["PersonnelNo" => "6108", "name" => "YUNI MARIDA", "password" => "6108"],
            // ["PersonnelNo" => "6109", "name" => "SRI RAHAYU", "password" => "6109"],
            // ["PersonnelNo" => "8970", "name" => "I NYOMAN ARDATRINATHA, S.PD", "password" => "8970"],
            // ["PersonnelNo" => "8971", "name" => "BAYU PRASETYO", "password" => "8971"],
            // ["PersonnelNo" => "8972", "name" => "DENIES HERMAWAN", "password" => "8972"],
            // ["PersonnelNo" => "8973", "name" => "AKHMAD BAIHAQI", "password" => "8973"],
            // ["PersonnelNo" => "8975", "name" => "ASEP ABDUL MALIK", "password" => "8975"],
            // ["PersonnelNo" => "8976", "name" => "NIKA ESIH ULANDINA", "password" => "8976"],
            // ["PersonnelNo" => "8977", "name" => "GILANGTRIS RAMADHANI", "password" => "8977"],
            // ["PersonnelNo" => "363", "name" => "ILHAM YUSEFAFEBI ANTONO", "password" => "363"],
            // ["PersonnelNo" => "8979", "name" => "FIRMAN SUHESTIYONO", "password" => "8979"],
            // ["PersonnelNo" => "8980", "name" => "RACHMA YUNITA", "password" => "8980"],
            // ["PersonnelNo" => "5214", "name" => "SARAH SARASWATI", "password" => "5214"],
            // ["PersonnelNo" => "5220", "name" => "MELISA MELYAWATI SODIKIN", "password" => "5220"],
            // ["PersonnelNo" => "6144", "name" => "EKA FITRIYANA", "password" => "6144"],
            // ["PersonnelNo" => "5222", "name" => "ANYAPRAMESTI PUTRI SAGITA", "password" => "5222"],
            // ["PersonnelNo" => "8983", "name" => "DESYNTA DIANASARI", "password" => "8983"],
            // ["PersonnelNo" => "6121", "name" => "IMELDA TRI AGUSTINA", "password" => "6121"],
            // ["PersonnelNo" => "6122", "name" => "SUCI NURAQIDAH", "password" => "6122"],
            // ["PersonnelNo" => "6124", "name" => "SULASTRI TAMANAMPO", "password" => "6124"],
            // ["PersonnelNo" => "6125", "name" => "ADE IRAWATI BR SEMBIRING", "password" => "6125"],
            // ["PersonnelNo" => "6126", "name" => "PUTRI ADINDA", "password" => "6126"],
            // ["PersonnelNo" => "6127", "name" => "SHERLY MONIKA HARIS", "password" => "6127"],
            // ["PersonnelNo" => "6128", "name" => "WARDAH", "password" => "6128"],
            // ["PersonnelNo" => "6116", "name" => "SRI ANITA BR KARO", "password" => "6116"],
            // ["PersonnelNo" => "6132", "name" => "RULY DINDA MAULANI", "password" => "6132"],
            // ["PersonnelNo" => "8981", "name" => "CALVIN JHON FRANKLIN PAPILAYA", "password" => "8981"],
            // ["PersonnelNo" => "8984", "name" => "ACHMAD SHOLEH NUR HIDAYAT", "password" => "8984"],
            // ["PersonnelNo" => "8986", "name" => "HERLAMBANG DEDI KURNIA SHANDI", "password" => "8986"],
            // ["PersonnelNo" => "8987", "name" => "GINTAN AL AFGANI", "password" => "8987"],
            // ["PersonnelNo" => "8988", "name" => "FER JULIA NINGSIH", "password" => "8988"],
            // ["PersonnelNo" => "9243", "name" => "ARFIANI MEGA FITRIA", "password" => "9243"],
            // ["PersonnelNo" => "5225", "name" => "ELY KRISDAYANTI", "password" => "5225"],
            // ["PersonnelNo" => "5226", "name" => "PUTRI ANNA DEWI ELOK LESTARI", "password" => "5226"],
            // ["PersonnelNo" => "5227", "name" => "DEWI NURDIANA", "password" => "5227"],
            // ["PersonnelNo" => "5229", "name" => "NOVIA AULIA NUR", "password" => "5229"],
            // ["PersonnelNo" => "9249", "name" => "I KADEK HARY WIADNYANA", "password" => "9249"],
            // ["PersonnelNo" => "6140", "name" => "BUDI LAKSMITA", "password" => "6140"],
            // ["PersonnelNo" => "6141", "name" => "SITI NURHASANAH BR GINTING", "password" => "6141"],
            // ["PersonnelNo" => "6142", "name" => "LIA MUHARA BR NAINGGOLAN", "password" => "6142"],
            // ["PersonnelNo" => "6143", "name" => "DEVI ANGRAINI NASUTION", "password" => "6143"],
            // ["PersonnelNo" => "6137", "name" => "NENI SUPRIATIN", "password" => "6137"],
            // ["PersonnelNo" => "8989", "name" => "ARIES WAHYU INDRAWAN", "password" => "8989"],
            // ["PersonnelNo" => "8991", "name" => "NOVITA SARI", "password" => "8991"],
            // ["PersonnelNo" => "8992", "name" => "SURIYANINGSIH", "password" => "8992"],
            // ["PersonnelNo" => "8993", "name" => "ANDI MAHYUDIN", "password" => "8993"],
            // ["PersonnelNo" => "5233", "name" => "NIRWANA", "password" => "5233"],
            // ["PersonnelNo" => "374", "name" => "DIA SETYO RINI", "password" => "374"],
            // ["PersonnelNo" => "70041", "name" => "MUHAMMAD MUCHTAR JAMAL", "password" => "70041"],
            // ["PersonnelNo" => "5239", "name" => "DEBBY SITI ROSITA SAPUTRI", "password" => "5239"],
            // ["PersonnelNo" => "376", "name" => "APRILIA TAQIYYATUL MUTTARISAH", "password" => "376"],
            // ["PersonnelNo" => "8994", "name" => "WIDYA FEBRIYANI", "password" => "8994"],
            // ["PersonnelNo" => "8995", "name" => "IMAM SYAHRONI", "password" => "8995"],
            // ["PersonnelNo" => "6146", "name" => "DEWI HERAWATI", "password" => "6146"],
            // ["PersonnelNo" => "6148", "name" => "EVI MULIANI", "password" => "6148"],
            // ["PersonnelNo" => "382", "name" => "GABARIEL MAURIKE HELSON", "password" => "382"],
            // ["PersonnelNo" => "5244", "name" => "FARWA KHULAIPAH MUHAJAROH", "password" => "5244"],
            // ["PersonnelNo" => "5246", "name" => "SITI NADIA PRASISKA", "password" => "5246"],
            // ["PersonnelNo" => "5247", "name" => "JESSICA MERCHI MAHARANI", "password" => "5247"],
            // ["PersonnelNo" => "6152", "name" => "SRI DWIYANTI", "password" => "6152"],
            // ["PersonnelNo" => "6153", "name" => "CINDY NUR HENDYASARI", "password" => "6153"],
            // ["PersonnelNo" => "6154", "name" => "DEWI OKTARIA", "password" => "6154"],
            // ["PersonnelNo" => "6157", "name" => "KHADHRAH  ARMILA", "password" => "6157"],
            // ["PersonnelNo" => "6159", "name" => "PUTRI REZA STEVANI", "password" => "6159"],
            // ["PersonnelNo" => "386", "name" => "MOCHAMMAD SHIDIQ ROCHMATULLOH", "password" => "386"],
            // ["PersonnelNo" => "80000", "name" => "RISKY FEBRIANA PUTRI", "password" => "80000"],
            // ["PersonnelNo" => "80002", "name" => "EKA NUR REZKI", "password" => "80002"],
            // ["PersonnelNo" => "5250", "name" => "NURY ROCHMA SOFYANTI", "password" => "5250"],
            // ["PersonnelNo" => "6160", "name" => "BONTAR RIASARI DAULAY", "password" => "6160"],
            // ["PersonnelNo" => "80006", "name" => "DITA NUR SAKINA", "password" => "80006"],
            // ["PersonnelNo" => "1010", "name" => "ELAINE CATHERINA MULYONO", "password" => "1010"],
            // ["PersonnelNo" => "6169", "name" => "BARLIANA", "password" => "6169"],
            // ["PersonnelNo" => "9256", "name" => "ANGELIN GIOVANI PUSPITASARI", "password" => "9256"],
            // ["PersonnelNo" => "9257", "name" => "INDRYAS RAMADANI", "password" => "9257"],
            // ["PersonnelNo" => "398", "name" => "BEBEN PRANATA RISMADIARTA", "password" => "398"],
            // ["PersonnelNo" => "80021", "name" => "MARVIN ADRIAN VERSTEEGH", "password" => "80021"],
            // ["PersonnelNo" => "399", "name" => "RAIHAN ADIANSYAH", "password" => "399"],
            // ["PersonnelNo" => "400", "name" => "ANDRI EKA WAHYUDIANTO", "password" => "400"],
            // ["PersonnelNo" => "9258", "name" => "MAYA ANGGI DAMAYANTI", "password" => "9258"],
            // ["PersonnelNo" => "80022", "name" => "YENI YANWANTARI", "password" => "80022"],
            // ["PersonnelNo" => "5257", "name" => "TASYA SAFA CAMILA", "password" => "5257"],
            // ["PersonnelNo" => "5258", "name" => "DIANA DWI WULANSARI", "password" => "5258"],
            // ["PersonnelNo" => "5259", "name" => "FEBBY WINARTY", "password" => "5259"],
            // ["PersonnelNo" => "5260", "name" => "LIDYA CITRA PURNAMA", "password" => "5260"],
            // ["PersonnelNo" => "5261", "name" => "ANIDA", "password" => "5261"],
            // ["PersonnelNo" => "6181", "name" => "HASNIAR PUSPITA SARI", "password" => "6181"],
            // ["PersonnelNo" => "6182", "name" => "INAR SUNARTI", "password" => "6182"],
            // ["PersonnelNo" => "6183", "name" => "ALIYAH ABDI N", "password" => "6183"],
            // ["PersonnelNo" => "404", "name" => "ISNA NURROSYIDAH", "password" => "404"],
            // ["PersonnelNo" => "80023", "name" => "VECKY KUSOY", "password" => "80023"],
            // ["PersonnelNo" => "405", "name" => "MIFTAHUL ULUM", "password" => "405"],
            // ["PersonnelNo" => "406", "name" => "MUHAMMAD NIZARUDIN", "password" => "406"],
            // ["PersonnelNo" => "80024", "name" => "HERU TRIYONO", "password" => "80024"],
            // ["PersonnelNo" => "407", "name" => "DIMAS ADI PRATAMA", "password" => "407"],
            // ["PersonnelNo" => "80025", "name" => "NI PUTU SRI WINANTI", "password" => "80025"],
            // ["PersonnelNo" => "80026", "name" => "YUYU YUNINGSIH, A. MPD", "password" => "80026"],
            // ["PersonnelNo" => "408", "name" => "LISA NUR SABILA", "password" => "408"],
            // ["PersonnelNo" => "409", "name" => "AMARYLIS FAUSTINE TALITHA PAHLEVI", "password" => "409"],
            // ["PersonnelNo" => "80027", "name" => "AYU WANDIRA YUSUF", "password" => "80027"],
            // ["PersonnelNo" => "5262", "name" => "DHIA KHARIDA ZALFA", "password" => "5262"],
            // ["PersonnelNo" => "5263", "name" => "WINDAH NUR AMBAR NILA", "password" => "5263"],
            // ["PersonnelNo" => "5264", "name" => "EMILIA", "password" => "5264"],
            // ["PersonnelNo" => "410", "name" => "IRMA SYAHDANIAH", "password" => "410"],
            // ["PersonnelNo" => "5265", "name" => "ENI ULFI ROHMATUL LAILI", "password" => "5265"],
            // ["PersonnelNo" => "5266", "name" => "RISMA", "password" => "5266"],
            // ["PersonnelNo" => "5267", "name" => "RENY RETNOWATI", "password" => "5267"],
            // ["PersonnelNo" => "5268", "name" => "YAYANG ANA SAHFITRI", "password" => "5268"],
            // ["PersonnelNo" => "5269", "name" => "SANTI NURGIANTI", "password" => "5269"],
            // ["PersonnelNo" => "5270", "name" => "NIKEN FRANSIALITA", "password" => "5270"],
            // ["PersonnelNo" => "411", "name" => "BAGOS SATRIA", "password" => "411"],
            // ["PersonnelNo" => "9259", "name" => "HANA RAHMADIARNI", "password" => "9259"],
            // ["PersonnelNo" => "6190", "name" => "INDAH PUTRI MUSTIKA", "password" => "6190"],
            // ["PersonnelNo" => "6191", "name" => "MULIANA", "password" => "6191"],
            // ["PersonnelNo" => "412", "name" => "JAKA PURNAMA", "password" => "412"],
            // ["PersonnelNo" => "80028", "name" => "ALI HASAN", "password" => "80028"],
            // ["PersonnelNo" => "80029", "name" => "SANTI", "password" => "80029"],
            // ["PersonnelNo" => "80030", "name" => "MUHAMMAD THAMRIN", "password" => "80030"],
            // ["PersonnelNo" => "413", "name" => "BELLA ANNISA NABILA", "password" => "413"],
            // ["PersonnelNo" => "80031", "name" => "RETNO EL PRADHIPTA", "password" => "80031"],
            // ["PersonnelNo" => "414", "name" => "ANTOK KURNIAWAN", "password" => "414"],
            // ["PersonnelNo" => "80032", "name" => "REZKY DWI NUR MUTMAINAH", "password" => "80032"],
            // ["PersonnelNo" => "415", "name" => "ARYA ZANITRA PUTRA HERMAWAN", "password" => "415"],
            // ["PersonnelNo" => "5271", "name" => "ANNISA SOFYANA", "password" => "5271"],
            // ["PersonnelNo" => "5272", "name" => "ELA RULITA", "password" => "5272"],
            // ["PersonnelNo" => "5273", "name" => "TIARA NABILLAZEN", "password" => "5273"],
            // ["PersonnelNo" => "5274", "name" => "RAHMAH MAULIDAH ARNANTI", "password" => "5274"],
            // ["PersonnelNo" => "5275", "name" => "MIFTAKHUL JANAH", "password" => "5275"],
            // ["PersonnelNo" => "6192", "name" => "FITRIANI MANSYUR", "password" => "6192"],
            // ["PersonnelNo" => "6193", "name" => "HARIATI", "password" => "6193"],
            // ["PersonnelNo" => "6194", "name" => "SUCI SALSABILA MUSTARI", "password" => "6194"],
            // ["PersonnelNo" => "6195", "name" => "ANITA CHOLISTIYAWATI", "password" => "6195"],
            // ["PersonnelNo" => "416", "name" => "DANIYA AYU KAMILA", "password" => "416"],
            // ["PersonnelNo" => "417", "name" => "FITRI SYAWALIYAH YUSNITA", "password" => "417"],
            // ["PersonnelNo" => "80033", "name" => "BISRI EFENDI", "password" => "80033"],
            // ["PersonnelNo" => "80035", "name" => "QOMARUDDIN", "password" => "80035"],
            // ["PersonnelNo" => "80034", "name" => "SRI SUPARNI", "password" => "80034"],
            // ["PersonnelNo" => "80036", "name" => "AINUN JARIAH", "password" => "80036"],
            // ["PersonnelNo" => "419", "name" => "YULIANA FATMALA", "password" => "419"],
            // ["PersonnelNo" => "420", "name" => "ADEZIA NAJLA FATIKHA", "password" => "420"],
            // ["PersonnelNo" => "80037", "name" => "ENI SAFITRI", "password" => "80037"],
            // ["PersonnelNo" => "6196", "name" => "RAUZATULMUNA", "password" => "6196"],
            // ["PersonnelNo" => "422", "name" => "ATHAYA ALMIRA NUR AZZAHRA", "password" => "422"],
            // ["PersonnelNo" => "5277", "name" => "ERLINA", "password" => "5277"],
            // ["PersonnelNo" => "5278", "name" => "SRI WAHYUNI", "password" => "5278"],
            // ["PersonnelNo" => "423", "name" => "DELLA WIWEKO ADI", "password" => "423"],
            // ["PersonnelNo" => "424", "name" => "SHEREN THALITA KHITA", "password" => "424"],
            // ["PersonnelNo" => "70043", "name" => "DIAH ANGGRAENI", "password" => "70043"],
            // ["PersonnelNo" => "5280", "name" => "SYLVIA REGGY MINETHA", "password" => "5280"],
            // ["PersonnelNo" => "5279", "name" => "HELDA", "password" => "5279"],
            // ["PersonnelNo" => "5281", "name" => "PUTRI YULIANA LUTMAWATI", "password" => "5281"],
            // ["PersonnelNo" => "6197", "name" => "AMBAR PRASETYANINGRUM", "password" => "6197"],
            // ["PersonnelNo" => "80038", "name" => "NAFISAH RIDHOTI", "password" => "80038"],
            // ["PersonnelNo" => "425", "name" => "ANGGI SAFIRA SARA RIZKIYAH", "password" => "425"],
            // ["PersonnelNo" => "80039", "name" => "HAMID FEBRIYAN GHOZALI", "password" => "80039"],
            // ["PersonnelNo" => "80040", "name" => "SOIBATUS SALAMIYA", "password" => "80040"],
            // ["PersonnelNo" => "5282", "name" => "MARSHANDA DWI PUTRI", "password" => "5282"],
            // ["PersonnelNo" => "5283", "name" => "PUTRI ADELIA", "password" => "5283"],
            // ["PersonnelNo" => "5284", "name" => "ELLYSDA SAGITA DOSIOFA SAMBIGA", "password" => "5284"],
            // ["PersonnelNo" => "5285", "name" => "MANJA DARA JELITA CINTYAWATI", "password" => "5285"],
            // ["PersonnelNo" => "80041", "name" => "DENI KURNIAWAN", "password" => "80041"],
            // ["PersonnelNo" => "5286", "name" => "ARBETI CATUR SEPRIYANA", "password" => "5286"],
            // ["PersonnelNo" => "5287", "name" => "ERNA TRISTIANA", "password" => "5287"],
            // ["PersonnelNo" => "6198", "name" => "RISKA RAMADANI", "password" => "6198"],
            // ["PersonnelNo" => "6199", "name" => "SRI ANITA BR KARO", "password" => "6199"],
            // ["PersonnelNo" => "80043", "name" => "APRILLIA FEBRIANTI", "password" => "80043"],
            // ["PersonnelNo" => "426", "name" => "LISA AULIA ZAHRA", "password" => "426"],
            // ["PersonnelNo" => "80042", "name" => "MUHAMMAD BASOFI", "password" => "80042"],
            // ["PersonnelNo" => "427", "name" => "DEDI SETIAWAN", "password" => "427"],
            // ["PersonnelNo" => "6200", "name" => "ENDANG DARLIAH", "password" => "6200"],
            // ["PersonnelNo" => "6201", "name" => "JULI FITRIANA", "password" => "6201"],
            // ["PersonnelNo" => "6202", "name" => "SITI AISYAH", "password" => "6202"],
            // ["PersonnelNo" => "6203", "name" => "AFRINA MEY PUTRI BALQIS", "password" => "6203"],
            // ["PersonnelNo" => "6204", "name" => "SHAFA PUTRI INSANI", "password" => "6204"],
            // ["PersonnelNo" => "6205", "name" => "NIKKY ARYANINGSIH LOGO", "password" => "6205"],
            // ["PersonnelNo" => "6206", "name" => "RIRIS APRIL RIA", "password" => "6206"],
            // ["PersonnelNo" => "80044", "name" => "FIRMA KUASAN", "password" => "80044"],
            // ["PersonnelNo" => "428", "name" => "ZAHRO LAILI", "password" => "428"],
            // ["PersonnelNo" => "6207", "name" => "HASMAWATI M", "password" => "6207"],
            // ["PersonnelNo" => "6208", "name" => "LUY ALMA SAKHA RANA TSABITA", "password" => "6208"],
            // ["PersonnelNo" => "6209", "name" => "NORIYANA INDRI SUNDARI", "password" => "6209"],
            // ["PersonnelNo" => "70044", "name" => "KHATIMATUSSA'ADAH", "password" => "70044"],
            // ["PersonnelNo" => "6211", "name" => "AULIA CHINTYA BELLA", "password" => "6211"],
            // ["PersonnelNo" => "6212", "name" => "SALMA IZZATUNNAFSI", "password" => "6212"],
            // ["PersonnelNo" => "6213", "name" => "ISMI ANDRIANI", "password" => "6213"],
            // ["PersonnelNo" => "6214", "name" => "NURUL ADINDA", "password" => "6214"],
            // ["PersonnelNo" => "429", "name" => "LIZA ALIF SISWANTI", "password" => "429"],
            // ["PersonnelNo" => "80045", "name" => "MUHAMMAD RAPI", "password" => "80045"],
            ["PersonnelNo" => "430", "name" => "ANDRIE PURWANTO", "password" => "430"],
        ];

        foreach ($data as $user) {
            DB::table('tbl_user_hris_absen')->insert([
                'PersonnelNo' => $user['PersonnelNo'],
                'name' => $user['name'],
                'password' => Hash::make($user['password']),
            ]);
        }
    }
}
