<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // ["PersonnelNo" => "12345", "name" => "ADMIN", "password" => "12345"],
            // ["PersonnelNo" => "123456", "name" => "KARYAWAN", "password" => "123456"],
            // ["PersonnelNo" => "19", "name" => "ENI PUJI RAHAYU", "password" => "19"],
            // ["PersonnelNo" => "14", "name" => "DESSY DAMAYANTI", "password" => "14"],
            // ["PersonnelNo" => "27", "name" => "IMA YUNANI", "password" => "27"],
            // ["PersonnelNo" => "46", "name" => "NUR INDAYAH", "password" => "46"],
            // ["PersonnelNo" => "11", "name" => "BUDI SANTOSO", "password" => "11"],
            // ["PersonnelNo" => "15", "name" => "DIDIK ERWANTO", "password" => "15"],
            // ["PersonnelNo" => "50", "name" => "PURWANTO", "password" => "50"],
            // ["PersonnelNo" => "65", "name" => "SUGIONO", "password" => "65"],
            // ["PersonnelNo" => "62", "name" => "SUDARMONO", "password" => "62"],
            // ["PersonnelNo" => "21", "name" => "ERVI RIANINGSIH", "password" => "21"],
            // ["PersonnelNo" => "35", "name" => "LUSI LINDA ERLINAWATI", "password" => "35"],
            // ["PersonnelNo" => "42", "name" => "MOCH ARIF RASYIDI", "password" => "42"],
            // ["PersonnelNo" => "31", "name" => "JAINUDIN", "password" => "31"],
            // ["PersonnelNo" => "47", "name" => "NUR KHOLIS SISWANTO", "password" => "47"],
            // ["PersonnelNo" => "64", "name" => "SUGENG AGUNG WIDODO ARYANTO", "password" => "64"],
            // ["PersonnelNo" => "56", "name" => "ROCHMAN", "password" => "56"],
            // ["PersonnelNo" => "70001", "name" => "RAIS SUMARNO", "password" => "70001"],
            // ["PersonnelNo" => "73", "name" => "WINDY EKA SUSANTI", "password" => "73"],
            // ["PersonnelNo" => "4", "name" => "AGUS SETYOADI", "password" => "4"],
            // ["PersonnelNo" => "66", "name" => "SURYANTO", "password" => "66"],
            // ["PersonnelNo" => "28", "name" => "IMROATUS SHOLIKHAH", "password" => "28"],
            // ["PersonnelNo" => "75", "name" => "YAYAN GUNAWILAGA", "password" => "75"],
            // ["PersonnelNo" => "5", "name" => "AGUS SUSANTO", "password" => "5"],
            // ["PersonnelNo" => "10", "name" => "ARIYANTO", "password" => "10"],
            // ["PersonnelNo" => "18", "name" => "ELYFAH SETYOWATI", "password" => "18"],
            // ["PersonnelNo" => "25", "name" => "HASAN AMIRUDIN", "password" => "25"],
            // ["PersonnelNo" => "32", "name" => "KARNADI SUDIRJA", "password" => "32"],
            // ["PersonnelNo" => "33", "name" => "KEMALAWATI", "password" => "33"],
            // ["PersonnelNo" => "38", "name" => "MARIA JOVITA H.S", "password" => "38"],
            // ["PersonnelNo" => "40", "name" => "MATIUS WAHYU BUDI SANTOSO", "password" => "40"],
            // ["PersonnelNo" => "44", "name" => "NOOR AINI", "password" => "44"],
            // ["PersonnelNo" => "57", "name" => "ROHMAD KUNCORO D", "password" => "57"],
            // ["PersonnelNo" => "68", "name" => "TITIK ERIANI KUSMIATI", "password" => "68"],
            // ["PersonnelNo" => "3", "name" => "ABDULLOH MAS'UD, SE", "password" => "3"],
            // ["PersonnelNo" => "394", "name" => "ELAINE CATHERINA MULYONO, S. FARM., APT.", "password" => "394"],
            // ["PersonnelNo" => "54", "name" => "RINI KUSUMA WARDANI", "password" => "54"],
            // ["PersonnelNo" => "37", "name" => "MUHAMMAD MISBAHUL ILMI", "password" => "37"],
            // ["PersonnelNo" => "34", "name" => "LILIS KARIAWATI", "password" => "34"],
            // ["PersonnelNo" => "26", "name" => "IKA UMI AZIZAH", "password" => "26"],
            // ["PersonnelNo" => "13", "name" => "CHATERINA NIMAS TITIS WINASTI", "password" => "13"],
            // ["PersonnelNo" => "9", "name" => "ANDIONO ARI M NUR", "password" => "9"],
            // ["PersonnelNo" => "141", "name" => "YOLANDA LAURENCIA GEOVANNY", "password" => "141"],
            // ["PersonnelNo" => "53", "name" => "REYNANDA VIOLINA AGUS DAMAYANTI", "password" => "53"],
            // ["PersonnelNo" => "76", "name" => "YEHEZKIEL LINANDI", "password" => "76"],
            // ["PersonnelNo" => "24", "name" => "HARIYANTO", "password" => "24"],
            // ["PersonnelNo" => "2", "name" => "ABDUL GHOFUR", "password" => "2"],
            // ["PersonnelNo" => "72", "name" => "WEKA NASTITI PRANA YUANTI", "password" => "72"],
            // ["PersonnelNo" => "134", "name" => "NURUL HUDA", "password" => "134"],
            // ["PersonnelNo" => "6", "name" => "ALFIAN RIZQI ROHMANDIANSYAH", "password" => "6"],
            // ["PersonnelNo" => "103", "name" => "DENY ANDRIANTO", "password" => "103"],
            // ["PersonnelNo" => "9001", "name" => "ACHMAT ALBASIR", "password" => "9001"],
            // ["PersonnelNo" => "9003", "name" => "Aditia Rizqi Darmawan", "password" => "9003"],
            // ["PersonnelNo" => "104", "name" => "FANNY ERYA SAMANTA", "password" => "104"],
            // ["PersonnelNo" => "9005", "name" => "AGUS PRASETIYO", "password" => "9005"],
            // ["PersonnelNo" => "9008", "name" => "AMALIA FITRI", "password" => "9008"],
            // ["PersonnelNo" => "105", "name" => "FERY SUSANTO", "password" => "105"],
            // ["PersonnelNo" => "9009", "name" => "ANDRE MADONI", "password" => "9009"],
            // ["PersonnelNo" => "162", "name" => "EKO AJI SATRIA", "password" => "162"],
            // ["PersonnelNo" => "107", "name" => "SUNARTI", "password" => "107"],
            // ["PersonnelNo" => "365", "name" => "CICI DISTRIANAH", "password" => "365"],
            // ["PersonnelNo" => "77", "name" => "SITI JARROH", "password" => "77"],
            // ["PersonnelNo" => "9014", "name" => "DEBI INDAH WAHYUNI", "password" => "9014"],
            // ["PersonnelNo" => "9115", "name" => "DEDIK DWI SAPUTRA", "password" => "9115"],
            // ["PersonnelNo" => "9152", "name" => "DIANA TYAS SAPUTRI", "password" => "9152"],
            // ["PersonnelNo" => "131", "name" => "SITI MAYSARO", "password" => "131"],
            // ["PersonnelNo" => "109", "name" => "MAWAN YULIANTO", "password" => "109"],
            // ["PersonnelNo" => "282", "name" => "DIMAS ADITYAH", "password" => "282"],
            // ["PersonnelNo" => "110", "name" => "BUDIONO", "password" => "110"],
            // ["PersonnelNo" => "111", "name" => "DHANA INDRA SENTOSA", "password" => "111"],
            // ["PersonnelNo" => "79", "name" => "LILIS PUJIASTUTIK", "password" => "79"],
            // ["PersonnelNo" => "96", "name" => "SULASTRI PRF", "password" => "96"],
            // ["PersonnelNo" => "9118", "name" => "Efendi", "password" => "9118"],
            // ["PersonnelNo" => "9119", "name" => "EFENDI HERMAWAN", "password" => "9119"],
            // ["PersonnelNo" => "9120", "name" => "EKA WULANDARI", "password" => "9120"],
            // ["PersonnelNo" => "9121", "name" => "ELY EKAWATI", "password" => "9121"],
            // ["PersonnelNo" => "9122", "name" => "ERIKA WANDA WULANDARI", "password" => "9122"],
            // ["PersonnelNo" => "9124", "name" => "ERNIA", "password" => "9124"],
            // ["PersonnelNo" => "9125", "name" => "EVA LESTARI NINGSIH", "password" => "9125"],
            // ["PersonnelNo" => "112", "name" => "CHOTIMAH", "password" => "112"],
            // ["PersonnelNo" => "81", "name" => "HERWIN", "password" => "81"],
            // ["PersonnelNo" => "82", "name" => "AUNUL ISLAMIYAH", "password" => "82"],
            // ["PersonnelNo" => "83", "name" => "ZAENAL DWI IFANI", "password" => "83"],
            // ["PersonnelNo" => "206", "name" => "FITRI ROMAYATI", "password" => "206"],
            // ["PersonnelNo" => "9013", "name" => "FITRI SETIA ARIYANTI", "password" => "9013"],
            // ["PersonnelNo" => "9128", "name" => "HASANAH", "password" => "9128"],
            // ["PersonnelNo" => "84", "name" => "LUTFI ANDRE IRAWAN", "password" => "84"],
            // ["PersonnelNo" => "114", "name" => "DANI SUPRAYETNO", "password" => "114"],
            // ["PersonnelNo" => "147", "name" => "ALFIAN AZMI ACHMAD HABIBI", "password" => "147"],
            // ["PersonnelNo" => "9130", "name" => "INDAH WULANDARI", "password" => "9130"],
            // ["PersonnelNo" => "116", "name" => "SITI FATIMA JAZILAH", "password" => "116"],
            // ["PersonnelNo" => "85", "name" => "NUR SAIDAH", "password" => "85"],
            // ["PersonnelNo" => "9131", "name" => "INTAN WAHYU WILUJENG", "password" => "9131"],
            // ["PersonnelNo" => "117", "name" => "DAMI", "password" => "117"],
            // ["PersonnelNo" => "259", "name" => "JUROTUN NISAH", "password" => "259"],
            // ["PersonnelNo" => "132", "name" => "LUSIANA PAIJEM", "password" => "132"],
            // ["PersonnelNo" => "9134", "name" => "LIA RAHMAWATI", "password" => "9134"],
            // ["PersonnelNo" => "119", "name" => "SAFIYEH", "password" => "119"],
            // ["PersonnelNo" => "86", "name" => "ALFIAN", "password" => "86"],
            // ["PersonnelNo" => "120", "name" => "S. HARINI", "password" => "120"],
            // ["PersonnelNo" => "9135", "name" => "LILA OLIVYA PRIVANA", "password" => "9135"],
            // ["PersonnelNo" => "9136", "name" => "LINA DIANITA", "password" => "9136"],
            // ["PersonnelNo" => "154", "name" => "LUZIANA", "password" => "154"],
            // ["PersonnelNo" => "133", "name" => "NANIK SUHERMAWATI", "password" => "133"],
            // ["PersonnelNo" => "9139", "name" => "MIFTAHUL ULUM", "password" => "9139"],
            // ["PersonnelNo" => "121", "name" => "MULYADI", "password" => "121"],
            // ["PersonnelNo" => "88", "name" => "UCI USWATUN CHASANAH", "password" => "88"],
            // ["PersonnelNo" => "89", "name" => "AGUS PRIYO WIYONO", "password" => "89"],
            // ["PersonnelNo" => "122", "name" => "INAKUM", "password" => "122"],
            // ["PersonnelNo" => "90", "name" => "SITI MASLIKAH", "password" => "90"],
            // ["PersonnelNo" => "9140", "name" => "MUCHAMMAD SADHAM HUSEN", "password" => "9140"],
            // ["PersonnelNo" => "123", "name" => "ADE WISMA TRI WAHYU", "password" => "123"],
            // ["PersonnelNo" => "124", "name" => "KUMAISAROH", "password" => "124"],
            // ["PersonnelNo" => "125", "name" => "LUTFI SHOFIYUDDIN", "password" => "125"],
            // ["PersonnelNo" => "9142", "name" => "MUCHLAS PUTRA SUDHANA", "password" => "9142"],
            // ["PersonnelNo" => "91", "name" => "AHMAD SYAFII", "password" => "91"],
            // ["PersonnelNo" => "9143", "name" => "MUFARIDA", "password" => "9143"],
            // ["PersonnelNo" => "342", "name" => "MUHAMMAD HUSAIN ABDILLAH", "password" => "342"],
            // ["PersonnelNo" => "9145", "name" => "MUHAMMAD ROSELI", "password" => "9145"],
            // ["PersonnelNo" => "9051", "name" => "NABILA PUTRI GHOZALI", "password" => "9051"],
            // ["PersonnelNo" => "93", "name" => "SUGENG RAHARJO", "password" => "93"],
            // ["PersonnelNo" => "94", "name" => "SUMIATUN", "password" => "94"],
            // ["PersonnelNo" => "126", "name" => "NOSA HARIATI", "password" => "126"],
            // ["PersonnelNo" => "9147", "name" => "NOER NOVITA SETIAWATI", "password" => "9147"],
            // ["PersonnelNo" => "145", "name" => "PARNO", "password" => "145"],
            // ["PersonnelNo" => "80", "name" => "SULASTRI HBL", "password" => "80"],
            // ["PersonnelNo" => "9058", "name" => "RATNA FITASARI", "password" => "9058"],
            // ["PersonnelNo" => "197", "name" => "AVRILIA MAS UDAH", "password" => "197"],
            // ["PersonnelNo" => "9060", "name" => "RIA RESTY ANGGRAENI", "password" => "9060"],
            // ["PersonnelNo" => "9061", "name" => "RISTANTO", "password" => "9061"],
            // ["PersonnelNo" => "99", "name" => "YUDI SUASWORO", "password" => "99"],
            // ["PersonnelNo" => "100", "name" => "MUCH. SHOLEH", "password" => "100"],
            // ["PersonnelNo" => "101", "name" => "HELMI FAUZI", "password" => "101"],
            // ["PersonnelNo" => "168", "name" => "RUDY WAHYU SAPUTRA", "password" => "168"],
            // ["PersonnelNo" => "128", "name" => "ABDUL KARIM", "password" => "128"],
            // ["PersonnelNo" => "9110", "name" => "RUSDI", "password" => "9110"],
            // ["PersonnelNo" => "9065", "name" => "SAMSUL HADI", "password" => "9065"],
            // ["PersonnelNo" => "178", "name" => "SENDI PRATAMA", "password" => "178"],
            // ["PersonnelNo" => "9070", "name" => "SITI ROBIBAH", "password" => "9070"],
            // ["PersonnelNo" => "152", "name" => "SOEFAIDIK KUSWANTORO", "password" => "152"],
            // ["PersonnelNo" => "9071", "name" => "SRI WATININGSIH", "password" => "9071"],
            // ["PersonnelNo" => "153", "name" => "SUMARIYONO HERMAWAN", "password" => "153"],
            // ["PersonnelNo" => "9075", "name" => "SUWARNI", "password" => "9075"],
            // ["PersonnelNo" => "8075", "name" => "SAIFUL AFFANDI", "password" => "8075"],
            // ["PersonnelNo" => "9107", "name" => "TEGUH DWI SAPUTRO", "password" => "9107"],
            // ["PersonnelNo" => "9077", "name" => "TEGUH SANTOSO", "password" => "9077"],
            // ["PersonnelNo" => "183", "name" => "TRI ANDRIANTO ROCHMATULLOH", "password" => "183"],
            // ["PersonnelNo" => "9079", "name" => "TRI AYU NING TIYAS", "password" => "9079"],
            // ["PersonnelNo" => "177", "name" => "TRI WAHYUNI SURYA DEWI", "password" => "177"],
            // ["PersonnelNo" => "8047", "name" => "HENDRIKUS RICKY MITAN", "password" => "8047"],
            // ["PersonnelNo" => "9083", "name" => "WIJAYANTI KUSUMANINGTYAS", "password" => "9083"],
            // ["PersonnelNo" => "5004", "name" => "DWI LUSIANA", "password" => "5004"],
            // ["PersonnelNo" => "8014", "name" => "ANNIZA REQYTA AMIR", "password" => "8014"],
            // ["PersonnelNo" => "8001", "name" => "AA PUTU SUASTINI", "password" => "8001"],
            // ["PersonnelNo" => "8023", "name" => "DEDDY AFERIYANTO", "password" => "8023"],
            // ["PersonnelNo" => "5012", "name" => "SELFINA NUGRAHENI", "password" => "5012"],
            // ["PersonnelNo" => "70008", "name" => "YEYEN MARYANI", "password" => "70008"],
            // ["PersonnelNo" => "70009", "name" => "ALFIRA RAFINSA YASRI", "password" => "70009"],
            // ["PersonnelNo" => "70002", "name" => "HENIK YULAIKA", "password" => "70002"],
            // ["PersonnelNo" => "8081", "name" => "SRI WAHYUNI", "password" => "8081"],
            // ["PersonnelNo" => "8085", "name" => "TIKA ARDIANTI", "password" => "8085"],
            // ["PersonnelNo" => "8056", "name" => "LEA CARLA BASTARANI", "password" => "8056"],
            // ["PersonnelNo" => "5002", "name" => "NINDITA PINTANING TRI ASTUTI", "password" => "5002"],
            // ["PersonnelNo" => "5010", "name" => "SITI AMINAH", "password" => "5010"],
            // ["PersonnelNo" => "143", "name" => "ANGGRAINI WIDIASTUTI", "password" => "143"],
            // ["PersonnelNo" => "167", "name" => "EVANDA BELLA ERSALINA", "password" => "167"],
            // ["PersonnelNo" => "151", "name" => "ERI DWI SETYORINI", "password" => "151"],
            // ["PersonnelNo" => "142", "name" => "JUNI IRINIA LESTARI", "password" => "142"],
            // ["PersonnelNo" => "184", "name" => "YOGI ANDREANSYAH", "password" => "184"],
            // ["PersonnelNo" => "186", "name" => "ALI MUCHTAR", "password" => "186"],
            // ["PersonnelNo" => "187", "name" => "ILFI NUR DIANA", "password" => "187"],
            // ["PersonnelNo" => "188", "name" => "DEVI ELIS AGUS BUDIARTO", "password" => "188"],
            // ["PersonnelNo" => "189", "name" => "MOHAMMAD ARDYAS FANDY RAMMDHANI", "password" => "189"],
            // ["PersonnelNo" => "149", "name" => "RIZKI LUTFIYATIN NISA", "password" => "149"],
            // ["PersonnelNo" => "137", "name" => "HERI SUSANTO", "password" => "137"],
            // ["PersonnelNo" => "164", "name" => "MOCHAMAD MAHMUNIR", "password" => "164"],
            // ["PersonnelNo" => "144", "name" => "SUTONO", "password" => "144"],
            // ["PersonnelNo" => "158", "name" => "ACHMAD DAVID CANDRA", "password" => "158"],
            // ["PersonnelNo" => "156", "name" => "CRISTIANTO", "password" => "156"],
            // ["PersonnelNo" => "8018", "name" => "BY LEWI MATHEUS DETHAN", "password" => "8018"],
            // ["PersonnelNo" => "191", "name" => "JOHAN ISWARA WIJAYA", "password" => "191"],
            // ["PersonnelNo" => "9004", "name" => "ADYTIA PRASETYA AMANDA PUTRA", "password" => "9004"],
            // ["PersonnelNo" => "9057", "name" => "PUK CINTAMI", "password" => "9057"],
            // ["PersonnelNo" => "9069", "name" => "SITI MASULAH", "password" => "9069"],
            // ["PersonnelNo" => "8000", "name" => "ADELIA RACHMAWATI CHARISA", "password" => "8000"],
            // ["PersonnelNo" => "8021", "name" => "DARMAWATI", "password" => "8021"],
            // ["PersonnelNo" => "8059", "name" => "MICHAEL ONGKO WIJAYA", "password" => "8059"],
            // ["PersonnelNo" => "70006", "name" => "SANTOSO", "password" => "70006"],
            // ["PersonnelNo" => "9088", "name" => "ANNISA PUTRI APRILIA", "password" => "9088"],
            // ["PersonnelNo" => "9100", "name" => "NAFIRA MAULIDIYA", "password" => "9100"],
            // ["PersonnelNo" => "9099", "name" => "MINARSIH", "password" => "9099"],
            // ["PersonnelNo" => "9098", "name" => "LINDA SRI WIJAYANTI", "password" => "9098"],
            // ["PersonnelNo" => "9097", "name" => "LIDYA WALIMATUS ZAHRA", "password" => "9097"],
            // ["PersonnelNo" => "9095", "name" => "FITA AFSARI", "password" => "9095"],
            // ["PersonnelNo" => "9093", "name" => "ENDANG EKOWATI", "password" => "9093"],
            // ["PersonnelNo" => "8005", "name" => "AGUS NUGROHO NOTO SUSANTO", "password" => "8005"],
            // ["PersonnelNo" => "9091", "name" => "DIMAS BUKHIN NUGRAHA", "password" => "9091"],
            // ["PersonnelNo" => "8008", "name" => "A.M. AKBAR", "password" => "8008"],
            // ["PersonnelNo" => "70004", "name" => "BAYU SETIYAWAN", "password" => "70004"],
            // ["PersonnelNo" => "9086", "name" => "ANIS CHOIRUN NISAK", "password" => "9086"],
            // ["PersonnelNo" => "9096", "name" => "ISNAINI B S SISTHA YATIM", "password" => "9096"],
            // ["PersonnelNo" => "70012", "name" => "MALIK DWI SURYO ATMOJA", "password" => "70012"],
            // ["PersonnelNo" => "63", "name" => "SUGENG", "password" => "63"],
            // ["PersonnelNo" => "29", "name" => "INDRIANI", "password" => "29"],
            // ["PersonnelNo" => "195", "name" => "BAYU WHISNU WHARDANA", "password" => "195"],
            // ["PersonnelNo" => "196", "name" => "ACHMAD HIDAYATURROZIQ", "password" => "196"],
            // ["PersonnelNo" => "8114", "name" => "YULIA STEVANI WOWOR", "password" => "8114"],
            // ["PersonnelNo" => "5011", "name" => "YURIKE ELVIRA INTAN LESTARI", "password" => "5011"],
            // ["PersonnelNo" => "140", "name" => "KIEVIN ALIFFIANSYAH ARDI", "password" => "140"],
            // ["PersonnelNo" => "201", "name" => "WINDRATIARA MULIANI", "password" => "201"],
            // ["PersonnelNo" => "9159", "name" => "HENNY SETIYOWATI", "password" => "9159"],
            // ["PersonnelNo" => "9157", "name" => "JIYANI", "password" => "9157"],
            // ["PersonnelNo" => "8913", "name" => "NI KADEK DESIANI", "password" => "8913"],
            // ["PersonnelNo" => "205", "name" => "HILMI DWI HARTANTO", "password" => "205"],
            // ["PersonnelNo" => "208", "name" => "MOH FARIS", "password" => "208"],
            // ["PersonnelNo" => "8140", "name" => "JUNAEDY ABDILLAH AVRIVIANTIKA", "password" => "8140"],
            // ["PersonnelNo" => "8147", "name" => "SHEHRIN HAMONANGAN", "password" => "8147"],
            // ["PersonnelNo" => "211", "name" => "SETYO BUDI UTOMO", "password" => "211"],
            // ["PersonnelNo" => "8149", "name" => "GLORY RIAMA HOSIANNA", "password" => "8149"],
            // ["PersonnelNo" => "5015", "name" => "IFA WIJAYANTI", "password" => "5015"],
            // ["PersonnelNo" => "216", "name" => "MAULUDI WIBAWA", "password" => "216"],
            // ["PersonnelNo" => "217", "name" => "FREDI RISDA SAPUTRA", "password" => "217"],
            // ["PersonnelNo" => "9165", "name" => "AGUS WIRANTONO", "password" => "9165"],
            // ["PersonnelNo" => "8151", "name" => "YUSRIL", "password" => "8151"],
            // ["PersonnelNo" => "8154", "name" => "SINTA YUNI ARTHA", "password" => "8154"],
            // ["PersonnelNo" => "221", "name" => "DWI ANTO", "password" => "221"],
            // ["PersonnelNo" => "202109", "name" => "SUKMAWATI", "password" => "202109"],
            // ["PersonnelNo" => "223", "name" => "ELLYANA DWI SOENTORO", "password" => "223"],
            // ["PersonnelNo" => "9179", "name" => "SASA MULYANTI", "password" => "9179"],
            // ["PersonnelNo" => "9190", "name" => "RISKA PRIYANTI", "password" => "9190"],
            // ["PersonnelNo" => "9192", "name" => "LINDA KUSNIYA", "password" => "9192"],
            // ["PersonnelNo" => "9195", "name" => "EVI LUSIANA WATI", "password" => "9195"],
            // ["PersonnelNo" => "226", "name" => "MUHAMMAD ARIF ROIS MAHARDIKA", "password" => "226"],
            // ["PersonnelNo" => "9992", "name" => "LILI ENDAH PRIHASTUTI", "password" => "9992"],
            // ["PersonnelNo" => "228", "name" => "DWI RENY WULANDARI", "password" => "228"],
            // ["PersonnelNo" => "9196", "name" => "IDA WIJAYANTI", "password" => "9196"],
            // ["PersonnelNo" => "9199", "name" => "KHOSIROH FEBRIANI", "password" => "9199"],
            // ["PersonnelNo" => "9206", "name" => "AFRIDA MITA SYAHRIA", "password" => "9206"],
            // ["PersonnelNo" => "230", "name" => "MOH. ADI SUSANTO", "password" => "230"],
            // ["PersonnelNo" => "235", "name" => "MOCHAMAD UFRIYANTO", "password" => "235"],
            // ["PersonnelNo" => "232", "name" => "CAESAR JULIO SEBASTIAN TITO PUTRA JUNAEDI", "password" => "232"],
            // ["PersonnelNo" => "9216", "name" => "DESI ARSITASARI", "password" => "9216"],
            // ["PersonnelNo" => "92123", "name" => "HERI KRISTIONO", "password" => "92123"],
            // ["PersonnelNo" => "8948", "name" => "AFI GLEDISTIN", "password" => "8948"],
            // ["PersonnelNo" => "239", "name" => "MUHAMMAD DIMAS PRIYANTO", "password" => "239"],
            // ["PersonnelNo" => "255", "name" => "SUDARNO", "password" => "255"],
            // ["PersonnelNo" => "256", "name" => "YUSTIA GRESDIANTI", "password" => "256"],
            // ["PersonnelNo" => "257", "name" => "ANDRE ARENDRA", "password" => "257"],
            // ["PersonnelNo" => "8162", "name" => "MUHAMMAD NOOR", "password" => "8162"],
            // ["PersonnelNo" => "8159", "name" => "SRI WAHYUNI", "password" => "8159"],
            // ["PersonnelNo" => "8160", "name" => "SRI REJEKI HAPSARI", "password" => "8160"],
            // ["PersonnelNo" => "8161", "name" => "IWAN PURNAMA", "password" => "8161"],
            // ["PersonnelNo" => "8169", "name" => "KHASAN", "password" => "8169"],
            // ["PersonnelNo" => "260", "name" => "VAHLEVI PERMATASARI", "password" => "260"],
            // ["PersonnelNo" => "263", "name" => "CHOMSIAH", "password" => "263"],
            // ["PersonnelNo" => "5040", "name" => "YULI INDAH KUSWATI", "password" => "5040"],
            // ["PersonnelNo" => "264", "name" => "MAHARDIANA NURFIDAH", "password" => "264"],
            // ["PersonnelNo" => "265", "name" => "YUGFAR WICAKSONO", "password" => "265"],
            // ["PersonnelNo" => "266", "name" => "TUBAGUS AKHMAD RAMA FAUZI", "password" => "266"],
            // ["PersonnelNo" => "268", "name" => "HAFIS ALAMSYAH", "password" => "268"],
            // ["PersonnelNo" => "8179", "name" => "MUHAMMAD BAGJA AWALLUDIN MUGHNI", "password" => "8179"],
            // ["PersonnelNo" => "269", "name" => "MERCUSI DWINDA KARTIKASARI", "password" => "269"],
            // ["PersonnelNo" => "5042", "name" => "MEGA MUSLIANA", "password" => "5042"],
            // ["PersonnelNo" => "5044", "name" => "MARLIANA", "password" => "5044"],
            // ["PersonnelNo" => "5045", "name" => "SELVY KADIR", "password" => "5045"],
            // ["PersonnelNo" => "5047", "name" => "DENA ELVINA PRATIWI", "password" => "5047"],
            // ["PersonnelNo" => "8904", "name" => "TUTI SUGIYANTI", "password" => "8904"],
            // ["PersonnelNo" => "272", "name" => "NAURA CHAIRUNNISA SIGIT", "password" => "272"],
            // ["PersonnelNo" => "5050", "name" => "SARI FEBRIANA", "password" => "5050"],
            // ["PersonnelNo" => "273", "name" => "ANDRI YUDHA TIRTAYASA", "password" => "273"],
            // ["PersonnelNo" => "5051", "name" => "RITA MUSTOFIA", "password" => "5051"],
            // ["PersonnelNo" => "5065", "name" => "MEGA RAHMAWATI", "password" => "5065"],
            // ["PersonnelNo" => "5068", "name" => "FRANCISKA YULIANA", "password" => "5068"],
            // ["PersonnelNo" => "276", "name" => "DWIKI SATRIYO SANTOSO", "password" => "276"],
            // ["PersonnelNo" => "5072", "name" => "NURPADILA S", "password" => "5072"],
            // ["PersonnelNo" => "277", "name" => "AMRINA ROSYADA", "password" => "277"],
            // ["PersonnelNo" => "70031", "name" => "JULIANA EVASARI SIAHAAN", "password" => "70031"],
            // ["PersonnelNo" => "9222", "name" => "MUCHAMMAD ARIF HIDAYAH SAPUTRA", "password" => "9222"],
            // ["PersonnelNo" => "5078", "name" => "TINA ROCHAYATI", "password" => "5078"],
            // ["PersonnelNo" => "5086", "name" => "TRISWANTI", "password" => "5086"],
            // ["PersonnelNo" => "5090", "name" => "NANA ISTIANI", "password" => "5090"],
            // ["PersonnelNo" => "70036", "name" => "LIES MARINI", "password" => "70036"],
            // ["PersonnelNo" => "5000", "name" => "RISNA PUJI LESTARI", "password" => "5000"],
            // ["PersonnelNo" => "5096", "name" => "SUNGKONO", "password" => "5096"],
            // ["PersonnelNo" => "5095", "name" => "JEFRI POTUTU", "password" => "5095"],
            // ["PersonnelNo" => "5190", "name" => "PUTRI RAHAYU", "password" => "5190"],
            // ["PersonnelNo" => "283", "name" => "PADMAWURI FARADISY", "password" => "283"],
            // ["PersonnelNo" => "8290", "name" => "ERIC HASUARY", "password" => "8290"],
            // ["PersonnelNo" => "284", "name" => "OKTARINDA DAMAYANTI", "password" => "284"],
            // ["PersonnelNo" => "285", "name" => "RONY JATMIKO", "password" => "285"],
            // ["PersonnelNo" => "373", "name" => "JUAN ROONEY ADITIA YUDAN PRATAMA", "password" => "373"],
            // ["PersonnelNo" => "288", "name" => "KANTI APRILIONI", "password" => "288"],
            // ["PersonnelNo" => "289", "name" => "MOCHAMMAD SANDI", "password" => "289"],
            // ["PersonnelNo" => "8786", "name" => "NUNU RAHFLIA", "password" => "8786"],
            // ["PersonnelNo" => "5106", "name" => "GITA ASA PERDANA", "password" => "5106"],
            // ["PersonnelNo" => "292", "name" => "ANDRYAN RIZQI ADHCHA SUSANTO", "password" => "292"],
            // ["PersonnelNo" => "9229", "name" => "EVA NOVIANA WARDHANI", "password" => "9229"],
            // ["PersonnelNo" => "295", "name" => "NEHEMIA DWI PURWO NUGROHO", "password" => "295"],
            // ["PersonnelNo" => "300", "name" => "DWI PRADEVI YUNIARTA", "password" => "300"],
            // ["PersonnelNo" => "5114", "name" => "SITI NUR HOPIPAH", "password" => "5114"],
            // ["PersonnelNo" => "5117", "name" => "IRMA SULISTIA", "password" => "5117"],
            // ["PersonnelNo" => "301", "name" => "ALFIYATUS SHOLIKHAH", "password" => "301"],
            // ["PersonnelNo" => "302", "name" => "ANASTASIA ALVITADONA", "password" => "302"],
            // ["PersonnelNo" => "8306", "name" => "MOH. RAMDAN NGGILU", "password" => "8306"],
            // ["PersonnelNo" => "326", "name" => "KHANSA FADHILAH RAMADHANIA", "password" => "326"],
            // ["PersonnelNo" => "5119", "name" => "WINA SETIATI", "password" => "5119"],
            // ["PersonnelNo" => "308", "name" => "ALMAYANI NASUTION, S.KOM", "password" => "308"],
            // ["PersonnelNo" => "5124", "name" => "TARLIN WENDHANTI", "password" => "5124"],
            // ["PersonnelNo" => "8304", "name" => "JULITA TODING", "password" => "8304"],
            // ["PersonnelNo" => "8307", "name" => "FRANSYOROSMETLI AG", "password" => "8307"],
            // ["PersonnelNo" => "9232", "name" => "EKA PRATAMA SAPUTRA", "password" => "9232"],
            // ["PersonnelNo" => "9234", "name" => "WAHYU PUTRA RAMADANI", "password" => "9234"],
            // ["PersonnelNo" => "315", "name" => "BAGAS SGORO", "password" => "315"],
            // ["PersonnelNo" => "5126", "name" => "DIAH OKTAFIA", "password" => "5126"],
            // ["PersonnelNo" => "5128", "name" => "AMILIA VIDIA LAKSONO", "password" => "5128"],
            // ["PersonnelNo" => "8914", "name" => "SRI UMI RAHAYU, SE", "password" => "8914"],
            // ["PersonnelNo" => "317", "name" => "ZALIZA UBAIDA PURENITTA", "password" => "317"],
            // ["PersonnelNo" => "8916", "name" => "DHANI IKHSAN DERMAWAN", "password" => "8916"],
            // ["PersonnelNo" => "6007", "name" => "ERA WIJAYANTI", "password" => "6007"],
            // ["PersonnelNo" => "6008", "name" => "ERNIS RETNO HARDINI", "password" => "6008"],
            // ["PersonnelNo" => "6009", "name" => "ASRI KRISLANI", "password" => "6009"],
            // ["PersonnelNo" => "6010", "name" => "JUWARNI", "password" => "6010"],
            // ["PersonnelNo" => "6011", "name" => "ASTUTI SRI WIDIYATI", "password" => "6011"],
            // ["PersonnelNo" => "5131", "name" => "AI WAWA", "password" => "5131"],
            // ["PersonnelNo" => "8917", "name" => "ROSIANI MUSLIMAH", "password" => "8917"],
            // ["PersonnelNo" => "323", "name" => "DINY EKA SAVITRI", "password" => "323"],
            // ["PersonnelNo" => "8919", "name" => "ZUSA EFFENDI", "password" => "8919"],
            // ["PersonnelNo" => "9237", "name" => "MUHAMAD ALDINO WICAKSONO", "password" => "9237"],
            // ["PersonnelNo" => "9238", "name" => "ARISKY SATRIO UTOMO", "password" => "9238"],
            // ["PersonnelNo" => "324", "name" => "NUFIYANTO IRAWAN", "password" => "324"],
            // ["PersonnelNo" => "8921", "name" => "FITRIANI", "password" => "8921"],
            // ["PersonnelNo" => "6013", "name" => "SUWARSINI", "password" => "6013"],
            // ["PersonnelNo" => "6014", "name" => "ANANDA TUSTAMMA SALSABILA", "password" => "6014"],
            // ["PersonnelNo" => "6015", "name" => "KUSRINI", "password" => "6015"],
            // ["PersonnelNo" => "6016", "name" => "RETNO HARYANTI SETIOWATI", "password" => "6016"],
            // ["PersonnelNo" => "325", "name" => "PAULUS SUPRAYITNO", "password" => "325"],
            // ["PersonnelNo" => "5197", "name" => "RESTI FEBRIANI WULANDARI", "password" => "5197"],
            // ["PersonnelNo" => "8924", "name" => "LUH ENDRI APRILIANI", "password" => "8924"],
            // ["PersonnelNo" => "328", "name" => "RIDHA OCTA NUR AFIFAH", "password" => "328"],
            // ["PersonnelNo" => "6021", "name" => "INTAN PURNAMA SARI", "password" => "6021"],
            // ["PersonnelNo" => "6022", "name" => "NUR AKMALIA", "password" => "6022"],
            // ["PersonnelNo" => "6023", "name" => "ANSARIAH", "password" => "6023"],
            // ["PersonnelNo" => "6024", "name" => "DEWI MULYANI ASIH", "password" => "6024"],
            // ["PersonnelNo" => "5143", "name" => "ALFI ILMIYATUN NAFIAH", "password" => "5143"],
            // ["PersonnelNo" => "5144", "name" => "NOFI SULISTYOWATI", "password" => "5144"],
            // ["PersonnelNo" => "329", "name" => "A. GILANG ROMADHON", "password" => "329"],
            // ["PersonnelNo" => "8932", "name" => "JIHAN IBBTI SAMAH", "password" => "8932"],
            // ["PersonnelNo" => "6026", "name" => "TRI IS YANIK", "password" => "6026"],
            // ["PersonnelNo" => "6027", "name" => "PUTRI SRI DEVI", "password" => "6027"],
            // ["PersonnelNo" => "6033", "name" => "ENDANG SUPRIANI BR SEMBIRING", "password" => "6033"],
            // ["PersonnelNo" => "6035", "name" => "WIDI ERA PRATIWI", "password" => "6035"],
            // ["PersonnelNo" => "5151", "name" => "SILVIA V DONDONGI", "password" => "5151"],
            // ["PersonnelNo" => "5152", "name" => "ISTY KAMAH", "password" => "5152"],
            // ["PersonnelNo" => "6043", "name" => "SUSILAWATI", "password" => "6043"],
            // ["PersonnelNo" => "5199", "name" => "ADE SASTIKA", "password" => "5199"],
            // ["PersonnelNo" => "6051", "name" => "DEWI ASRIYANI", "password" => "6051"],
            // ["PersonnelNo" => "6055", "name" => "AFIFAH GHONIYAH RITONGA", "password" => "6055"],
            // ["PersonnelNo" => "6052", "name" => "EVA YULIANA", "password" => "6052"],
            // ["PersonnelNo" => "5156", "name" => "MONICA ANJELIA", "password" => "5156"],
            // ["PersonnelNo" => "8933", "name" => "MEILINA SITANGGANG", "password" => "8933"],
            // ["PersonnelNo" => "332", "name" => "PAULINUS DARMAN", "password" => "332"],
            // ["PersonnelNo" => "333", "name" => "HENDRIK EKO PRASETYO", "password" => "333"],
            // ["PersonnelNo" => "334", "name" => "RIZKY RAHAYU", "password" => "334"],
            // ["PersonnelNo" => "5159", "name" => "MEGAWATI", "password" => "5159"],
            // ["PersonnelNo" => "6060", "name" => "SENJAWATI", "password" => "6060"],
            // ["PersonnelNo" => "8937", "name" => "ARI AGUSTIN", "password" => "8937"],
            // ["PersonnelNo" => "337", "name" => "HO KEYNE", "password" => "337"],
            // ["PersonnelNo" => "5162", "name" => "SARIFAH AYU VITIOLA", "password" => "5162"],
            // ["PersonnelNo" => "6065", "name" => "SITI NURFADILAH", "password" => "6065"],
            // ["PersonnelNo" => "6066", "name" => "YULI YANTI", "password" => "6066"],
            // ["PersonnelNo" => "9240", "name" => "MOCH RIZAL ISNAN", "password" => "9240"],
            // ["PersonnelNo" => "341", "name" => "SYAIDAH ROHMATUL UMMAH", "password" => "341"],
            // ["PersonnelNo" => "343", "name" => "HILMI HAQQI SAUSANTI", "password" => "343"],
            // ["PersonnelNo" => "5164", "name" => "CITRA ARUM LESTARI", "password" => "5164"],
            // ["PersonnelNo" => "5166", "name" => "NI KOMANG DIVA SETIANI", "password" => "5166"],
            // ["PersonnelNo" => "5167", "name" => "MIRA NOVIANTI", "password" => "5167"],
            // ["PersonnelNo" => "5168", "name" => "NOVI ANDRIANI", "password" => "5168"],
            // ["PersonnelNo" => "5169", "name" => "YULIANI SAFITRI", "password" => "5169"],
            // ["PersonnelNo" => "8947", "name" => "VERONIKA DEWI PUSPITASARI W.", "password" => "8947"],
            // ["PersonnelNo" => "70037", "name" => "BUDI DARMAWAN", "password" => "70037"],
            // ["PersonnelNo" => "6072", "name" => "MARSA NOFIA", "password" => "6072"],
            // ["PersonnelNo" => "344", "name" => "MOHAMMAD REZKI MAULANA", "password" => "344"],
            // ["PersonnelNo" => "345", "name" => "FIRDA DWI HARYANTI", "password" => "345"],
            // ["PersonnelNo" => "346", "name" => "DEWI ZAHROTUN NISA", "password" => "346"],
            // ["PersonnelNo" => "347", "name" => "R. ALIFAN RAHMAT BAYU HARWANTO", "password" => "347"],
            // ["PersonnelNo" => "5171", "name" => "FEBI MELIYANA", "password" => "5171"],
            // ["PersonnelNo" => "335", "name" => "DIDIK EKO PRASETYO", "password" => "335"],
            // ["PersonnelNo" => "5173", "name" => "PUTRI PRATIWI", "password" => "5173"],
            // ["PersonnelNo" => "5176", "name" => "DINDA HALIFA HASAN", "password" => "5176"],
            // ["PersonnelNo" => "6079", "name" => "ENDANG LISMA AYU", "password" => "6079"],
            // ["PersonnelNo" => "6080", "name" => "NURUL FADILA AMALIA", "password" => "6080"],
            // ["PersonnelNo" => "351", "name" => "YEKTI YUSNIAN", "password" => "351"],
            // ["PersonnelNo" => "8952", "name" => "MIA EKA LESTARI", "password" => "8952"],
            // ["PersonnelNo" => "8954", "name" => "MASRUKI", "password" => "8954"],
            // ["PersonnelNo" => "354", "name" => "FEBIANTI YULIANA", "password" => "354"],
            // ["PersonnelNo" => "5182", "name" => "TITA SAPUTRI", "password" => "5182"],
            // ["PersonnelNo" => "5184", "name" => "RESMA FEBIAWANTICHA", "password" => "5184"],
            // ["PersonnelNo" => "5185", "name" => "SRI KURNIA INDRAWATI", "password" => "5185"],
            // ["PersonnelNo" => "5186", "name" => "YULTIANA SARTIKA ENDANG", "password" => "5186"],
            // ["PersonnelNo" => "6090", "name" => "SRI SUPATMI", "password" => "6090"],
            // ["PersonnelNo" => "356", "name" => "SANDRA LUKITA SARI", "password" => "356"],
            // ["PersonnelNo" => "8960", "name" => "FEBRIANSYAH PUTRA", "password" => "8960"],
            // ["PersonnelNo" => "5189", "name" => "MAYANGSARI", "password" => "5189"],
            // ["PersonnelNo" => "5191", "name" => "FIFI YUNITA TRISNA ASIH", "password" => "5191"],
            // ["PersonnelNo" => "6097", "name" => "DARMAWATI", "password" => "6097"],
            // ["PersonnelNo" => "6099", "name" => "ZULAYKA RAISYA PUTRI NST", "password" => "6099"],
            // ["PersonnelNo" => "8961", "name" => "BILKIS FAJARIAH", "password" => "8961"],
            // ["PersonnelNo" => "8962", "name" => "ELMI NURUL MAYASARI", "password" => "8962"],
            // ["PersonnelNo" => "5198", "name" => "DHANINTA REGGYANA", "password" => "5198"],
            // ["PersonnelNo" => "5200", "name" => "DIAH INDAH SARI", "password" => "5200"],
            // ["PersonnelNo" => "5201", "name" => "LOLITA MARTHINALOVA", "password" => "5201"],
            // ["PersonnelNo" => "8964", "name" => "SRI RAHMADANI", "password" => "8964"],
            // ["PersonnelNo" => "5202", "name" => "LUSIANA DAMAYANTI", "password" => "5202"],
            // ["PersonnelNo" => "5203", "name" => "TITIS YUNITA SARI", "password" => "5203"],
            // ["PersonnelNo" => "5206", "name" => "ATIKAH", "password" => "5206"],
            // ["PersonnelNo" => "5207", "name" => "SHAFIRA NAYA RAMADHANI", "password" => "5207"],
            // ["PersonnelNo" => "5208", "name" => "INTAN YULIANA", "password" => "5208"],
            // ["PersonnelNo" => "358", "name" => "HENDRA KRISTIAWAN", "password" => "358"],
            // ["PersonnelNo" => "5209", "name" => "SINTIA SANDI ALMALA", "password" => "5209"],
            // ["PersonnelNo" => "5211", "name" => "ZIZKA NUR AINI", "password" => "5211"],
            // ["PersonnelNo" => "6104", "name" => "PUTRI PATRICIA", "password" => "6104"],
            // ["PersonnelNo" => "6106", "name" => "KURNIAWATI", "password" => "6106"],
            // ["PersonnelNo" => "359", "name" => "CHURIL FIRDAH", "password" => "359"],
            // ["PersonnelNo" => "360", "name" => "DIAH PARAMITHA SARI", "password" => "360"],
            // ["PersonnelNo" => "8969", "name" => "I WAYAN SUWARTIKA", "password" => "8969"],
            // ["PersonnelNo" => "361", "name" => "MICHAEL PERSADA SEMBIRING", "password" => "361"],
            // ["PersonnelNo" => "362", "name" => "ABDUS SYUKUR", "password" => "362"],
            // ["PersonnelNo" => "8974", "name" => "HERIYANTO", "password" => "8974"],
            // ["PersonnelNo" => "8978", "name" => "MASNI MUSTIR", "password" => "8978"],
            // ["PersonnelNo" => "364", "name" => "NUR AGHNAITA HAYATI", "password" => "364"],
            // ["PersonnelNo" => "5212", "name" => "INTAN SARI HARUMNISA", "password" => "5212"],
            // ["PersonnelNo" => "5213", "name" => "SEPTI ADELIA", "password" => "5213"],
            // ["PersonnelNo" => "5215", "name" => "SISKA RANI DEVA YANTI", "password" => "5215"],
            // ["PersonnelNo" => "5216", "name" => "YULIANA B", "password" => "5216"],
            // ["PersonnelNo" => "5217", "name" => "RAHMAWATI", "password" => "5217"],
            // ["PersonnelNo" => "5218", "name" => "NINI RAMADANTI", "password" => "5218"],
            // ["PersonnelNo" => "5219", "name" => "NENENG SRIATIKAH IRMAWATI", "password" => "5219"],
            // ["PersonnelNo" => "6119", "name" => "YAYUK SUSANTI", "password" => "6119"],
            // ["PersonnelNo" => "6120", "name" => "KISTIN MUTAWASITOH", "password" => "6120"],
            // ["PersonnelNo" => "6123", "name" => "NURHASANAH", "password" => "6123"],
            // ["PersonnelNo" => "6129", "name" => "RIZKI DWI UTARI", "password" => "6129"],
            // ["PersonnelNo" => "6130", "name" => "LINDA SARI", "password" => "6130"],
            // ["PersonnelNo" => "366", "name" => "KHARISMA FIRDAUS", "password" => "366"],
            // ["PersonnelNo" => "8982", "name" => "NITA SUNDARI", "password" => "8982"],
            // ["PersonnelNo" => "8985", "name" => "STHECY WIDYA NENGSY KELMASKOSSU", "password" => "8985"],
            // ["PersonnelNo" => "367", "name" => "JANUAR DIMAS RIFA'I", "password" => "367"],
            // ["PersonnelNo" => "5223", "name" => "VITRI GUSTINI", "password" => "5223"],
            // ["PersonnelNo" => "368", "name" => "RHEVINDRA PERMATA ANGGRIAWAN", "password" => "368"],
            // ["PersonnelNo" => "5224", "name" => "PUTRI IZZANA SYAHFIRA", "password" => "5224"],
            // ["PersonnelNo" => "9242", "name" => "LULUB AZIZAH RETNOWATI", "password" => "9242"],
            // ["PersonnelNo" => "9244", "name" => "FILKANOVA ERFIN", "password" => "9244"],
            // ["PersonnelNo" => "369", "name" => "IFTIROSYA HAKIKIA", "password" => "369"],
            // ["PersonnelNo" => "5228", "name" => "NENY LUTFIANI", "password" => "5228"],
            // ["PersonnelNo" => "5230", "name" => "MEGA NARVIA", "password" => "5230"],
            // ["PersonnelNo" => "5231", "name" => "ICHA TRIWAHYUNI", "password" => "5231"],
            // ["PersonnelNo" => "370", "name" => "NISA ARIFIA", "password" => "370"],
            // ["PersonnelNo" => "8990", "name" => "APRIYANTI", "password" => "8990"],
            // ["PersonnelNo" => "371", "name" => "MUHAMMAD MUNIR", "password" => "371"],
            // ["PersonnelNo" => "372", "name" => "DEWI SINTA ANDANI", "password" => "372"],
            // ["PersonnelNo" => "5232", "name" => "DESI YULVINA BAHRI", "password" => "5232"],
            // ["PersonnelNo" => "5234", "name" => "TIYAS WINDYANDINI", "password" => "5234"],
            // ["PersonnelNo" => "375", "name" => "AYU AZZAHRA NAILA FANI", "password" => "375"],
            // ["PersonnelNo" => "9246", "name" => "MUHAMMAD NUR AGUNG LAKSONO", "password" => "9246"],
            // ["PersonnelNo" => "70040", "name" => "ENDAH LESTARI SUPARDI", "password" => "70040"],
            // ["PersonnelNo" => "5235", "name" => "NOVA SOPIANA", "password" => "5235"],
            // ["PersonnelNo" => "5236", "name" => "MAULINA HANDAYANI", "password" => "5236"],
            // ["PersonnelNo" => "5237", "name" => "SUKESIH", "password" => "5237"],
            // ["PersonnelNo" => "5238", "name" => "DIAH WAHYU ANDRIANI", "password" => "5238"],
            // ["PersonnelNo" => "5240", "name" => "YANI MULYANINGSIH", "password" => "5240"],
            // ["PersonnelNo" => "6145", "name" => "RANI ANGGRAINI", "password" => "6145"],
            // ["PersonnelNo" => "6147", "name" => "MUMUN SITI MUNASIH", "password" => "6147"],
            // ["PersonnelNo" => "6149", "name" => "SALIYAH EGI ANDISTA", "password" => "6149"],
            // ["PersonnelNo" => "6150", "name" => "SUSTER DEWI SINAMBELA,S.E", "password" => "6150"],
            // ["PersonnelNo" => "6151", "name" => "DEWI SARTINA", "password" => "6151"],
            // ["PersonnelNo" => "8997", "name" => "WIDYA SEPTIA NINGSIH", "password" => "8997"],
            // ["PersonnelNo" => "8996", "name" => "KUSNUL ARIFAH", "password" => "8996"],
            // ["PersonnelNo" => "381", "name" => "NIKEN AYU SAFITRI", "password" => "381"],
            // ["PersonnelNo" => "8998", "name" => "IKA HANDINI", "password" => "8998"],
            // ["PersonnelNo" => "8999", "name" => "SUKMA KARTIKA RUBYASARI", "password" => "8999"],
            // ["PersonnelNo" => "383", "name" => "PUTRIANY RAHMAWATI", "password" => "383"],
            // ["PersonnelNo" => "384", "name" => "MAULIDA ALFINA ZAHRO", "password" => "384"],
            // ["PersonnelNo" => "8200", "name" => "AGUS HIDAYAT", "password" => "8200"],
            // ["PersonnelNo" => "385", "name" => "I GUSTI NGURAH AGUNG OKA DHANA, S.SI", "password" => "385"],
            // ["PersonnelNo" => "5241", "name" => "HERLINA QURROTA'AINI", "password" => "5241"],
            // ["PersonnelNo" => "5243", "name" => "REZKY MILARAHMA", "password" => "5243"],
            // ["PersonnelNo" => "5245", "name" => "FATIMAH AZZAHRA", "password" => "5245"],
            // ["PersonnelNo" => "5242", "name" => "LIA DESI SETYA PURWANTI", "password" => "5242"],
            // ["PersonnelNo" => "6155", "name" => "MUHAMMAD ALIMIN", "password" => "6155"],
            // ["PersonnelNo" => "6156", "name" => "FITRIANA", "password" => "6156"],
            // ["PersonnelNo" => "6158", "name" => "ERNAWATY MALAU", "password" => "6158"],
            // ["PersonnelNo" => "387", "name" => "SITI MAYASAROH", "password" => "387"],
            // ["PersonnelNo" => "80001", "name" => "GREGORIUS SEPTIAN HANGGARA", "password" => "80001"],
            // ["PersonnelNo" => "80003", "name" => "MOCH EFENDI", "password" => "80003"],
            // ["PersonnelNo" => "80004", "name" => "DEWI MURNIATI", "password" => "80004"],
            // ["PersonnelNo" => "5248", "name" => "TETI SUAINI", "password" => "5248"],
            // ["PersonnelNo" => "5249", "name" => "DYAH PARAMITHA HASAN", "password" => "5249"],
            // ["PersonnelNo" => "5251", "name" => "QORRI AININA", "password" => "5251"],
            // ["PersonnelNo" => "6161", "name" => "MUSTIKA SARI", "password" => "6161"],
            // ["PersonnelNo" => "6162", "name" => "INDRI NOVALINDA", "password" => "6162"],
            // ["PersonnelNo" => "6163", "name" => "NURIDAWATI", "password" => "6163"],
            // ["PersonnelNo" => "6164", "name" => "HENY MAHENDRAYANI", "password" => "6164"],
            // ["PersonnelNo" => "391", "name" => "SHABRINA FIRDATUL JANNAH", "password" => "391"],
            // ["PersonnelNo" => "390", "name" => "NADA NABEELA OKTAVIARTA", "password" => "390"],
            // ["PersonnelNo" => "389", "name" => "ALIEF PUTRI PARAWANGSA JUHARTO", "password" => "389"],
            // ["PersonnelNo" => "388", "name" => "IRMA RETNO DEWI", "password" => "388"],
            // ["PersonnelNo" => "392", "name" => "LUTHFIATUL LAILY FIRDAUSI", "password" => "392"],
            // ["PersonnelNo" => "80005", "name" => "GUNAWAN KURNIANTO", "password" => "80005"],
            // ["PersonnelNo" => "80007", "name" => "FAZLUL ROZI", "password" => "80007"],
            // ["PersonnelNo" => "80008", "name" => "NOVITA SILVIA SIREGAR", "password" => "80008"],
            // ["PersonnelNo" => "393", "name" => "MOHAMAD ZAINI", "password" => "393"],
            // ["PersonnelNo" => "80009", "name" => "MUHARIANI SUMIA NINGSIH", "password" => "80009"],
            // ["PersonnelNo" => "395", "name" => "EGGY FIRMANSYAH", "password" => "395"],
            // ["PersonnelNo" => "80010", "name" => "SISKA YULIA", "password" => "80010"],
            // ["PersonnelNo" => "9247", "name" => "MUCHAMMAD ARDIANSYAH", "password" => "9247"],
            // ["PersonnelNo" => "9248", "name" => "BIAGGI ARICO SEMBIRING", "password" => "9248"],
            // ["PersonnelNo" => "5252", "name" => "SITI MARIAM", "password" => "5252"],
            // ["PersonnelNo" => "9250", "name" => "NOVI FERNANDA", "password" => "9250"],
            // ["PersonnelNo" => "9251", "name" => "LAILYA RACHMAWATI", "password" => "9251"],
            // ["PersonnelNo" => "6165", "name" => "NUNUNG NURHAYATI", "password" => "6165"],
            // ["PersonnelNo" => "6166", "name" => "DAYU PUTRI LESTARI", "password" => "6166"],
            // ["PersonnelNo" => "6167", "name" => "NENA LUSTIWATI", "password" => "6167"],
            // ["PersonnelNo" => "6168", "name" => "VERAWATY HERDANI", "password" => "6168"],
            // ["PersonnelNo" => "396", "name" => "ACH. ROBBY AL FAZRI", "password" => "396"],
            // ["PersonnelNo" => "6170", "name" => "SRI WAHYUNI", "password" => "6170"],
            // ["PersonnelNo" => "6171", "name" => "VIVI ARYANI", "password" => "6171"],
            // ["PersonnelNo" => "6172", "name" => "JIHAN GOLDAREN MAHENDRA", "password" => "6172"],
            // ["PersonnelNo" => "80011", "name" => "RIYA AGUSTINI", "password" => "80011"],
            // ["PersonnelNo" => "8096", "name" => "DJUNAIDI", "password" => "8096"],
            // ["PersonnelNo" => "80012", "name" => "ANNISA SEPTIANI", "password" => "80012"],
            // ["PersonnelNo" => "80013", "name" => "KUSMIATI", "password" => "80013"],
            // ["PersonnelNo" => "80014", "name" => "MUHAMMAD FAJAR ROMADHON", "password" => "80014"],
            // ["PersonnelNo" => "9252", "name" => "MUHAMMAD AMIN ROBIHAM", "password" => "9252"],
            // ["PersonnelNo" => "9253", "name" => "FANDHI ACHMAD", "password" => "9253"],
            // ["PersonnelNo" => "5253", "name" => "DWITA TRI ASHAYU", "password" => "5253"],
            // ["PersonnelNo" => "5254", "name" => "AYANG ADELIA", "password" => "5254"],
            // ["PersonnelNo" => "5255", "name" => "HERLINA SUSANTI", "password" => "5255"],
            // ["PersonnelNo" => "5256", "name" => "DESABELLA BRILIANTIN", "password" => "5256"],
            // ["PersonnelNo" => "80015", "name" => "JUNIARTI PRASSETYO", "password" => "80015"],
            // ["PersonnelNo" => "397", "name" => "NOVI ERNAWATI", "password" => "397"],
            // ["PersonnelNo" => "80016", "name" => "HANNISA", "password" => "80016"],
            // ["PersonnelNo" => "80017", "name" => "STIVANA MARGARETHA SUPIT", "password" => "80017"],
            // ["PersonnelNo" => "80018", "name" => "ELA HAMIDA", "password" => "80018"],
            // ["PersonnelNo" => "9254", "name" => "NANDA ALFIRA", "password" => "9254"],
            // ["PersonnelNo" => "9255", "name" => "DYVA SISILYA DWI MARGARETNA", "password" => "9255"],
            // ["PersonnelNo" => "70042", "name" => "TUTI ALAWIYAH", "password" => "70042"],
            // ["PersonnelNo" => "80019", "name" => "RISKA WAHYUNINGTIAS", "password" => "80019"],
            // ["PersonnelNo" => "6173", "name" => "NURHIJMAH", "password" => "6173"],
            // ["PersonnelNo" => "6174", "name" => "RETNO HARYANTI", "password" => "6174"],
            // ["PersonnelNo" => "6175", "name" => "UHA JUHATI", "password" => "6175"],
            // ["PersonnelNo" => "6176", "name" => "DIAH RIZKY RAMADHANI", "password" => "6176"],
            // ["PersonnelNo" => "6177", "name" => "RIRIS VALENTINA HUTAJULU", "password" => "6177"],
            // ["PersonnelNo" => "6178", "name" => "NOVA AULIA", "password" => "6178"],
            // ["PersonnelNo" => "6179", "name" => "NENI ANDLINA KOTO", "password" => "6179"],
            // ["PersonnelNo" => "6180", "name" => "SAFRINA", "password" => "6180"],
            // ["PersonnelNo" => "80020", "name" => "ADITYA ARBI HIMAWAN", "password" => "80020"],
            // ["PersonnelNo" => "8097", "name" => "ANGGI DWI HANDAYANI", "password" => "8097"],
            // ["PersonnelNo" => "8098", "name" => "HABAKUK", "password" => "8098"],
            // ["PersonnelNo" => "8099", "name" => "SEVI NUR JANNAH", "password" => "8099"],
            // ["PersonnelNo" => "273", "name" => "ANDRI YUDHA TIRTAYASA", "password" => "273"],
            // ["PersonnelNo" => "347", "name" => "R. ALIFAN RAHMAT BAYU HARWANTO", "password" => "347"],
            // ["PersonnelNo" => "9091", "name" => "DIMAS BUKHIN NUGRAHA", "password" => "9091"],
            // ["PersonnelNo" => "8008", "name" => "A.M. AKBAR", "password" => "8008"],
            // ["PersonnelNo" => "70004", "name" => "BAYU SETIYAWAN", "password" => "70004"],
            ["PersonnelNo" => "418", "name" => "HERI RAMADHAN RS", "password" => "418"],
            // Tambahkan data lainnya...
        ];

        foreach ($data as $user) {
            DB::table('tbl_user_hris_absen')->insert([
                'PersonnelNo' => $user['PersonnelNo'],
                'name' => $user['name'],
                'password' => Hash::make($user['password']),
            ]);
        }
    }
}
